### ISSUE TITLE
Update datasets to 2.11.0

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1002]
See https://github.com/huggingface/datasets/releases/tag/2.11.0

TODO: See discussions below
- [x] #1009
- [x] #1280
- [x] #1281
- [x] Use writer_batch_size for ArrowBasedBuilder
- [ ] Use direct cast from binary to Audio/Image
- [ ] Refresh datasets that use numpy.load

Useful changes for the datasets server (please complete if there are more, @huggingface/datasets)

> Use soundfile for mp3 decoding instead of torchaudio by @polinaeterna in https://github.com/huggingface/datasets/pull/5573
> 
>  - this allows to not have dependencies on pytorch to decode audio files
>  - this was possible with soundfile 0.12 which bundles libsndfile binaries at a recent version with MP3 support

should we remove the dependency to torch and torchaudio? cc @polinaeterna

> Add writer_batch_size for ArrowBasedBuilder by @lhoestq in https://github.com/huggingface/datasets/pull/5565
> - allow to specofy the row group / record batch size when you download_and_prepare() a dataset

Needed for https://github.com/huggingface/datasets-server/pull/833 I think; cc @lhoestq 

> Allow direct cast from binary to Audio/Image by @mariosasko in https://github.com/huggingface/datasets/pull/5644

Should we adapt the code in https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/features.py due to that?

> Support streaming datasets with numpy.load by @albertvillanova in https://github.com/huggingface/datasets/pull/5626

should we refresh some datasets after that?

**Comment by albertvillanova** [comment]
I would suggest splitting this issue into several minor ones. I'm editing the description above...

**Comment by severo** [comment]
Keep open. Note also #1099 to upgrade to 2.12.0

**Comment by albertvillanova** [comment]
Keep open

**Comment by albertvillanova** [comment]
I think "Use writer_batch_size for ArrowBasedBuilder" is already done by:
- #833

CC: @lhoestq @severo
