### ISSUE TITLE
Remove authentication by cookie?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1011]
Currently, to be able to return the contents for gated datasets, all the endpoints check the request credentials if needed. The accepted credentials are: HF token, HF cookie, or a JWT in `X-Api-Key`. See https://github.com/huggingface/datasets-server/blob/ecb861b5e8d728b80391f580e63c8d2cad63a1fc/services/api/src/api/authentication.py#L26

Should we remove the cookie authentication?

cc @coyotte508 @SBrandeis @XciD @rtrompier

**Comment by coyotte508** [comment]
not sure, maybe when it times out we want the user to call datasets-server on the frontend-side? In that case we would need the cookie

**Comment by severo** [comment]
OK, thanks! Closing.

**Comment by severo** [comment]
re-opening. We don't use it from the Hub. If needed, we can reopen later. Anyway, it's not working as expected for now (see #1683).

**Comment by severo** [comment]
@coyotte508 had the idea of removing JWT and using cookie instead for the frontend requests. Let's keep open.

**Comment by severo** [comment]
see #2052.

**Comment by severo** [comment]
Done with #2580
