### ISSUE TITLE
Dataset Viewer issue for nlpconnect/DocVQA

### ISSUE THREAD

**Issue by tbeijloos** [huggingface/datasets-server#1012]
### Link

https://huggingface.co/datasets/nlpconnect/DocVQA

### Description

The dataset viewer is not working for dataset nlpconnect/DocVQA.

Error details:

```
Error code:   ResponseNotFound

```

**Comment by albertvillanova** [comment]
@tbeijloos please note that your dataset repository is empty: no data files nor Python loading script.

See: https://huggingface.co/datasets/nlpconnect/DocVQA/tree/main

If you need help to create a dataset, please have a look at our docs: https://huggingface.co/docs/datasets/upload_dataset
