### ISSUE TITLE
Dataset Viewer issue for THUIR/T2Ranking

### ISSUE THREAD

**Issue by Deriq-Qian-Dong** [huggingface/datasets-server#1015]
### Link

https://huggingface.co/datasets/THUIR/T2Ranking

### Description

The dataset viewer is not working for dataset THUIR/T2Ranking.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
@Deriq-Qian-Dong please note that the dataset viewer may take some time until it works properly: the `ResponseNotReady` meand that it is still processing.

Note that the dataset viewer is working now.
![Screenshot from 2023-04-06 10-35-34](https://user-images.githubusercontent.com/8515462/230322208-f7de1d54-02ee-4b46-ad4e-71c35a8d0193.png)
