### ISSUE TITLE
Dataset Viewer issue for RUCAIBox/Data-to-text-Generation

### ISSUE THREAD

**Issue by hoboyu11** [huggingface/datasets-server#1018]
### Link

https://huggingface.co/datasets/RUCAIBox/Data-to-text-Generation

### Description

The dataset viewer is not working for dataset RUCAIBox/Data-to-text-Generation.

Error details:

```
Error code:   ResponseNotFound

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @hoboyu11.

Please note that this is not an issue with the viewer itself: your dataset does not load.

Note that `.tgz` data files are not supported and you would need to:
- Either changing the archive file format to a supported one, like `.zip`
- Or implement a Python loading script; see docs here: [Create a dataset loading script](https://huggingface.co/docs/datasets/v2.11.0/en/dataset_script)

I have opened a discussion in the "Community" tab of your dataset.
Let's continue the discussion there.
