### ISSUE TITLE
Dataset Viewer issue for Inspire-art/final

### ISSUE THREAD

**Issue by AMEERAZAM08** [huggingface/datasets-server#1038]
### Link

https://huggingface.co/datasets/Inspire-art/final

### Description

The dataset viewer is not working for dataset Inspire-art/final.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @AMEERAZAM08.

Apparently you have deleted the dataset: we get a 404 error from the URL above.

**Comment by AMEERAZAM08** [comment]
Thanks
