### ISSUE TITLE
Dataset Viewer issue for banking77

### ISSUE THREAD

**Issue by aman-tandon-30** [huggingface/datasets-server#1049]
### Link

https://huggingface.co/datasets/banking77

### Description

The dataset viewer is not working for dataset banking77.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @aman-tandon-30.

We are investigating it.

**Comment by albertvillanova** [comment]
The viewer is working now.

![Screenshot from 2023-04-17 15-58-15](https://user-images.githubusercontent.com/8515462/232506465-a7635c3d-6bc2-4b06-aa44-21ec74c518de.png)
