### ISSUE TITLE
Dataset Viewer issue for austint73/butterfly_dataset

### ISSUE THREAD

**Issue by jS5t3r** [huggingface/datasets-server#1051]
### Link

https://huggingface.co/datasets/austint73/butterfly_dataset

### Description

The dataset viewer is not working for dataset austint73/butterfly_dataset.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Please note that the dataset contains no files, besides the default `.gitattributes`.

![Screenshot from 2023-04-18 08-17-08](https://user-images.githubusercontent.com/8515462/232688190-cec5dfb4-d2b6-4ba6-8c3a-ccf70c4d0d4f.png)

You can contact the dataset owner to inform them about this, by using the "Community" tab in their dataset: https://huggingface.co/datasets/austint73/butterfly_dataset/discussions

**Comment by jS5t3r** [comment]
Ok. Thanks
