### ISSUE TITLE
Dataset Viewer issue for togethercomputer/RedPajama-Data-1T

### ISSUE THREAD

**Issue by carlosseda** [huggingface/datasets-server#1055]
### Link

https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T

### Description

The dataset viewer is not working for dataset togethercomputer/RedPajama-Data-1T.

Error details:

```
Error code:   PreviousStepFormatError

```

**Comment by severo** [comment]
Working on it

**Comment by albertvillanova** [comment]
The viewer is working fine now:

![Screenshot from 2023-04-19 12-36-26](https://user-images.githubusercontent.com/8515462/233049503-252e3fb1-83da-45ee-85c9-c7043d855986.png)

CC: @severo 

Also note that this issue page is getting filled with many cross-references, because of the commit messages...
