### ISSUE TITLE
Dataset Viewer issue for InstaDeepAI/human_reference_genome

### ISSUE THREAD

**Issue by dallatt** [huggingface/datasets-server#1067]
### Link

https://huggingface.co/datasets/InstaDeepAI/human_reference_genome

### Description

The dataset viewer is not working for dataset InstaDeepAI/human_reference_genome.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @dallatt.

Please note that your loading script is using a specific package called `Bio` that is not installed in our viewer servers, thus raising a 500 error.

@severo I think we should better handle third-party dependencies and raise a more descriptive error message. What do you think?

**Comment by dallatt** [comment]
Hello @albertvillanova @severo ,

Thank you for the answer and sorry for the delay, I completely missed the notification.

I understand the problem. Is there any way we can still use the dataset viewer with maybe a small setup script that installs `Bio` if it is not present in the user's environment?

**Comment by severo** [comment]
Hi @dallatt. For now, it's not possible to install custom dependencies. We discuss the issue at https://github.com/huggingface/datasets-server/issues/599#issuecomment-1318931976. Not sure if we will implement it though, at least we don't have an ETA.

**Comment by dallatt** [comment]
Will follow this closely, thank you !

**Comment by severo** [comment]
Should we close since we will not support script based datasets?

**Comment by severo** [comment]
Note that the current behavior (`DatasetModuleNotInstalledError` instead of dataset script not supported) is incorrect.

**Comment by severo** [comment]
closing, and see https://github.com/huggingface/datasets-server/issues/2385 as a follow-up
