### ISSUE TITLE
Dataset Viewer issue for InstaDeepAI/multi_species_genomes

### ISSUE THREAD

**Issue by dallatt** [huggingface/datasets-server#1068]
### Link

https://huggingface.co/datasets/InstaDeepAI/multi_species_genomes

### Description

The dataset viewer is not working for dataset InstaDeepAI/multi_species_genomes.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
duplicate of https://github.com/huggingface/datasets-server/issues/1067
