### ISSUE TITLE
Dataset Viewer issue for michaelwzhu/ChatMed-Datasets

### ISSUE THREAD

**Issue by michael-wzhu** [huggingface/datasets-server#1071]
### Link

https://huggingface.co/datasets/michaelwzhu/ChatMed-Datasets

### Description

The dataset viewer is not working for dataset michaelwzhu/ChatMed-Datasets.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Thanks for reporting! We've had an issue tonight in the infrastructure; it's fixed now.

<img width="1023" alt="Capture d’écran 2023-04-21 à 10 07 41" src="https://user-images.githubusercontent.com/1676121/233580037-aa1bd365-a2d9-4e09-8bbf-eeb8d6db5f46.png">
