### ISSUE TITLE
Dataset Viewer issue for masakhane/afriqa

### ISSUE THREAD

**Issue by ToluClassics** [huggingface/datasets-server#1082]
### Link

https://huggingface.co/datasets/masakhane/afriqa

### Description

The dataset viewer is not working for dataset masakhane/afriqa.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @ToluClassics.

The viewer needs some time to process the dataset and render the view, depending on the number of jobs in the queue. Normally, when you find a `ResponseNotReady` error, you have just to wait until it is processed and refresh the view page.

Your dataset has been eventually processed and it no longer shows a `ResponseNotReady` error. However, it now shows a `FileNotFoundError`:
```
FileNotFoundError: [Errno 2] No such file or directory: 'https://github.com/masakhane-io/afriqa/raw/main/data/queries/bem/queries.afriqa.bem.en.train.json'
```
I have opened a discussion on the Community tab of the dataset: https://huggingface.co/datasets/masakhane/afriqa/discussions/1
Let's continue the discussion there.
