### ISSUE TITLE
What's left in refactoring of processing steps and endpoints

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets-server#1086]
Here I want to summarize once again the final changes that we need to make datasets-server consistent in naming and logic, see https://github.com/huggingface/datasets-server/issues/867 (because it's all scattered in comments to different issues)

## Rename steps

- [x] `/split-names-from-streaming` -> `config-split-names-from-streaming` https://github.com/huggingface/datasets-server/pull/1168
- [x] `/split-names-from-dataset-info` -> `config-split-names-from-info` https://github.com/huggingface/datasets-server/pull/1226
- [x] `/config-names` -> `dataset-config-names` https://github.com/huggingface/datasets-server/pull/1246

## Delete steps

- [x] `parquet-and-dataset-info` https://github.com/huggingface/datasets-server/pull/1043
- [x] `dataset-split-names-from-streaming` https://github.com/huggingface/datasets-server/pull/1106
- [x] `dataset-split-names-from-dataset-info` https://github.com/huggingface/datasets-server/pull/1141

## Endpoints
- [x] `/dataset-info` -> `/info` https://github.com/huggingface/datasets-server/pull/1468
- [x] delete `/parquet-and-dataset-info` https://github.com/huggingface/datasets-server/pull/1488
- [x] delete `/config-names`

## Misc
- [x] update the docs 
- [x] update the OpenAPI spec.

**Comment by severo** [comment]
> /split-names-from-streaming -> split-names-from-streaming
> /split-names-from-dataset-info -> /split-names-from-info
> /config-names -> config-names

I think it's:

/split-names-from-streaming -> config-split-names-from-streaming
/split-names-from-dataset-info -> config-split-names-from-info
/config-names -> config-names -> dataset-config-names

**Comment by severo** [comment]
> Rename endpoints - should we?
>
> /dataset-info -> /info
> /parquet-and-dataset-info -> /parquet-and-info - do we need this endpoint actually?

The endpoints are defined here: https://github.com/huggingface/datasets-server/blob/main/services/api/src/api/config.py#L118

OK to remove `/parquet-and-dataset-info`
OK to rename `/dataset-info` to `/info`

Maybe we could have a better name than "/opt-in-out-urls-scan"
And also: it's inconsistent to have "/config-names" but "/splits". Maybe rename "/config-names" to "/configs", or remove it altogether?

**Comment by severo** [comment]
Finally: to finish this "cycle", we also have to update the docs and the OpenAPI spec.

**Comment by polinaeterna** [comment]
> I think it's:
> 
> /split-names-from-streaming -> config-split-names-from-streaming
> /split-names-from-dataset-info -> config-split-names-from-info
> /config-names -> config-names -> dataset-config-names

Hah yes thanks! changed the description

> it's inconsistent to have /config-names but /splits. Maybe rename /config-names to /configs; or remove it altogether?

Hm true but we also have "split-names" in names of steps, in `/split-names-from-streaming` and `/split-names-from-dataset-info` that are just supposed to be renamed. So maybe we can:
1. either
  - preserve **`/config-names`** endpoint
  - `/splits` endpoint -> **`/split-names`**
  - `/split-names-from-streaming` step -> **`config-split-names-from-streaming`**
  - `/split-names-from-dataset-info` step -> **`config-split-names-from-info`**
2. or
- preserve **`/splits`** endpoint
- `/config-names` endpoint -> **`/configs`**
- `/config-names` step -> **`dataset-configs`**
- `/split-names-from-streaming` step -> **`config-splits-from-streaming`**
- `/split-names-from-dataset-info` step -> **`config-splits-from-info`**

The 2nd option looks neater to me (=less symbols :D), wdyt?

**Comment by polinaeterna** [comment]
> remove the /config-names endpoint (not documented for now, not used in the Hub)

I agree it's kinda redundant since `/splits` returns the same information just with additional info (split, num_bytes...). Let's remove it then.

> let -names in the step names (less work

We need to change the names of exactly these steps anyway according to this plan so it's not gonna be any additional work.
But I'm okay with letting `-names` in steps too.

**Comment by severo** [comment]
>  But I'm okay with letting -names in steps too.

to be honest, I'm OK with both: keeping or changing. BTW I think that the https://github.com/huggingface/datasets library also uses both terms (splits / split_names) interchangeabily depending on the file.

> so it's not gonna be any additional work

OK. I'm just wondering if it will not imply changing the names of the methods, the tests, etc.

**Comment by severo** [comment]
Is the only remaning task removing the `/config-names` endpoint @polinaeterna?

**Comment by polinaeterna** [comment]
@severo i think it's all the tasks that are not marked as closed here (except for OpenAPI specs?)

**Comment by severo** [comment]
OK. Does someone want to finish this? @huggingface/datasets-server

**Comment by severo** [comment]
closing, as everything has been done, afaik
