### ISSUE TITLE
Dataset Viewer issue for cbt

### ISSUE THREAD

**Issue by lowestbuaaer** [huggingface/datasets-server#1095]
### Link

https://huggingface.co/datasets/cbt

### Description

The dataset viewer is not working for dataset cbt.

Error details:

```
Error code:   ResponseAlreadyComputedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @lowestbuaaer.

Indeed the source data URLs are no longer accessible, raising a 404 Not Found error. See the corresponding issue:
- https://huggingface.co/datasets/cbt/discussions/2
Let's continue the discussion about this specific issue there.

On the other hand, @severo do you know why the viewer shows this `ResponseAlreadyComputedError` message?
- I think we should improve this

**Comment by lowestbuaaer** [comment]
Thank you for your quick reply!

**Comment by severo** [comment]
Fixed
<img width="1030" alt="Capture d’écran 2023-05-02 à 10 06 21" src="https://user-images.githubusercontent.com/1676121/235612956-560d2c89-03f9-4fa9-9b5b-384f9a7c84eb.png">
