### ISSUE TITLE
Dataset Viewer issue for poloclub/diffusiondb

### ISSUE THREAD

**Issue by vkvickkey** [huggingface/datasets-server#1112]
### Link

https://huggingface.co/datasets/poloclub/diffusiondb

### Description

The dataset viewer is not working for dataset poloclub/diffusiondb.

Error details:

```
Error code:   UnexpectedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @vkvickkey.

We had an issue on the Hub that is fixed now.

The viewer is working now:
![Screenshot from 2023-05-17 11-36-12](https://github.com/huggingface/datasets-server/assets/8515462/fc707092-8ef4-41dd-a29a-6a39c16444e1)

**Comment by vkvickkey** [comment]
@albertvillanova tanks brother
