### ISSUE TITLE
Create a cronjob to clean the dangling cache directories

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1122]
Currently, the disk used to store the `datasets` library cache for the workers is full (shortage of inodes). It's mainly due to dangling cache directories from days or weeks. We should create a cronjob that runs every day, and deletes the directories older than 2 days.

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
fyi, to clean directories older than 3 days:

```bash
find . -maxdepth 1 -mtime +6 -type d -exec rm -r {} +
```

**Comment by severo** [comment]
keep open.

**Comment by severo** [comment]
I think it has been done for all the cache directories, right @AndreaFrancis?

**Comment by AndreaFrancis** [comment]
Yes, it is enabled for: duckdb-index, hf-datasets-cache and stats-cache
