### ISSUE TITLE
Dataset viewer issue for wikitext: wrong number of pages

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1126]
It shows only 44 pages at https://huggingface.co/datasets/wikitext even though the dataset has more than 1M rows

**Comment by severo** [comment]
I think it's OK, because the split has 4360 rows.

<img width="1028" alt="Capture d’écran 2023-05-03 à 13 28 09" src="https://user-images.githubusercontent.com/1676121/235903588-7acc62b8-35ec-4db1-8455-02b74fa6023b.png">

**Comment by lhoestq** [comment]
Ah yes sorry ! Maybe we should show "train" as the first split though

**Comment by severo** [comment]
The datasets-server respects the order given by the datasets library, in this case, the list of splits is given by the script: https://huggingface.co/datasets/wikitext/blob/main/wikitext.py#L108

Should we override this order?

**Comment by lhoestq** [comment]
@albertvillanova did a PR to fix the order recently. The order should be fixed when we update to the next release of `datasets`

**Comment by lhoestq** [comment]
Oh actually his PR only affects datasets without scripts. So yea maybe we can override, or simply open a PR on wikitext
