### ISSUE TITLE
Too large row group size for parquet exports of image datasets

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1127]
See https://huggingface.co/datasets/sasha/dog-food/blob/refs%2Fconvert%2Fparquet/sasha--dog-food/parquet-train.parquet which still has a row group size of 1K even though it's supposed to be 100 after #833

**Comment by severo** [comment]
I force refreshed sasha/dog-food, but the parquet files have not been updated: https://huggingface.co/datasets/sasha/dog-food/tree/refs%2Fconvert%2Fparquet/sasha--dog-food

**Comment by lhoestq** [comment]
it did an empty commit: https://huggingface.co/datasets/sasha/dog-food/commit/a81197249e873ae4c9341eb1b3751a05705b9142

**Comment by severo** [comment]
Ah ok, thanks, I was looking at the list of commits in https://huggingface.co/datasets/sasha/dog-food/tree/refs%2Fconvert%2Fparquet/sasha--dog-food (it showed only 2), while at the root (https://huggingface.co/datasets/sasha/dog-food/tree/refs%2Fconvert%2Fparquet), we see the empty ones

**Comment by lhoestq** [comment]
found the issue: the feature somehow disappeared from `main`- will re-make a PR
