### ISSUE TITLE
Dataset viewer issue: UnexpectedError on page 1 even if the parquet job succeeded

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1129]
see https://huggingface.co/datasets/xnli/viewer/all_languages/train?p=1

The admin page shows that there is an error `FileSystemError`:

type | dataset | config | split | http_status | error_code | job_runner_version | dataset_git_revision | progress | updated_at | details
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
split-first-rows-from-parquet | xnli | all_languages | train | 500 | FileSystemError | 2 | 1cdcf07be24d81f3d782038a5a0b9c8d62f76e60 |   | 2023-04-28T13:29:12.187000 | {"error": "Could not read the parquet files: 416 Client Error: Requested Range Not Satisfiable for url: https://s3.us-east-1.amazonaws.com/lfs.huggingface.co/datasets/xnli/...

**Comment by severo** [comment]
Fixed!
<img width="1609" alt="Capture d’écran 2023-06-02 à 18 05 56" src="https://github.com/huggingface/datasets-server/assets/1676121/7d43ad6d-4677-4af2-b181-0362d3a6f43e">
