### ISSUE TITLE
Unable to refresh certain jobs in the admin UI

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1130]
e.g. `config-parquet-and-info` on cnn_dailymail 1.0.0 returns

```
[cnn_dailymail] ❌ Failed to add processing step to the queue. Error 404: b'Not Found'
```

**Comment by severo** [comment]
This one is very funny and a shame: look at the force-refresh code:

https://github.com/huggingface/datasets-server/blob/2bf624a0d60a351c30248880378f30583758f08e/services/admin/src/admin/app.py#L120

This means that to refresh `/config-names`, you call `/force-refresh/config-names`.

But if you want to refresh `config-parquet-and-info`, you have to call `/force-refreshconfig-parquet-and-info`, without the `/`. Yes...

And the admin UI is adding a `/`:

https://github.com/huggingface/datasets-server/blob/2bf624a0d60a351c30248880378f30583758f08e/front/admin_ui/app.py#L249

**Comment by severo** [comment]
I was able to refresh the root step `/config-names` by putting `config-names` in the field, btw. It's a hack, but it should refresh all the dataset. Meanwhile, it can help.

<img width="869" alt="Capture d’écran 2023-05-03 à 13 45 57" src="https://user-images.githubusercontent.com/1676121/235907080-6c971a0a-5045-42ba-926e-75f34baf4669.png">

**Comment by severo** [comment]
Fix here: https://github.com/huggingface/datasets-server/pull/1131

**Comment by severo** [comment]
Fixed
<img width="1522" alt="Capture d’écran 2023-05-03 à 14 03 32" src="https://user-images.githubusercontent.com/1676121/235910571-56560444-112d-405a-b220-0195955d5906.png">
