### ISSUE TITLE
Dataset Viewer issue for databricks/databricks-dolly-15k

### ISSUE THREAD

**Issue by calam1** [huggingface/datasets-server#1138]
### Link

https://huggingface.co/datasets/databricks/databricks-dolly-15k

### Description

The dataset viewer is not working for dataset databricks/databricks-dolly-15k.

Error details:

```
Error code:   ResponseAlreadyComputedError

```

**Comment by srowen** [comment]
Oh, yeah I just reported this! https://github.com/huggingface/datasets-server/issues/1139
Might be related to something wider: https://github.com/huggingface/datasets-server/issues/1137

**Comment by calam1** [comment]
Closing this due to duplicate of [#1139](https://github.com/huggingface/datasets-server/issues/1139)
