### ISSUE TITLE
Dataset Viewer issue for databricks/databricks-dolly-15k

### ISSUE THREAD

**Issue by srowen** [huggingface/datasets-server#1139]
### Link

https://huggingface.co/datasets/databricks/databricks-dolly-15k

### Description

Hi all, I see that some other datasets may be having issues now, so this is probably related, but wanted to report the issues I started seeing today at `databricks/databricks-dolly-15k`.

After I committed a change to the dataset file, I see that the viewer no longer works. The update seemed normal, following the process suggested for creating a pull request and merging. It doesn't seem like it's a problem with the data, but I'm not clear:

'Response has already been computed and stored in cache kind: split-first-rows-from-streaming. Compute will be skipped."
```
Error code:   ResponseAlreadyComputedError
```

I also find that the dataset is not downloadable. It yields a 403 / Access Denied error via the `datasets` library or through the web UI. https://huggingface.co/datasets/databricks/databricks-dolly-15k/resolve/main/databricks-dolly-15k.jsonl

Thank you for any help you might be able to provide, or pointers if we did something wrong.

**Comment by matthayes** [comment]
I deleted the jsonl file and uploaded the previous version (copied from git history) using git.  The viewer now works and I'm able to download the dataset.  

The file was updated using a pull request.  Maybe this is what caused the issue?  Could there be a bug in the handling of git lfs files in pull requests?

**Comment by srowen** [comment]
It's fixed after Matt tried again separately.
I suspect strongly enough that this was related to my local git + lfs setup somehow that I'm going to close this.
