### ISSUE TITLE
Dataset Viewer issue for reddit

### ISSUE THREAD

**Issue by surya-narayanan** [huggingface/datasets-server#1151]
### Link

https://huggingface.co/datasets/reddit

### Description

The dataset viewer is not working for dataset reddit.

Error details:

```
Error code:   DatasetTooBigFromDatasetsError
Traceback:    The previous step failed, the error is copied to this step:  kind='config-parquet' dataset='reddit' config='default' split=None---The previous step failed, the error is copied to this step:  kind='config-parquet-and-info' dataset='reddit' config='default' split=None---
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @surya-narayanan.

Now the current error is different: `IndexError`:
```
IndexError: list index out of range
```

Note this is an error we get sometimes when data files are hosted on Zenodo, caused by a 429 HTTP error (Too many requests). We are working to give a more informative error message.

**Comment by albertvillanova** [comment]
The corresponding issue in the Community tab of the dataset: https://huggingface.co/datasets/reddit/discussions/5

**Comment by albertvillanova** [comment]
Fixed by https://huggingface.co/datasets/reddit/discussions/7
