### ISSUE TITLE
Dataset Viewer issue for cbt and "raw" configuration: Cannot GET

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#1171]
### Link

https://huggingface.co/datasets/cbt

### Description

There is an issue with the URL to show a specific split for the "raw" configuration:
```
Cannot GET /datasets/cbt/viewer/raw/train
``` 
- See: https://huggingface.co/datasets/cbt/viewer/raw/train

However, it works when no split name is provided in the URL.
- See: https://huggingface.co/datasets/cbt/viewer/raw

Maybe the word "raw" has a special meaning in the URL and cannot be used as configuration name (as it is the case in GitHub)?

CC: @severo

**Comment by severo** [comment]
wow, it's weird. Thanks for reporting.

**Comment by severo** [comment]
Yes, `raw` is special, it's used in the URLs that show the raw content of a file in a repo, eg https://huggingface.co/datasets/cbt/raw/main/README.md

Could you open the issue in https://github.com/huggingface/moon-landing (internal)?

**Comment by albertvillanova** [comment]
In GitHub, the "raw" keyword is used to get a document as raw, no HTML/CSS rendered.

**Comment by severo** [comment]
yes, it's the same here

**Comment by severo** [comment]
partly fixed on the Hub, but still not completely
