### ISSUE TITLE
Add a field, and rename another one, in /opt-in-out-urls

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1174]
The current response for /opt-in-out-urls is:

```
{
  "urls_columns": ["url"],
  "has_urls_columns": true,
  "num_opt_in_urls": 0,
  "num_opt_out_urls": 4052,
  "num_scanned_rows": 12452281,
  "num_urls": 12452281
}
```

I think we should:
- rename `num_urls` into `num_scanned_urls`
- add `num_rows` with the total number of rows in the dataset/config/split. It would help understand which proportion of the dataset has been scanned. Note that the information is already available in `/size`, but I think it would be handy to have this information here. wdyt?

**Comment by severo** [comment]
Hmmm: we don't necessarily have the information in /size, for example:

https://datasets-server.huggingface.co/size?dataset=c4 or https://datasets-server.huggingface.co/size?dataset=mc4 have no information about the number of rows! It's because they are too big to have a parquet conversion. So: we don't know!

**Comment by lhoestq** [comment]
Maybe we can add a boolean `partial_scan` ?
