### ISSUE TITLE
Dataset Viewer issue for lliillyy/controlnet_ap10k_val

### ISSUE THREAD

**Issue by Lliillyy** [huggingface/datasets-server#1178]
### Link

https://huggingface.co/datasets/lliillyy/controlnet_ap10k_val

### Description

The dataset viewer is not working for dataset lliillyy/controlnet_ap10k_val.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @Lliillyy.

The `ResponseNotReady` error means the our server is busier than normal and you have to wait some time until the viewer processes your dataset.

Today I have checked your dataset and found out that you have disabled the viewer. If the viewer is disabled, we cannot investigate of there are issues with it. I'm closing this issue.

Feel free to reopen it if you enable the viewer and a problem persists.
