### ISSUE TITLE
Dataset Viewer issue for Abrumu/Fashion_controlnet_dataset_V2

### ISSUE THREAD

**Issue by abdelrahmanabdelghany** [huggingface/datasets-server#1179]
### Link

https://huggingface.co/datasets/Abrumu/Fashion_controlnet_dataset_V2

### Description

The dataset viewer is not working for dataset Abrumu/Fashion_controlnet_dataset_V2.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @abdelrahmanabdelghany. 

The `ResponseNotReady` error means the our server is busier than normal and you have to wait some time until the viewer processes your dataset.

Today it was showing a `JobManagerCrashedError`. We had an issue this weekend and we had to process many datasets on the Hub

I have forced the refresh of your viewer and now it works as expected:
![Screenshot from 2023-05-15 11-22-05](https://github.com/huggingface/datasets-server/assets/8515462/9a54d144-aa2d-4886-b967-47bc543909db)
