### ISSUE TITLE
Dataset Viewer issue for RengJEY/Fast_Food_classification

### ISSUE THREAD

**Issue by RENGJEY** [huggingface/datasets-server#1193]
### Link

https://huggingface.co/datasets/RengJEY/Fast_Food_classification

### Description

The dataset viewer is not working for dataset RengJEY/Fast_Food_classification.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @RENGJEY.

Your repository contains neither data files nor a Python loading script: only the `README.md` and `.gitattributes` file.
![Screenshot from 2023-05-18 07-24-15](https://github.com/huggingface/datasets-server/assets/8515462/5a2d1725-2c6e-49ae-8825-80bb5114c6f1)

Therefore the viewer has nothing to show.
