### ISSUE TITLE
Dataset Viewer issue for Fredithefish/GPTeacher-for-RedPajama-Chat

### ISSUE THREAD

**Issue by fredi-python** [huggingface/datasets-server#1194]
### Link

https://huggingface.co/datasets/Fredithefish/GPTeacher-for-RedPajama-Chat

### Description

The dataset viewer is not working for dataset Fredithefish/GPTeacher-for-RedPajama-Chat.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Thanks for reporting, it's fixed now.

<img width="921" alt="Capture d’écran 2023-05-19 à 10 35 12" src="https://github.com/huggingface/datasets-server/assets/1676121/c4b15ed9-1d31-49ce-9320-0146b547764b">
