### ISSUE TITLE
Dataset Viewer issue for under-tree/prepared-yagpt

### ISSUE THREAD

**Issue by RodionfromHSE** [huggingface/datasets-server#1195]
### Link

https://huggingface.co/datasets/under-tree/prepared-yagpt

### Description

The dataset viewer is not working for dataset under-tree/prepared-yagpt.

Error details:
Dataset was pushed in next way
```python
final_dataset.push_to_hub(checkpoint)
```
where final_dataset is DatasetDict object

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Thanks for reporting, it's fixed now.

<img width="1634" alt="Capture d’écran 2023-05-19 à 10 34 43" src="https://github.com/huggingface/datasets-server/assets/1676121/fa24e6e7-24f5-4c2c-b56a-795765552ec7">
