### ISSUE TITLE
Dataset Viewer issue for tarteel-ai/everyayah

### ISSUE THREAD

**Issue by manna1lix** [huggingface/datasets-server#1212]
### Link

https://huggingface.co/datasets/tarteel-ai/everyayah

### Description

The dataset viewer is not working for dataset tarteel-ai/everyayah.

Error details:

```
Error code:   JobRunnerCrashedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @manna1lix.

The data files are quite large (some of them have more 1.5 GB) and the job crashes when trying to load them into RAM memory.

If order to support loading your dataset in machines with lower RAM, I would suggest the author split their data files into smaller ones (around maximum 500 MB each), so that each of them can be loaded in memory.

I have created an issue in the Community tab of the dataset: https://huggingface.co/datasets/tarteel-ai/everyayah/discussions/1
Let's continue the discussion there!

**Comment by rudro12356** [comment]
Just adding my solution just in case someone runs into this issue again: I ran into issue trying to doownload the HISTAI histology images which are preety large. I went ahead with python script to use the Python API from the HF Hub, and was able to initiate the download. Below is my script:

`#!/usr/bin/env python3
"""
Robust downloader for the HISTAI hematologic WSI dataset.

Target output directory:
    Data - histai/HISTAI-hematologic

Usage:
    python download_histai_hematologic.py --token <HF_TOKEN>
"""

from __future__ import annotations

import argparse
import os
import random
import sys
import time
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Download histai/HISTAI-hematologic from Hugging Face with retries "
            "and resume support."
        )
    )
    parser.add_argument(
        "--repo-id",
        default="histai/HISTAI-hematologic",
        help="Hugging Face dataset repo id (default: histai/HISTAI-hematologic).",
    )
    parser.add_argument(
        "--target-dir",
        default=str(Path("Data - histai") / "HISTAI-hematologic"),
        help=(
            "Destination directory. Default is "
            "'Data - histai/HISTAI-hematologic' under current working directory."
        ),
    )
    parser.add_argument(
        "--token",
        default=os.getenv("HF_TOKEN"),
        help="Hugging Face token. If omitted, reads HF_TOKEN env var.",
    )
    parser.add_argument(
        "--max-workers",
        type=int,
        default=4,
        help="Parallel download workers (default: 4). Reduce if unstable network.",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=6,
        help="Retry attempts for transient failures (default: 6).",
    )
    parser.add_argument(
        "--include-pattern",
        action="append",
        default=[],
        help=(
            "Optional include pattern(s), e.g. --include-pattern '*.tiff'. "
            "Can be repeated."
        ),
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.max_workers < 1:
        raise ValueError("--max-workers must be >= 1.")
    if args.retries < 1:
        raise ValueError("--retries must be >= 1.")
    if not args.repo_id or "/" not in args.repo_id:
        raise ValueError("--repo-id must be in format 'owner/name'.")
    if not args.token:
        raise ValueError(
            "Missing Hugging Face token. Pass --token or set HF_TOKEN environment variable."
        )


def do_download(args: argparse.Namespace) -> None:
    try:
        from huggingface_hub import snapshot_download
    except ImportError as exc:
        raise RuntimeError(
            "Missing dependency 'huggingface_hub'. Install it with:\n"
            "  pip install --upgrade huggingface_hub[hf_transfer]"
        ) from exc

    target_dir = Path(args.target_dir).resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    print(f"[info] Repo: {args.repo_id}")
    print(f"[info] Target directory: {target_dir}")
    print(f"[info] Max workers: {args.max_workers}")
    print(f"[info] Retries: {args.retries}")
    if args.include_pattern:
        print(f"[info] Include patterns: {args.include_pattern}")

    # Speeds up large downloads when hf_transfer extra is available.
    os.environ.setdefault("HF_HUB_ENABLE_HF_TRANSFER", "1")

    for attempt in range(1, args.retries + 1):
        try:
            snapshot_download(
                repo_id=args.repo_id,
                repo_type="dataset",
                local_dir=str(target_dir),
                token=args.token,
                max_workers=args.max_workers,
                resume_download=True,
                local_dir_use_symlinks=False,
                allow_patterns=args.include_pattern or None,
            )
            print("[success] Download completed.")
            return
        except Exception as exc:  # noqa: BLE001
            wait_s = min(90, (2 ** attempt) + random.uniform(0.0, 1.5))
            print(f"[warn] Attempt {attempt}/{args.retries} failed: {exc}")
            if attempt >= args.retries:
                raise RuntimeError(
                    "Download failed after all retries. "
                    "If access is gated, ensure you accepted terms on the dataset page "
                    "and your token has required permissions."
                ) from exc
            print(f"[info] Retrying in {wait_s:.1f}s...")
            time.sleep(wait_s)


def main() -> int:
    args = parse_args()
    try:
        validate_args(args)
        do_download(args)
        return 0
    except Exception as exc:  # noqa: BLE001
        print(f"[error] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
`
