### ISSUE TITLE
Dataset Viewer issue for beskrovnykh/daniel-dataset-fragments

### ISSUE THREAD

**Issue by beskrovnykh** [huggingface/datasets-server#1228]
### Link

https://huggingface.co/datasets/beskrovnykh/daniel-dataset-fragments

### Description

The dataset viewer is not working for dataset beskrovnykh/daniel-dataset-fragments.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @beskrovnykh.

We are having issues with the datasets-server, which is busier than usual and the response is not ready yet.

We'll keep you informed once the issues are fixed.

**Comment by albertvillanova** [comment]
The viewer is fixed now:

![Screenshot from 2023-05-23 21-16-20](https://github.com/huggingface/datasets-server/assets/8515462/bfef168d-335d-4591-810d-f2e9a5b74622)
