### ISSUE TITLE
Dataset Viewer issue for shibing624/medical

### ISSUE THREAD

**Issue by shibing624** [huggingface/datasets-server#1229]
### Link

https://huggingface.co/datasets/shibing624/medical

### Description

The dataset viewer is not working for dataset shibing624/medical.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @shibing624.

We are having issues with the datasets-server, which is busier than usual and the response is not ready yet.

We'll keep you informed once the issues are fixed.

**Comment by shibing624** [comment]
waiting for you ...

**Comment by albertvillanova** [comment]
The viewer is fixed now:

![Screenshot from 2023-05-23 18-50-10](https://github.com/huggingface/datasets-server/assets/8515462/5d19fce5-2ede-4a4e-8e5d-5dbea376bccd)
