### ISSUE TITLE
Fix audio data in pagination of audio datasets

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1255]
Currently pagination is only enabled for testing purposes on [arabic_speech_corpus](https://huggingface.co/datasets/arabic_speech_corpus) but times out because the "transform to list" step that writes the audio files to disk takes too much time.

Currently it writes both MP3 and WAV - but we should find which one is faster and only write this one.

This is not super high prio for now though, since there aren't a lot of audio dataset with pagination

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
keep open

**Comment by lhoestq** [comment]
So it's technically fixed but not enabled for all the datasets yet because most of them need to be converted to parquet (job failed because of OOM). Will re-run them once #1759 is deployed

**Comment by severo** [comment]
> Will re-run them once https://github.com/huggingface/datasets-server/pull/1759 is deployed

Done

**Comment by lhoestq** [comment]
Awesome ! Though after more digging I found that while the endpoint does work now, it's still too slow: 10sec to convert the audio data. We'll have to find a more clever way. For example I can simply not convert anything (if it's wav, keep it as wav - if it's mp3, keep it as mp3)

**Comment by severo** [comment]
Done.
