### ISSUE TITLE
Dataset Viewer issue for Muennighoff/xP3x

### ISSUE THREAD

**Issue by Muennighoff** [huggingface/datasets-server#1262]
### Link

https://huggingface.co/datasets/Muennighoff/xP3x

### Description

The dataset viewer is not working for dataset Muennighoff/xP3x.

Error details:

```
The dataset is currently empty. Upload or create new data files. Then, you will be able to explore them in the Dataset Viewer.
```

This dataset can be loaded & works just fine, however, the hub displays: The dataset is currently empty. [Upload or create new data files](https://huggingface.co/datasets/Muennighoff/xP3x/tree/main). Then, you will be able to explore them in the Dataset Viewer.

Not sure if this is a datasets or hub bug

**Comment by albertvillanova** [comment]
Now the error message is:
```
Job manager was killed while running this job (job exceeded maximum duration).

Error code:   JobManagerExceededMaximumDurationError
```

Looking at the code of your loading script, I have noticed that for each config (you have 277 configs) you are downloading the entire data files: you download the entire data files 277 times. I guess this is the reason why your loading script exceeds the maximum duration limit on the viewer server.

Also, the `id_` is not properly generated: you will get duplicate values for each of the files in `filepath`.

As this is not strictly speaking an issue of the dataset viewer, but an issue with the loading script, I am opening a discussion in the Community tab of your dataset: https://huggingface.co/datasets/Muennighoff/xP3x/discussions/1
Let's continue the discussion there.
