### ISSUE TITLE
Dataset Viewer issue for dineshpatil341341/demo

### ISSUE THREAD

**Issue by kishorgujjar** [huggingface/datasets-server#1265]
### Link

https://huggingface.co/datasets/dineshpatil341341/demo

### Description

The dataset viewer is not working for dataset dineshpatil341341/demo.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
The dataset is currently empty. [Upload or create new data files](https://huggingface.co/datasets/dineshpatil341341/demo/tree/main). Then, you will be able to explore them in the Dataset Viewer.

![Screenshot from 2023-05-31 07-34-51](https://github.com/huggingface/datasets-server/assets/8515462/8bf6abcb-2806-42e5-9d51-503672c73b21)
