### ISSUE TITLE
Send a notification to the dataset owner on parquet files creation

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1270]
Once the parquet files have been created, we could send a notification to the dataset maintainer, to let them know, with the goal to increase the usage of these files.

Note: an idea by @julien-c when we started working on parquet conversion was to do it through the PR mechanism. It would have helped in that aspect, since the dataset maintainers would have received the notification as with any other PR.

**Comment by julien-c** [comment]
yes we discussed this point with @gary149 yesterday, let's use a Discussion (on each repo) to achieve this

**Comment by severo** [comment]
keep open

**Comment by geethika-123** [comment]
Hi @severo - I can work on this feature. Can you let me know where in the workflow the parquet file gets created? I tried searching on GitHub but couldn't find it.

**Comment by severo** [comment]
Sure. They are created here: https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/config/parquet_and_info.py.

**Comment by severo** [comment]
What should the discussion contain?
1. only one message if the dataset has been converted to parquet once.
2. one message after each conversion.

---

I see three places where to implement it:
1. in the job_runner (run by a worker) that converts the dataset to parquet
2. in a watcher on MongoDB events, like done in SSE, that sends an event if the `config-parquet` has changed
3. in a daily cron job that sends messages for `config-parquet` entries updated in the last 24h

Important: the jobs are config-level, not dataset-level. But the discussions are per dataset. We should not send one discussion message for each configuration conversion to avoid too much spam.

I favor option 3 (daily cron job), where we send at most 1 message per day and dataset. The idea is to increase awareness, not to give instant feedback.

---

What do you think about these two questions @julien-c @gary149?

**Comment by julien-c** [comment]
yes option 3 sounds fine to me and we can also  maybe iniitally limit to `1 message per day and per entity (user or org)`

**Comment by severo** [comment]
I will implement it this way.

We run a daily job that lists the datasets converted [1] to Parquet in the last 24 hours.

We loop on the updated cache entries sorted by time (oldest first) and keep the first entry for each namespace (user/org - let's ignore canonical datasets).

We try to find a previous discussion created by the same bot (datasets-server-bot) in the dataset. If we find one, we append a new comment to the discussion. Else, we create a new discussion (if so: the message will contain more details, to introduce the "bot notifications").

The first message will be something like:

> # Datasets Server Bot notifications
> 
> [Datasets](https://huggingface.co/docs/datasets/) can be published in any format (CSV, JSONL, directories of images, etc.) to the Hub, and they are easily accessed with the 🤗 Datasets library. For a more performant experience (especially when it comes to large datasets), Datasets Server has automatically converted this dataset to the [Parquet](https://parquet.apache.org/) format.
> 
> The Parquet files are published to the Hub on a specific [`ref/convert/parquet`](https://huggingface.co/datasets/amazon_polarity/tree/refs%2Fconvert%2Fparquet) branch.
>
> You can find more details about the Parquet conversion in the [documentation](https://huggingface.co/docs/datasets-server/parquet).
>
> _The Datasets Server bot will provide updates in the comments. Close the discussion if you want to stop receiving notifications._

^ not sure about the last sentence, as it means more logic to implement. And should it apply only to the dataset, or to the namespace?

If the discussion already exists, the message will be something like:

> Datasets Server has automatically converted this dataset to the [Parquet](https://parquet.apache.org/) format.
>
> The Parquet files are published to the Hub on a specific [`ref/convert/parquet`](https://huggingface.co/datasets/amazon_polarity/tree/refs%2Fconvert%2Fparquet) branch.
>
> You can find more details about the Parquet conversion in the [documentation](https://huggingface.co/docs/datasets-server/parquet).

[1] at least one config converted to parquet

**Comment by severo** [comment]
See https://github.com/huggingface/datasets-server/pull/1824
