### ISSUE TITLE
Change the name of the committer on the Hub

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1271]
Currently, the parquet files are committed by https://huggingface.co/francky (see https://huggingface.co/datasets/glue/commits/refs%2Fconvert%2Fparquet).

Create a dedicated user like `parquet-converter` or `converter` or `datasets-server`, or...

Alternative: use an app token to do the commits. I understand that we should soon have the feature, right @SBrandeis?

**Comment by julien-c** [comment]
> Alternative

this is orthogonal, no? (You'll still need your commits linked to a specific user)

**Comment by julien-c** [comment]
as discussed let's just try renaming the existing user to `parquet-converter` and hope it works out of the box:)

**Comment by severo** [comment]
By the way, as we only rely on the token, no change is required here in the datasets server itself. I'll keep open only to track the user renaming.

**Comment by severo** [comment]
> > Alternative: use an app token to do the commits. I understand that we should soon have the feature, right @SBrandeis?
> this is orthogonal, no? (You'll still need your commits linked to a specific user)

See https://github.com/huggingface/datasets-server/issues/1283
