### ISSUE TITLE
Use original parquet files if present, instead of re-generating

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1273]
When a dataset is already in parquet format, we should try to use them in `config-parquet-and-dataset-info` instead of creating brand new files.
It would help fostering the use of parquet by default. It would provide an instant dataset viewer.

Notes:
- it should be "free" because the original parquet files are already stored with LFS, so it's just a matter of creating a new pointer to them
- we should take care of the size: maybe re-convert if the parquet files are too big or too small, in order to ensure our services (/rows, stats, search) will work as expected
- in the same vein: we should check if the row group size is coherent with the type of data. In the dataset viewer, we use a smaller row group size for images or audio, to help /rows be reactive enough.
- maybe the same parquet file is used for multiple configs, or splits, through the dataset script. What to do in that case? Maybe we should apply the "shortcut" only when the dataset has no script

**Comment by lhoestq** [comment]
> it should be "free" because the original parquet files are already stored with LFS, so it's just a matter of creating a new pointer to them

yup, we can use the hffs `cp_file` method:

https://github.com/huggingface/huggingface_hub/blob/b347dfd200bf9a56d1e4edd050783178bddec186/src/huggingface_hub/hf_file_system.py#L303

> we should take care of the size: maybe re-convert if the parquet files are too big or too small, in order to ensure our services (/rows, stats, search) will work as expected

I think we should be fine no matter the file size

> in the same vein: we should check if the row group size is coherent with the type of data. In the dataset viewer, we use a smaller row group size for images or audio, to help /rows be reactive enough.

Yup +1. The case is pretty rare but does exist, e.g. in [philippemo/test-final](https://huggingface.co/datasets/philippemo/test-final)
