### ISSUE TITLE
Dataset Viewer issue for ms_marco

### ISSUE THREAD

**Issue by jxmorris12** [huggingface/datasets-server#1277]
### Link

https://huggingface.co/datasets/ms_marco

### Description

The dataset viewer is not working for dataset ms_marco.

Error details:

```
Error code:   JobRunnerCrashedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @jxmorris12.

The viewer is working now:

![Screenshot from 2023-06-01 06-45-56](https://github.com/huggingface/datasets-server/assets/8515462/01f7ac7a-310c-4cd0-a10a-ef9f00271866)
