### ISSUE TITLE
Remove dependency on torch and torchaudio

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#1281]
As suggested by @severo:
> should we remove the dependency to torch and torchaudio? cc @polinaeterna

- [ ] #1282
- [ ] Remove torch

**Comment by albertvillanova** [comment]
I have already removed the dependency on `torchaudio`, once all the Audio feature functionalities are backed by `soundfile`.

In relation with `torch`, are we sure we want to stop supporting dataset loading scripts that use `torch`. If so, what about the ones using `tensorflow`?

Maybe @lhoestq can give better insight.

**Comment by severo** [comment]
I was asking because, if I remember correctly, we didn't depend on torch (because we had no dataset depending on torch) before working with audio cells.

But I wouldn't want to rely on my poor memory. At one point it would be good to store statistics about the dependencies found in the scripts to be able to take decisions. Not prioritary.

**Comment by albertvillanova** [comment]
I agree with you that we should track that information.

Honestly, I don't know how many loading scripts on Hub dataset depend on `torch` (or `tensorflow`)...

**Comment by lhoestq** [comment]
we might want to keep torchaudio after all, e.g. for https://huggingface.co/datasets/cdminix/libritts-aligned/blob/main/libritts-aligned.py

**Comment by severo** [comment]
should we revert https://github.com/huggingface/datasets-server/pull/1282?

**Comment by albertvillanova** [comment]
I think the relevant question is how many loading scripts use `torchaudio`. I don't think we should support all packages for all scripts, but we should do sensible choices based on impact.

Also please note that even if reverting @1282, the viewer will not work for https://huggingface.co/datasets/cdminix/libritts-aligned
- It has also 2 other third-party dependencies which are not installed on the datasets-server:
```
Error code:   DatasetModuleNotInstalledError
Exception:    ImportError
Message:      To be able to use cdminix/libritts-aligned, you need to install the following dependencies: alignments, phones.
```

**Comment by lhoestq** [comment]
Ah I see, maybe not worth it for now then

**Comment by albertvillanova** [comment]
There are still 2 questions to be answered: https://github.com/huggingface/datasets-server/issues/1281#issuecomment-1571875857
> In relation with `torch`, are we sure we want to stop supporting dataset loading scripts that use `torch`?

> If so, what about the ones using `tensorflow`?

**Comment by severo** [comment]
OK. Let's keep the current situation and do statistics about `DatasetModuleNotInstalledError` regularly.

For example, for now:

```
> db.cachedResponsesBlue.aggregate([
  { $match: {error_code: "DatasetModuleNotInstalledError", "details.copied_from_artifact": {"$exists": false} } },
  { $set: { match: { $regexFind: { input: "$details.cause_message", regex: /[\'`]pip install (.+)[\'`]/ } } } },
  { $set: { library: { $arrayElemAt: ['$match.captures', 0] } } },
  { $group: { _id: "$library", count: { $sum: 1 } } },
  { $sort: { count: -1 } }
])
{ _id: 'ir-datasets', count: 434 }
{ _id: 'bioc', count: 11 }
{ _id: 'pytorch_ie', count: 11 }
{ _id: null, count: 10 }
{ _id: 'Bio', count: 6 }
{ _id: 'mwparserfromhell', count: 6 }
{ _id: 'more_itertools', count: 6 }
{ _id: 'pickle5', count: 4 }
{ _id: 'ir_datasets', count: 3 }
{ _id: 'torchaudio', count: 3 }
{ _id: 'xarray', count: 3 }
{ _id: 'spacy', count: 2 }
{ _id: 'apache_beam', count: 2 }
{ _id: 'alignments phones torchaudio', count: 2 }
{ _id: 'ffmpeg', count: 2 }
{ _id: 'boto3 botocore', count: 2 }
{ _id: 'cv2', count: 2 }
{ _id: 'evaluate', count: 1 }
{ _id: 'snowflake', count: 1 }
{ _id: 'stempeg', count: 1 }
{ _id: 'textgrids', count: 1 }
{ _id: 'pyconll', count: 1 }
{ _id: 'faiss sentence_transformers', count: 1 }
{ _id: 'ndjson', count: 1 }
{ _id: 'webdataset', count: 1 }
{ _id: 'detectron2', count: 1 }
{ _id: 'syntok', count: 1 }
{ _id: 'ijson', count: 1 }
{ _id: 'shapely', count: 1 }
{ _id: 'wikidata', count: 1 }
{ _id: 'torch, onnxruntime', count: 1 }
{ _id: 'nibabel boto3', count: 1 }
{ _id: 'sympy', count: 1 }
{ _id: '"bigbench @ https://storage.googleapis.com/public_research_data/bigbench/bigbench-0.0.1.tar.gz" # noqa: this is also required by bigbench.api.util',
  count: 1 }
{ _id: 'pycocotools', count: 1 }
{ _id: 'lance', count: 1 }
{ _id: 'datasets,', count: 1 }
{ _id: 'function_parser git tree_sitter', count: 1 }
{ _id: 'ijson more_itertools', count: 1 }
{ _id: 'dataset', count: 1 }
{ _id: 'imgaug imageio', count: 1 }
{ _id: 'warcio selectolax', count: 1 }
{ _id: 's3fs xarray', count: 1 }
{ _id: 'xarray zarr gcsfs', count: 1 }
{ _id: 'sacrebleu', count: 1 }
{ _id: 'synapseclient', count: 1 }
{ _id: 'xarray s3fs', count: 1 }
{ _id: 'opustools', count: 1 }
{ _id: 'xarray netCDF4', count: 1 }
{ _id: 'wfdb', count: 1 }
{ _id: 'cassis', count: 1 }
{ _id: '#BToken is ERC20', count: 1 }
```

The most important ones to add could be [ir-datasets](https://pypi.org/project/ir-datasets/), [bioc](https://pypi.org/project/bioc/) and [pytorch_ie](https://pypi.org/project/pytorch-ie/).

**Comment by severo** [comment]
Who wants to try to add the most required dependencies ([ir-datasets](https://pypi.org/project/ir-datasets/), [bioc](https://pypi.org/project/bioc/) and [pytorch_ie](https://pypi.org/project/pytorch-ie/))?

**Comment by albertvillanova** [comment]
On the other hand, I am curious how people use `ir-datasets` and integrate it with `datasets`... :thinking:

**Comment by severo** [comment]
I'm opening a dedicate issue for the new dependencies, and closing this issue.

**Comment by severo** [comment]
I created https://github.com/huggingface/datasets-server/issues/1442, and assigned it to you @albertvillanova. Thanks!

> On the other hand, I am curious how people use ir-datasets and integrate it with datasets... 🤔

Please share with us what you find
