### ISSUE TITLE
Create a cronjob to delete dangling cache entries

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1285]
from the cache database

related to https://github.com/huggingface/datasets-server/issues/1284

**Comment by severo** [comment]
keep open

**Comment by AndreaFrancis** [comment]
See https://github.com/huggingface/datasets-server/issues/1550#issuecomment-1707471830
There were some datasets that could not be backfilled because they didn't exist on the hub. We should remove those as well as their related assets.

**Comment by AndreaFrancis** [comment]
Firs part was implemented here: https://github.com/huggingface/datasets-server/pull/1822 for datasets that no longer exist in the hub.
After calling DELETE /admin/obsolete-cache, 3920 datasets were deleted with 86780 cache records.
See the detailed list in the response 
[obsolete_cache.csv](https://github.com/huggingface/datasets-server/files/12702277/obsolete_cache.csv)

**Comment by severo** [comment]
The backfill cron job now loops on the cache entries, so: it will delete all the obsolete cache entries. Done
