### ISSUE TITLE
Dataset Viewer issue for Venkatesh4342/augmented_ner

### ISSUE THREAD

**Issue by Venkatesh3132003** [huggingface/datasets-server#1290]
### Link

https://huggingface.co/datasets/Venkatesh4342/augmented_ner

### Description

The dataset viewer is not working for dataset Venkatesh4342/augmented_ner.

Error details:

```
Error code:   ResponseNotReady

```
couldn't upload a dataset in json format

**Comment by albertvillanova** [comment]
The dataset does not exist: 404 error

**Comment by Venkatesh3132003** [comment]
Even current version of transformer library is taking more time to fine tune and if we degrade the vesion training time decreases from 26 hours to 1.5 hours

**Comment by albertvillanova** [comment]
I think that is an issue with `transformers`. You could open an issue in their repo: https://github.com/huggingface/transformers/issues/new/choose
