### ISSUE TITLE
Upgrade huggingface_hub to 0.15.1

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1291]
https://github.com/huggingface/huggingface_hub/releases/tag/v0.15.0

- use `run_as_future=True` in parquet upload?
- `list_datasets` breaking change should not affect us

**Comment by albertvillanova** [comment]
Correct link: https://github.com/huggingface/huggingface_hub/releases/tag/v0.15.1

**Comment by severo** [comment]
0.15.0 disappeared from https://github.com/huggingface/huggingface_hub/releases 😮
