### ISSUE TITLE
In /valid, associate an enum to every dataset

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1295]
Instead of a list of datasets:

```json
{
  "valid": [
    "0-hero/OIG-small-chip2",
    "000alen/semantic",
    "04-07-22/wep-probes",
    "0721boy/nva-pic",
    ...
  ]
}
```

we could return an object, where the datasets are the keys, and the values are lists of available features: `"preview" | "parquet" | "parquet-sample"`

```json
{
  "0-hero/OIG-small-chip2": ["preview"],
  "000alen/semantic": ["preview", "parquet"],
  "04-07-22/wep-probes": ["preview", "parquet-sample"],
  "0721boy/nva-pic": [], 
  ...
}
```

The list of features for each dataset helps the Hub show the appropriate text/icons/UI.

Note that we might want to change the name of the endpoint to avoid breaking change, and to be more descriptive: `/features-by-dataset` (I don't like it, because `features` has another meaning in datasets).

Also: the response could take too long to be computed online as it's currently done (it already takes about 300ms to compute), so we should precompute it regularly with a cronjob and cache the result. See #891

**Comment by julien-c** [comment]
> to avoid breaking change
are you sure anyone extrernal is using that endpoint (or the API for that matter :) )

**Comment by julien-c** [comment]
`"04-07-22/wep-probes": ["preview", "parquet-sample"],`

on the Hub side at least, we won't really care about the "lower-level" attribute, just the "best" one

**Comment by severo** [comment]
if we don't need multiple values for one dataset, we could use the following format instead (similar to the current one):

```json
{
  "preview": [list of datasets with highest level == preview],
  "parquet-sample": [list of datasets with highest level == parquet-sample, ie. parquets for the first 5G],
  "parquet": [list of datasets with full conversion to parquet]
}
```

**Comment by severo** [comment]
Done in #1353
