### ISSUE TITLE
Get random access to the rows

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#13]
Currently, only the first rows can be obtained with /rows. We want to get access to slices of the rows through pagination, eg /rows?from=40000&rows=10

**Comment by severo** [comment]
Design thoughts (thanks to discussion with @lhoestq):
- the endpoint will be GET `/rows`, with required parameters `dataset`, `config`, `split` and optional parameters to control the number of results, eg: `from` and `limit`?
- the API service will request the parquet files (if they exist), and return the formatted JSON. Beware: it might take some time, in particular if the rows are very big (every row can contain several MB of JSON) so we should not impose a timeout on the response.
- to be discussed: what to do with the audio files and images? They are stored as a struct with fields: `bytes` (the raw bytes) and `path` (the filename). We could return a temporary URL in the /rows JSON, and then generate a temporary static file if the URL is called from the client (again: without a timeout, because generating the temporary file can take some time).

**Comment by mariosasko** [comment]
> the API service will request the parquet files (if they exist), and return the formatted JSON. Beware: it might take some time, in particular if the rows are very big (every row can contain several MB of JSON) so we should not impose a timeout on the response.

Maybe we could eventually switch to Apache Flight to make this performant. 

A nice article that compares Apache Flight and the standard approach based on returning a binary format over HTTP: https://voltrondata.com/resources/data-transfer-at-the-speed-of-flight

**Comment by severo** [comment]
We could provide two response formats for the /rows endpoint, depending on what the client wants:
- JSON
- Arrow Flight

We could use the [Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) header, or a query parameter, to select the format of the response.

**Comment by severo** [comment]
Another option would be to create an Arrow Flight server that can be accessed on a dedicated endpoint (it's RPC, not REST API); and the /rows endpoint would use that RPC endpoint to serve a JSON serialized response.

**Comment by severo** [comment]
Done
