### ISSUE TITLE
The number of started jobs is a lot bigger than the number of workers

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1323]
We currently have nearly 2000 started jobs, and "only" 200 workers

<img width="389" alt="Capture d’écran 2023-06-07 à 18 27 10" src="https://github.com/huggingface/datasets-server/assets/1676121/df48b775-b423-4d99-af59-7117355685c8">

My guess: the jobs raise an uncaught exception and are never finished properly in the database. They will be deleted afterwards anyway (zombie killer) but possibly we must fix something here.

**Comment by severo** [comment]
Note that the three affected steps are `dataset-opt-in-out-urls-count`, `config-opt-in-out-urls-count`, `split-opt-in-out-urls-count`, which at least seems coherent in some way.

maybe @AndreaFrancis you want to check this?

**Comment by AndreaFrancis** [comment]
Sure, I will check

**Comment by AndreaFrancis** [comment]
Interestingly, there are jobs with "started" status but have a  "finished_at" value and a cache record in the DB. I think only the status is not being set correctly, will put here my findings.

**Comment by AndreaFrancis** [comment]
I found some other records in the queue for other steps (Different than dataset-opt-in-out-urls-count, config-opt-in-out-urls-count, split-opt-in-out-urls-count) using filter` {status:"started", finished_at:{$exists:true}`}. But I was not able to reproduce the issue.
I think setting the TTL index to drop only for those status success/error would help us identify the problem.

**Comment by severo** [comment]
Hmmm. No need to investigate too much. If we don't find the root reason quickly, we can let it unchanged: anyway, the cron backfill will fix the remaining issues once a day

**Comment by AndreaFrancis** [comment]
> Hmmm. No need to investigate too much. If we don't find the root reason quickly, we can let it unchanged: anyway, the cron backfill will fix the remaining issues once a day

Sure, anyway I think we should not delete the inconsistent records, those are not being finished by zombie killer, and looks like queue's finish method is not letting us know if there is a wrong combination of state+dates https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/queue.py#LL632C15-L632C15 it returns a boolean but nowhere is being evaluated.
I opened https://github.com/huggingface/datasets-server/pull/1325, and would like to understand what is happening and if there is a pattern for this behavior.

**Comment by severo** [comment]
Note that since we change the TTL index, we now have "waiting" jobs with a non-null finished_at field, which shows up in the metrics. Maybe we should change the way we compute the metrics, if this issue is not solved soon

<img width="388" alt="Capture d’écran 2023-06-21 à 17 40 17" src="https://github.com/huggingface/datasets-server/assets/1676121/197ff946-dc70-4a77-9568-7b78669e5b0e">
