### ISSUE TITLE
Locking mechanism

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1356]
Certain jobs like config-parquet-and-info write to a repository and may have concurrency issues (see e.g. https://github.com/huggingface/datasets-server/issues/1349)

For config-parquet-and-info we need to lock the job at the dataset level, so that no other job of the same type for the same dataset write at the same time.

This can be implemented using mongodb

**Comment by severo** [comment]
> lock the job at the dataset level

indeed, because all the configs share the same git branch, and we don't want to interleave commits.
