### ISSUE TITLE
Avoid running jobs twice when step depends on "parallel" jobs

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#1358]
Any time a step depends on two "parallel" steps, the job runs twice, even if the previous one is already computed.
See https://github.com/huggingface/datasets-server/pull/1296#discussion_r1227676712 for context.
Our parallel jobs are:
- "config-split-names-from-streaming"/"config-split-names-from-info" -> dataset-split-names, config-opt-in-out-urls-count and potentially split-duckdb-index" from https://github.com/huggingface/datasets-server/pull/1296
- "split-first-rows-from-parquet" / "split-first-rows-from-streaming" -> split-image-url-columns, dataset-is-valid
We should somehow avoid running the job twice if the result has already been computed for a given revision and job runner version is the same as the current.

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
No more parallel steps in the code
