### ISSUE TITLE
Refactor: use "Document" suffix for classes that inherit from mongoengine's Document

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1359]
ie.

- `Job` -> `JobDocument`
- `CachedResponse` -> `CachedResponseDocument`
- `JobTotalMetric` -> `JobTotalMetricDocument`
- `CacheTotalMetric` -> `CacheTotalMetricDocument`

The idea is to clarify that the class allows manipulating the DB directly and to let the non-suffixed names be free for use as a more high-level class.

It's a nit - easy and useful, but not urgent

**Comment by geethika-123** [comment]
Hey @severo - I want to take this up. Can I self-assign?

**Comment by severo** [comment]
Sure! Done
