### ISSUE TITLE
Increase PIL limit for images size

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1361]
See https://huggingface.co/datasets/datadrivenscience/ship-detection/discussions/4#6489674ff4d5239fac762f2a

PIL has a limit for the image size (178,956,970 pixels). When the datasets library tries to get the value for the big image, it raises `DecompressionBombError`

https://github.com/huggingface/datasets-server/blob/7b4b78f04473d8f00e7c2226381982a9a84ab48c/services/worker/src/worker/utils.py#L341

<strike>I'm not sure if we could handle this better (ie: ignoring the error just for these images, replacing with a placeholder?)</strike> 
- [ ] increase the limit
- [ ] catch the exception and return a proper advice for the user

wdyt @huggingface/datasets?

**Comment by lhoestq** [comment]
I think we can just increase the limit. The idea is just not to OOM

**Comment by severo** [comment]
Duplicate of #1192 (but we will keep this one)

**Comment by severo** [comment]
Copying references found by @albertvillanova 

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open

> If the number of pixels is greater than twice MAX_IMAGE_PIXELS, then a DecompressionBombError will be raised instead.

> This threshold can be changed by setting MAX_IMAGE_PIXELS. It can be disabled by setting Image.MAX_IMAGE_PIXELS = None.

> The default value for MAX_IMAGE_PIXELS is 0.25GB, which allows opening images up to 0.5GB (twice the value)
