### ISSUE TITLE
Dataset viewer issue for bigscience/P3

### ISSUE THREAD

**Issue by VoiceBeer** [huggingface/datasets-server#1365]
Same to #960 
<img width="1024" alt="image" src="https://github.com/huggingface/datasets-server/assets/18626699/12590e16-db21-443d-8ddc-ec6f9bf0ac41">

**Comment by severo** [comment]
move to the discussion here: https://huggingface.co/datasets/bigscience/P3/discussions/6#64d651a0c8d03cca8f9a2546
