### ISSUE TITLE
Update datasets to 2.13.0

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1370]
https://github.com/huggingface/datasets/releases/tag/2.13.0

Related to the datasets server:
- Better row group size in push_to_hub by @lhoestq in https://github.com/huggingface/datasets/pull/5935
- Make get_from_cache use custom temp filename that is locked by @albertvillanova in https://github.com/huggingface/datasets/pull/5938

Did I miss something @huggingface/datasets-server ?

**Comment by lhoestq** [comment]
it should also fix issues where images were shown as `{"bytes": ...}` thanks to https://github.com/huggingface/datasets/pull/5921
