### ISSUE TITLE
Uncaught error in /rows on big datasets

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1384]
For some datasets, for which the parquet files have been uploaded (or copied) with multiple commits (see https://github.com/huggingface/datasets-server/issues/1349) like `atom-in-the-universe/zlib-books-1k-50k`:

```
tiiuae/falcon-refinedweb
marianna13/zlib-books-1k-500k
atom-in-the-universe/zlib-books-1k-50k
atom-in-the-universe/zlib-books-1k-100k
atom-in-the-universe/zlib-books-1k-500k
atom-in-the-universe/zlib-books-1k-1000k
mlfoundations/datacomp_1b
```

the parquet files exist, all the steps are OK, but we get an uncaught error on /rows (in services/api):

https://datasets-server.huggingface.co/rows?dataset=atom-in-the-universe/zlib-books-1k-50k&config=atom-in-the-universe--zlib-books-1k-50k&split=train&offset=500&length=100

```
{"error":"Unexpected error."}
```

**Comment by AndreaFrancis** [comment]
Not sure, but maybe it is related to https://github.com/huggingface/datasets-server/issues/1341?
I will work on it anyway.

**Comment by lhoestq** [comment]
I think it's related to https://github.com/huggingface/huggingface_hub/issues/1515

**Comment by severo** [comment]
keep open
