### ISSUE TITLE
Use EFS instead of NFS for datasets and parquet "local" cache

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1407]
(and duckdb local cache in the PRs)

related to https://github.com/huggingface/datasets-server/issues/1072

internal: see https://github.com/huggingface/infra/issues/605#issue-1758616648

**Comment by AndreaFrancis** [comment]
Migrations to be done:
- [ ]     datasets-server-cache-pvc -> Done by https://github.com/huggingface/datasets-server/pull/1495
- [ ]     datasets-server-parquet-pvc
- [ ]     datasets-server-duckdb-pvc -> Done by https://github.com/huggingface/datasets-server/pull/1495
