### ISSUE TITLE
Add new dependencies for the job runners

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1442]
Based on statistics about the most needed dependencies (https://github.com/huggingface/datasets-server/issues/1281#issuecomment-1609455781), we should prioritize adding [ir-datasets](https://pypi.org/project/ir-datasets/), [bioc](https://pypi.org/project/bioc/) and [pytorch_ie](https://pypi.org/project/pytorch-ie/).

**Comment by severo** [comment]
Sure, please comment here while you investigate!

**Comment by albertvillanova** [comment]
The "ir-datasets" dependency comes from a single organization (the "ir-datasets" org) containing 443 datasets: https://huggingface.co/irds

Basically, they circumvent our `dl_manager.download_and_extract` inside `_split_generators` and instead they use `ir_datasets.load` inside `_generate_examples`.

See, e.g.: https://huggingface.co/datasets/irds/antique/blob/main/antique.py

**Comment by severo** [comment]
OK! thanks for investigating. So, if not asked by the users, we can let these two dependencies uninstalled. What about bioc?

**Comment by severo** [comment]
did they manage to have a working pip package? IIRC it was the issue

**Comment by severo** [comment]
closing since we don't support scripts anymore
