### ISSUE TITLE
Remove the useless mongodb indexes

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1444]
Review the current indexes in the mongodb collections, and ensure all of them are required. Else, remove the redundant ones. It will allow us to reduce the size on the server

**Comment by geethika-123** [comment]
Hey @severo. I want to take this up as this helps me to understand the code base a bit more. I'm new to mongodb collections. Can you please guide me on how to verify if an index is needed or not?

**Comment by severo** [comment]
> Can you please guide me on how to verify if an index is needed or not in this code base?

I think that the definition of indexes includes duplicates because some simple indexes are included in the more complex ones.

https://github.com/huggingface/datasets-server/blob/812df7632bd074bf1fd46ec2e25e35ee5e2492ca/libs/libcommon/src/libcommon/queue.py#L140-L159

> Do we have a test suite which exercises performance of MongoDB

No...

**Comment by geethika-123** [comment]
Hey @severo - Apologies for delay from my end as I was busy with a few personal things. I have gathered some info about
the compound indices of mongodb from [here](https://www.mongodb.com/docs/manual/core/index-compound/#std-label-index-ascending-and-descending)

As per the above document, the prefix and order of the indices are important, I have come across
a few redundant indices and would like to remove them. Here is the list of indices that I would like to remove.

```python
"indexes": [ 
     "dataset", 
     ("type", "status"), 
     ("priority", "status", "created_at", "namespace", "unicity_id"), 
     ("priority", "status", "created_at", "type", "namespace"), 
     ("priority", "status", "type", "created_at", "namespace", "unicity_id"), 
     ("status", "type"), 
     ("status", "namespace", "priority", "type", "created_at"), 
   ]
```
Please take a look and let me know if I am on right track.

**Comment by severo** [comment]
Indeed. You can look at https://github.com/huggingface/datasets-server/issues/1444 that does the job for the queue database.

**Comment by geethika-123** [comment]
Hey @severo , I have found few redundant indices in simple_cache.py .Here is the list of indices I would like to remove.

| Index | proposal | 
------|-----------------------------
| ("kind","dataset","config","split") | Keep | 
| ("dataset","kind","http_status") | Keep |
| ("kind","http_status","dataset") | Remove| 
| ("kind","http_status","error_code") | Keep |
| ("kind","id") | Remove

**Comment by severo** [comment]
Done
