### ISSUE TITLE
Remove `.valid` from `/valid` endpoint?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1445]
We recently added to fields to `/valid`:
- `viewer`: all the datasets that have a valid dataset viewer
- `preview`: all the datasets that don't have a valid dataset viewer, but have a dataset preview

And the Hub does not use the original field `valid` anymore. We still fill it with the union of both sets.

Should we remove it, as it doubles the size of the response and increases the response time, with no benefit? cc @huggingface/datasets-server 

Note that it's used in the notebooks (https://github.com/search?q=org%3Ahuggingface+datasets-server.huggingface.co+repo%3Ahuggingface%2Fnotebooks&type=code), for example, so it is a breaking change.

I would vote in favor of removing it, and updating the notebooks (and the docs obviously).

**Comment by lhoestq** [comment]
no strong opinion on my side, imo it won't have any impact on latency though

**Comment by severo** [comment]
Note that we don't have data about the API usage, and how much an issue would be a breaking change.

In particular, maybe some spaces are using the API. And external code (https://github.com/search?q=datasets-server.huggingface.co)?

**Comment by severo** [comment]
> no strong opinion on my side, imo it won't have any impact on latency though

I wanted to check in the internal monitoring charts (https://grafana.huggingface.tech/d/i7gwsO5Vz/global-view?from=now-90d&to=now&orgId=1&var-slo_quantile_99_5=0.995&var-slo_quantile_85=0.85&var-slo_period=12h&viewPanel=2), but we deployed the two new fields on 12 of June (https://huggingface.slack.com/archives/C04L6P8KNQ5/p1686587478810609 internal), but we don't have prometheus metrics before 19 of June anymore...

**Comment by severo** [comment]
OK. Maybe the first step is adding a deprecation notice on `valid` in the docs (and add doc contents for the two other fields). Then, one day maybe, break the compatibility.

**Comment by severo** [comment]
We removed it with #1452
