### ISSUE TITLE
Improve metrics to hide duplicates

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1458]
Yesterday, a new step (`split-duckcb-index`) was added and run over all the datasets. Here are the metrics:

<img width="771" alt="Capture d’écran 2023-06-29 à 09 46 31" src="https://github.com/huggingface/datasets-server/assets/1676121/5daf2798-c79b-4ff9-a192-03ba38d4b149">

We can see that many new cache entries have been filled and that many of them are errors. But looking into the details, we can see that most of them are copies of the error in a previous step.

It would be useful to show the errors related only to the new step.

**Comment by AndreaFrancis** [comment]
> But looking into the details, we can see that most of them are copies of the error in a previous step.

I would like to change the "UnexpectedError" for something indicating that there was an error in the ancestor like "PreviousStepStatusError" instead.

**Comment by severo** [comment]
I disagree with this. It was the previous behavior, and we recently changed to copy the previous error so that the users see a meaningful error message, instead of an internal one ("...previous step failed...")
It makes it a bit more complex for us to monitor, but the users are first.
Not that it's still easy to discriminate between "original" and "copied" errors, since we add the `details.copy_from_another_error: true` field in the cached response entry. So, we can filter without much difficulty. It's just that we don't do it as of now in the metrics.

**Comment by AndreaFrancis** [comment]
Sure, I totally agree now. I can work on this change on the metrics side.

**Comment by severo** [comment]
OK! Not urgent, though

**Comment by severo** [comment]
Let's close, it's not very important
