### ISSUE TITLE
/rows: raise an error if a dataset has too big row groups

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1527]
It can happen if a dataset was converted to parquet before the recent row group size optimization, e.g. garythung/trashnet

Currently it makes the worker crash.

We could also refresh the parquet export of the dataset when this happens

**Comment by severo** [comment]
See https://github.com/huggingface/datasets-server/pull/1520#issuecomment-1640684785

> Could be, but instead of complicating the code for that, maybe do a one-time analysis on all the datasets that have a size over ...GB
