### ISSUE TITLE
The metrics jobs are lasting to long

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1579]
<img width="306" alt="Capture d’écran 2023-07-28 à 11 01 37" src="https://github.com/huggingface/datasets-server/assets/1676121/0f1c0120-b2e2-4133-b5da-312b7981c4f1">

**Comment by AndreaFrancis** [comment]
Closing since the issue is no longer happening. It was related to a db index maintenance action.
  
![Screenshot from 2023-07-28 11-51-25](https://github.com/huggingface/datasets-server/assets/5564745/543fd94a-bb2d-4c52-8279-6dae7334629d)

**Comment by severo** [comment]
thanks for investigating
