### ISSUE TITLE
In config-parquet-metadata, delete the old files before uploading new ones

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1613]
I'm currently moving the parquet-metadata files to a new storage, and I see strange numbering for shards. See for example, in the same directory (35456 parquet files for this one):

```
root@prod-datasets-server-storage-admin-786cfbf44-4ncpv:/storage# ls parquet-metadata-new/Antreas/TALI-large-2/--/Antreas--TALI-large-2/ | tail
parquet-train-00059-of-00085.parquet
parquet-train-00059-of-00086.parquet
parquet-train-00059-of-00087.parquet
parquet-train-00059-of-00088.parquet
parquet-train-00059-of-00089.parquet
parquet-train-00059-of-00090.parquet
parquet-train-00059-of-00092.parquet
parquet-train-00059-of-00093.parquet
parquet-train-00059-of-00094.parquet
parquet-train-00059-of-00095.parquet
root@prod-datasets-server-storage-admin-786cfbf44-4ncpv:/storage# ls parquet-metadata-new/Antreas/TALI-large-2/--/Antreas--TALI-large-2/ | tail
parquet-train-00072-of-00257.parquet
parquet-train-00072-of-00258.parquet
parquet-train-00072-of-00259.parquet
parquet-train-00072-of-00260.parquet
parquet-train-00072-of-00261.parquet
parquet-train-00072-of-00262.parquet
parquet-train-00072-of-00264.parquet
parquet-train-00072-of-00265.parquet
parquet-train-00072-of-00266.parquet
parquet-train-00072-of-00267.parquet
```

Is it normal @lhoestq? I think the second number should never change for a given split, right?

**Comment by severo** [comment]
This specific dataset does not exist anymore: https://huggingface.co/datasets/Antreas/TALI-large-2.

I saw the same in other datasets, but they also seem to have disappeared (ArmelR/FreeLaw, ArmelR/Github)

**Comment by severo** [comment]
Related: @lhoestq: a dataset like https://huggingface.co/datasets/ArmelR/sharded-pile has 1266 parquet files, and thus 1266 super small parquet metadata files. Would having only one parquet metadata file for all the shards make sense?

**Comment by severo** [comment]
Weird behavior on https://huggingface.co/datasets/ArtifactAI/arxiv_python_research_code, for example:

we have:

```
parquet-train-00000-of-00025.parquet
...
parquet-train-00024-of-00025.parquet
parquet-train-00000-of-00026.parquet
...
parquet-train-00025-of-00026.parquet
... and then so on until
parquet-train-00000-of-00050.parquet
...
parquet-train-00049-of-00050.parquet
```

I now understand what's going on:
- the user is adding data commit per commit
- on every version, we run all the DAG
- thus: we have 25 parquet shards, then 26, then 27... until 50 when the whole dataset has been uploaded.

Our issue here is that we don't delete the files from the previous commits. It should be part of the config-parquet-metadata step (like we do for the config-parquet-and-info step: list all the existing files, contrast with the files that should exist, and delete the difference)

**Comment by severo** [comment]
Related to #1122 and #1284

**Comment by lhoestq** [comment]
Now the file names are 000.parquet, 0001.parquet etc. so this weird pattern should be gone.

Though the job currently doesn't delete the old files with the old naming so we should take care of that

**Comment by severo** [comment]
replaced by #2384
