### ISSUE TITLE
Handle breaking change in google dependency?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1689]
See https://huggingface.co/datasets/bigscience/P3/discussions/6#64dca122e3e44e8000c45616

Should we downgrade the dependency, or fix the datasets?

**Comment by mariosasko** [comment]
The simplest solution is probably to convert `bigscience/P3`'s TFRecord files to Parquet to fix the viewer. This should also speed up the dataset generation. 

@VictorSanh Are you OK with this change?

**Comment by VictorSanh** [comment]
Sorry I haven't been checking much GH for the past few days being off.
Yes that sounds good to me! Let me know if I can help for the conversion!
