### ISSUE TITLE
delete obsolete cache records

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#1696]
When running dataset-config-names force-refresh for datasets with only one config for https://github.com/huggingface/datasets-server/issues/1550 , I found that for dataset `triple-t/dummy`, the previous config remains in the db `triple-t/dummy.`
All cache records related to  `triple--t/dummy` should have been removed.

See 
![Screenshot from 2023-08-16 18-05-54](https://github.com/huggingface/datasets-server/assets/5564745/259711df-2f53-4cd1-b6e9-6bc53b4f1a00)

We could do it after previous job has finished.

**Comment by severo** [comment]
Done.

```
db.cachedResponsesBlue.estimatedDocumentCount()
5720377
db.cachedResponsesBlue.countDocuments({"config": /--/i})
805504
db.cachedResponsesBlue.deleteMany({"config": /--/i})
{ acknowledged: true, deletedCount: 805504 }
db.cachedResponsesBlue.estimatedDocumentCount()
4915107
db.cachedResponsesBlue.countDocuments({"config": /--/i})
0
```
