### ISSUE TITLE
Implement Server-sent events to update the Hub cache

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1718]
The Hub needs to know which datasets have a viewer, or only a preview. Currently, we publish the /valid endpoint, which returns a list of all the dataset names that has the search capability, the viewer, or just the preview.
It has two drawbacks:
1. it gives information about the gated datasets
2. it does not scale (the queries to the database take too much time, > 10s, even > 20s when the database is under load)

The solution we will implement is to send Server-sent events to the Hub.

**Comment by severo** [comment]
Internal reference: https://huggingface.slack.com/archives/C04L6P8KNQ5/p1692719271678269?thread_ts=1692705169.430019&cid=C04L6P8KNQ5

**Comment by severo** [comment]
Replaces https://github.com/huggingface/datasets-server/issues/891.

**Comment by severo** [comment]
Docs: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events, https://html.spec.whatwg.org/multipage/server-sent-events.html.

Questions:
- should we set an `id` on the messages? which means: should we keep a buffer of all the messages the client did not receive and send them again when the connection is back?
- this mechanism is only for updates. Should we maintain `/valid` to give the current state, when the Hub's backend starts?

**Comment by Kakulukian** [comment]
> * this mechanism is only for updates. Should we maintain `/valid` to give the current state when the Hub's backend starts? If we maintain it, we should paginate the response.

For this part, Spaces gave us the complete list of spaces then only updated one

**Comment by severo** [comment]
It has been working for weeks now. Closing.
