### ISSUE TITLE
Locks sometimes block all the workers

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1727]
It can happen that the job from `Queue().get_next_waiting_job()` is wrongly locked, which can make the workers fail to start a new job.

A way to fix this is to find a way to not have wrong locks or simply to ignore locked jobs in `Queue().get_next_waiting_job()`.

**Comment by lhoestq** [comment]
I might just add a TTL for unicity_id locks

**Comment by severo** [comment]
best option in my opinion
