### ISSUE TITLE
/search num_rows_total field is incoherent

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1729]
In the following example, num_rows_total=1 (ie. the total number of results for that search) while the `rows` field is an array of 100 rows

https://datasets-server.huggingface.co/search?dataset=loubnabnl/gpt4-1k-annotations&config=default&split=train&query=pokemon&offset=0&limit=100

**Comment by AndreaFrancis** [comment]
Good catch! Thanks for reporting!

**Comment by AndreaFrancis** [comment]
Fixed on https://github.com/huggingface/datasets-server/pull/1730
