### ISSUE TITLE
Audio feature is not displayed correctly on the first page (not in pagination)

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets-server#1740]
It says `Not supported with pagination yet`, example: https://huggingface.co/datasets/open-asr-leaderboard/datasets-test-only

As far as I understand it is an expected behavior for pages starting from 2 page because audio was [intentionally disabled](https://github.com/huggingface/datasets-server/issues/1255) for `/rows` but it should be displayed in the first 100 rows.

**Comment by severo** [comment]
The first page is now shown using /rows when available, instead of /first-rows. It's a breaking change, that we might want to revert, indeed.

**Comment by severo** [comment]
Related: https://github.com/huggingface/moon-landing/issues/6864

**Comment by lhoestq** [comment]
fixed with https://github.com/huggingface/moon-landing/pull/7387
