### ISSUE TITLE
Support Search for datasets on the first 5GB of big datasets

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1742]
If a dataset is in parquet format the viewer shows the full dataset but search is disabled.

In this case it would be nice to support search anyway, at least on the first 5GB.

**Comment by lhoestq** [comment]
related to https://github.com/huggingface/datasets-server/issues/1758

**Comment by lhoestq** [comment]
I think I'll add new jobs `duckdb_index_size` for the front end to know whether `search` can be performed on the full dataset or only on the first 5GB.

IMO the viewer should display "(First 5GB)" if the index is partial - even if the parquet export is full.

It can also use the `num_rows` from indexing instead of the `num_rows` from the parquet export to determine the number of pages and to display in the configs and splits dropdown. What do you think @severo ?

**Comment by severo** [comment]
I agree: we now have two sources of truth depending on the service (/rows, or /search+/filter), but we have only the size for the first one (parquet). We should have the information for both (size, number of rows, if it is partial) for Parquet and DuckDB.
I don't know how we should make the API evolve, though. Do you want to work on a proposal?

**Comment by lhoestq** [comment]
I'm on it ;)
