### ISSUE TITLE
[refactor] extract split name from the URL

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1755]
We use the same code [here](https://github.com/huggingface/datasets-server/pull/1750/files#diff-b31b94865cf356d2b241fc7f38f98bd9484d61464a991d06364bdf82c2c5ba4eR292), [here](https://github.com/huggingface/datasets-server/pull/1750/files#diff-51b62bca3846b24d6554358a34bd39d0db4db7f24e378182fde2d549e2d1268bR353) and [here](https://github.com/huggingface/datasets-server/pull/1750/files#diff-d9a2c828d7feca3b7f9e332e040ef861e842a16d18276b356461d2aa34396a8aR131).

It could be factorized.

**Comment by egndz** [comment]
#self-assign
