### ISSUE TITLE
Unsafe warning for github code clean

### ISSUE THREAD

**Issue by chinghuachen** [huggingface/datasets-server#1775]
The [Github Code Clean data set ](https://huggingface.co/datasets/codeparrot/github-code-clean) shows 47 unsafe files. May I request a re-scan with ClamAV to confirm that these are indeed unsafe? I have seen elsewhere (#882) that a re-scan resulted in files that were previously deemed unsafe were in fact OK.

**Comment by severo** [comment]
cc @McPatate

**Comment by severo** [comment]
I'm closing the issue on this repo (which only handles the dataset viewer table) and I opened a discussion here: https://huggingface.co/datasets/codeparrot/github-code-clean/discussions/3

**Comment by chinghuachen** [comment]
thank you for re-directing, @severo
