### ISSUE TITLE
update datasets to 2.14.5

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1781]
https://github.com/huggingface/datasets/releases/tag/2.14.5

I think it does not require changes in the code, right?

Also: I'm not sure if we have to refresh datasets to fix errors. Maybe:
- Do not filter out .zip extensions from no-script datasets by @albertvillanova in https://github.com/huggingface/datasets/pull/6208

Could you confirm @lhoestq @albertvillanova @polinaeterna or @mariosasko ?

**Comment by albertvillanova** [comment]
Some of the fixes done by @lhoestq were motivated by viewer issues on the Hub:
- PR: https://github.com/huggingface/datasets/pull/6218
  - motivated by viewer issue in: https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions
Maybe he can give more details.

**Comment by severo** [comment]
OK thanks. How can we create the list of all the datasets to be refreshed?
1. for https://github.com/huggingface/datasets/pull/6218
2. for https://github.com/huggingface/datasets/pull/6208

**Comment by lhoestq** [comment]
I have some ideas to refresh the ones like the pokemon one. Will take care of it tomorrow. Regarding zip I'm not sure

**Comment by severo** [comment]
I deployed it, so feel free to launch refreshes

**Comment by lhoestq** [comment]
Fixed ! https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions

and deleted 1k cache entries for image datasets with the same issue and 270 cache entries for audio datasets

**Comment by severo** [comment]
Was it the `PreviousStepFormatError` error code? The number of occurrences dropped from 1.650 to 880 in the last 12h!

<img width="786" alt="Capture d’écran 2023-09-07 à 11 38 33" src="https://github.com/huggingface/datasets-server/assets/1676121/8969ee67-352e-4dec-8243-fe7b1a9779fa">

**Comment by lhoestq** [comment]
Nope I simply checked the features in the dataset_info
