### ISSUE TITLE
Delete obsolete cache entries (config="namespace--dataset", instead of default")

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1810]
All the datasets now use "default" as the default config name. However, the cache entries that used the previous default value ("namespace--dataset") are still in the database, even if not used anymore. We have to delete them.

**Comment by AndreaFrancis** [comment]
Looks duplicated of https://github.com/huggingface/datasets-server/issues/1696

**Comment by severo** [comment]
Right!
