### ISSUE TITLE
erroneous "en" config in parquet-and-info for dataset aakanksha/udpos 

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1812]
Here:

https://github.com/huggingface/datasets-server/blob/09e3f9827048d552c4aefc8125fe6366dbeabc34/services/worker/src/worker/job_runners/config/parquet_and_info.py#L422

`builder.config.name` is changed from `default`(the correct value) to `en`, which breaks the final response (parquet files are created under [`en/`](https://huggingface.co/datasets/aakanksha/udpos/tree/refs%2Fconvert%2Fparquet/en) directory, which later does not match with the expected `default` config).

I have no idea why, or how to fix that.

**Comment by severo** [comment]
I assign you @lhoestq, I imagine you should have a better idea.

**Comment by severo** [comment]
Once fixed, close #1582 and refresh the datasets listed in

```
db.cachedResponsesBlue.aggregate([
    {$match: {error_code: "PreviousStepFormatError", "kind": "config-parquet-metadata"}},
    {$group: {_id: 0, datasets: {"$addToSet": "$dataset"}}},	
])
```

**Comment by lhoestq** [comment]
Taking a look

**Comment by lhoestq** [comment]
Just opened https://github.com/huggingface/datasets/pull/6253

We'll have to refresh those datasets when the fix will be released

**Comment by severo** [comment]
Is this issue obsolete now that dataset scripts are disabled?

I just refreshed the example dataset https://huggingface.co/datasets/aakanksha/udpos, and it shows 

<img width="1027" alt="Capture d’écran 2023-11-03 à 22 48 39" src="https://github.com/huggingface/datasets-server/assets/1676121/b4d4de4c-75bf-4b1b-b267-6fe0a670da86">

**Comment by severo** [comment]
should we close @lhoestq ?
