### ISSUE TITLE
Search times out for long queries

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1860]
searching for small queries like `nerijs`  or `nerijs pixel` works, but not for `nerijs pixel art xl` in https://huggingface.co/datasets/multimodalart/lora-fusing-preferences

It seems to be due to time out because long queries take longer to run

**Comment by lhoestq** [comment]
I think increasing the delay before time out should be fine @AndreaFrancis no ?
Maybe cc @severo if you know the place in moon landing to modify it

**Comment by severo** [comment]
see https://github.com/huggingface/moon-landing/pull/7579 (internal)

**Comment by severo** [comment]
https://huggingface.co/datasets/multimodalart/lora-fusing-preferences now shows

```
Error code:   JobManagerExceededMaximumDurationError
```

Refreshing it

**Comment by severo** [comment]
Note that this dataset is also reported here: https://github.com/huggingface/datasets-server/issues/1859 for having too big row groups

**Comment by severo** [comment]
same error:  JobManagerExceededMaximumDurationError

**Comment by AndreaFrancis** [comment]
It seems to be working now for https://huggingface.co/datasets/multimodalart/lora-fusing-preferences. Maybe the worker's memory increase helped.
![image](https://github.com/huggingface/datasets-server/assets/5564745/a2e2f2f2-7147-4fee-a048-7deacf096f7d)
![image](https://github.com/huggingface/datasets-server/assets/5564745/389b6810-b2b8-4336-85d4-9c659b176906)

Could we close this issue?

**Comment by lhoestq** [comment]
Yes OP is fixed, thanks !
