### ISSUE TITLE
Remove obsolete code once cached-assets is fully migrated to S3

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#1885]
Once we validate that cached-assets is working as expected on S3 instead of EFS, we can remove obsolete code.
For example clean_cached_assets from time to time in /rows and /search.

**Comment by albertvillanova** [comment]
Should we keep this issue open?

**Comment by AndreaFrancis** [comment]
Part of the obsolete code was removed here https://github.com/huggingface/datasets-server/pull/1988 and the remaining part will be handled here https://github.com/huggingface/datasets-server/pull/1976

**Comment by severo** [comment]
can it be closed with https://github.com/huggingface/datasets-server/pull/2040?

**Comment by AndreaFrancis** [comment]
Completed with https://github.com/huggingface/datasets-server/pull/2068
