### ISSUE TITLE
/filter returns Unexpected error for string columns

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1990]
For example:

https://datasets-server.huggingface.co/filter?dataset=tapaco&config=af&split=train&where=language=%27af%27

```
{"error":"Unexpected error."}
```

**Comment by severo** [comment]
Note that https://datasets-server.huggingface.co/filter?dataset=julien-c/titanic-survival&config=default&split=train&where=Sex=%27female%27&length=2 works (it's an example in OpenAPI)

**Comment by severo** [comment]
The error is:

```
RuntimeError: The indexing process did not store the features.
```

**Comment by severo** [comment]
https://github.com/huggingface/datasets-server/blob/30f58b58ef29215e895b9f9dacb3d000d7e8ea10/services/search/src/search/routes/filter.py#L143-L152

**Comment by severo** [comment]
I'm trying to recompute the duckdb index for tapaco

**Comment by severo** [comment]
It now works for tapaco / af. So: the issue seems to be outdated index DuckDB files. cc @AndreaFrancis @albertvillanova : can you see how to refresh all the outdated duckdb files?

**Comment by severo** [comment]
Assigning @albertvillanova, since he is refreshing the missing datasets. Thanks!

**Comment by albertvillanova** [comment]
Also @AndreaFrancis, who patiently show me all the procedure step by step.

**Comment by AndreaFrancis** [comment]
Done.
We called `force-refresh` action for `config-parquet-and-info` step in 9208 configs, see file 
[filter-unexpected-errors.csv](https://github.com/huggingface/datasets-server/files/13044026/filter-unexpected-errors.csv) for a detailed list.
Also, I deleted the content in `/storage/duckdb-index/downloads` to avoid querying from outdated `index.duckdb` files.
