### ISSUE TITLE
How to pass single quote in /filter endpoint "where" parameter?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2038]
See `https://huggingface.co/datasets/albertvillanova/lm_en_dummy2/viewer/default/train?f[meta][value]='{'file': 'file_4.txt'}'`

From `https://datasets-server.huggingface.co/filter?dataset=albertvillanova/lm_en_dummy2&config=default&split=train&where=meta='{'file': 'file_4.txt'}'`, we get:

```
{"error":"Parameter 'where' is invalid"}
```

We want to search he value `{'file': 'file_4.txt'}` in the column `meta`

**Comment by severo** [comment]
Do you have an idea @albertvillanova?

**Comment by albertvillanova** [comment]
You have to escape it by prepending another single quote: 
```
https://datasets-server.huggingface.co/filter?dataset=albertvillanova/lm_en_dummy2&config=default&split=train&where=meta='{''file'': ''file_4.txt''}'
```

Maybe I should implement this escaping automatically in the /filter endpoint. What do you think?

**Comment by severo** [comment]
Yes, I think it would be helpful to have the endpoint handle these details

**Comment by albertvillanova** [comment]
@severo, as we support composite predicates in the WHERE clause, this issue is harder to fix than it may seem at first sight.

I have investigated even using a SQL parser, but all of them assume that the single quotes have previously been escaped.

What about just explaining this in the docs? The escaping of the single quote is usual in SQL syntax.

**Comment by severo** [comment]
Yes, OK

**Comment by severo** [comment]
Indeed https://huggingface.co/datasets/albertvillanova/lm_en_dummy2/viewer/default/train?f[meta][value]=%27{%27%27file%27%27:%20%27%27file_4.txt%27%27}%27 works (two single quotes instead of single quotes)

**Comment by severo** [comment]
Fix in the Hub's code (internal): https://github.com/huggingface/moon-landing/pull/7968
