### ISSUE TITLE
Delete duckdb files when a split is deleted

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2053]
See https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k/tree/refs%2Fconvert%2Fparquet/default/train

The `train` split existed, but has been deleted. Now, the datasets has `train_sft` and `train_gen`. But the duckdb index file still exists for `train` in `refs/convert/parquet`. Note that the parquet files have been deleted.

**Comment by severo** [comment]
cc @albertvillanova or @AndreaFrancis

**Comment by AndreaFrancis** [comment]
Fixed 
![image](https://github.com/huggingface/datasets-server/assets/5564745/744e470d-f24a-4409-8b67-2eab99c91894)

**Comment by AndreaFrancis** [comment]
I will try to find a way to identify if other datasets have been affected, surely, yes, but it will automatically be fixed whenever the split-duckdb-index step is executed again for a given config.

**Comment by severo** [comment]
> I will try to find a way to identify if other datasets have been affected, surely, yes, but it will automatically be fixed whenever the split-duckdb-index step is executed again for a given config.

OK, so: don't worry, we will have to compute them all when upgrading duckdb
