### ISSUE TITLE
The "Recreate dataset" admin action first fails, then works

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2057]
First click on the button:
<img width="1526" alt="Capture d’écran 2023-11-03 à 22 55 31" src="https://github.com/huggingface/datasets-server/assets/1676121/ebbcb349-ca39-4a6e-9aee-f244ef0ebbf6">

Second click (a few seconds later):
<img width="1526" alt="Capture d’écran 2023-11-03 à 22 55 38" src="https://github.com/huggingface/datasets-server/assets/1676121/96ecc3d3-e5a8-4d95-a20f-2c239589ed7d">

**Comment by AndreaFrancis** [comment]
I saw this error last week, looks like it is related to storage trying to delete unexistent files in cached-assets bucket. I will take a look.

**Comment by AndreaFrancis** [comment]
Fixed in https://github.com/huggingface/datasets-server/pull/2071
