### ISSUE TITLE
Skip local configs in mixed local+downloadable datasets

### ISSUE THREAD

**Issue by anton-l** [huggingface/datasets-server#208]
Some benchmark-type datasets can have non-downloadable configs, e.g. when one of its subsets is a closed-license dataset. One of such datasets is BABEL, as part of a larger benchmark collection XTREME-S: https://huggingface.co/datasets/google/xtreme_s

Here the preview backend is trying to load the `babel.<lang>` configs that require local files:
```
Status code:   400
Exception:     FileNotFoundError
Message:       You are trying to load the 'babel.as' speech recognition dataset. It is required that you manually download the input speech data. Manual download instructions: Please make sure to get access and download the following dataset LDC2016S06 from https://catalog.ldc.upenn.edu/LDC2016S06.
            Once downloaded make sure that you pass the path to the downloaded file IARPA_BABEL_OP1_102_LDC2016S06.zip as a manual downloaded dataset:
            `load_dataset("google/xtreme-s", "babel.as", data_dir='path/to/IARPA_BABEL_OP1_102_LDC2016S06.zip')`.
        
```

**Expected**:
Skip the `babel.<lang>` configs as they require `data_dir`, and load the rest of the configurations (`fleurs.<lang>`, `mls.<lang>`, `minds14.<lang>`...)

**Comment by severo** [comment]
Fixed!

<img width="1032" alt="Capture d’écran 2023-03-28 à 11 16 01" src="https://user-images.githubusercontent.com/1676121/228190273-8d827374-2354-46b1-9fce-082ec28006d1.png">
