### ISSUE TITLE
TransformRowsProcessingError in /rows with simple audio dataset

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2096]
https://huggingface.co/datasets/GregoryVandromme/vandromme_dataset/viewer/default/test

https://datasets-server.huggingface.co/rows?dataset=GregoryVandromme/vandromme_dataset&config=default&split=test

```
{"error":"Server error while post-processing the split rows. Please report the issue."}
```

Reported here: https://huggingface.co/datasets/GregoryVandromme/vandromme_dataset/discussions/1

**Comment by albertvillanova** [comment]
I have investigated, and apparently we no longer support audio no-script datasets on the Hub.

See:
- https://huggingface.co/datasets/albertvillanova/tmp-wav/viewer/default/train

I am fixing it.
