### ISSUE TITLE
LockedDatasetTimeoutError on laion/dalle-3-dataset

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2123]
Step `config-parquet-and-info` on `laion/dalle-3-dataset` (config=default) fails with error 

```
 {"error": "the dataset is currently locked, please try again later."}
```

See https://github.com/huggingface/datasets-server/blob/62f589bbc0be836e3d68353885410ec6309afbd7/services/worker/src/worker/job_runners/config/parquet_and_info.py#L1237

**Comment by albertvillanova** [comment]
I had a similar issue recently with "wikimedia/wikipedia". See internal discussion: https://huggingface.slack.com/archives/C04L6P8KNQ5/p1702040773865629

@lhoestq fixed it by manually deleting the lock from "datasets_server_queue.locks" collection.

**Comment by severo** [comment]
yes, I had to do it too on other datasets.

Currently, we have some old locks: 117 out of 3.268 current locks are from yesterday or before. We should remove them. We have a TTL index that should do it (remove after 10 minutes, if the owner is null, or if the `ttl` field is equal to `600`). But the 117 remaining locks have `ttl: null`.

**Comment by severo** [comment]
maybe @lhoestq wants to chime in

**Comment by lhoestq** [comment]
I opened https://github.com/huggingface/datasets-server/pull/2200 to add a TTL on those locks

**Comment by severo** [comment]
We still have 497 entries. But look at the following one: it's for config `farsi_fa` which does not exist anymore in dataset https://huggingface.co/datasets/BramVanroy/xlwic_wn. Thus it's an obsolete cache entry that should not exist anymore. Simply: we don't have a mechanism to delete this kind of entries (cc @AndreaFrancis for visibility)

<img width="501" alt="Capture d’écran 2023-12-18 à 12 40 34" src="https://github.com/huggingface/datasets-server/assets/1676121/25297262-1cb8-465f-b832-9e30efe5d99a">

It seems like most remaining errors (older than today) are due to that reason.
