### ISSUE TITLE
Unblock two datasets

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2125]
Revert https://github.com/huggingface/datasets-server/pull/2120 once huggingface_hub 0.20 has been released. In particular, we're interested in:
- https://github.com/huggingface/huggingface_hub/pull/1809
- https://github.com/huggingface/huggingface_hub/pull/1815

**Comment by pathum2583-eng** [comment]
Revert https://github.com/huggingface/datasets-server/pull/2120 once huggingface_hub 0.20 has been released. In particular, we're interested in:
- https://github.com/huggingface/huggingface_hub/pull/1809
- https://github.com/huggingface/huggingface_hub/pull/1815

**Comment by pathum2583-eng** [comment]
@pathum2583-eng  6323aecb672775b6a310f139f67084ae8d6b8751
