### ISSUE TITLE
The dataset viewer associates the wrong audio to a sample

### ISSUE THREAD

**Issue by ylacombe** [huggingface/datasets-server#2158]
### Describe the bug

When I filtered on some new audio datasets, I realized that sometimes the audio were  associated to the wrong sample. 
It's easy to notice when playing the first sample of this filtered view:  [view (see `line_id = EN1321`)](https://huggingface.co/datasets/ylacombe/english_dialects/viewer/welsh_female/train?f%5Bspeaker_id%5D%5Bmin%5D=5487&f%5Bspeaker_id%5D%5Bmax%5D=6488). You'll notice that the audio does not correspond to the transcription.

This also happens when navigating in a private mode.

I've verified manually that this was not a labeling error by sampling loading this dataset with `datasets`. This time the audio associated with the `line_id = EN1321` and `speaker_id=6136` was the correct one.

### Steps to reproduce the bug

On Google Chrome, open [this](https://huggingface.co/datasets/ylacombe/english_dialects/viewer/welsh_female/train?f%5Bspeaker_id%5D%5Bmin%5D=5487&f%5Bspeaker_id%5D%5Bmax%5D=6488) and look at line associated to `line_id = EN1321`.

### Expected behavior

We expect the audio to corresponds to the transcription.

### Environment info

Google Chrome, the 28th November!

**Comment by lhoestq** [comment]
Confirming it comes from the back-end: https://datasets-server.huggingface.co/filter?dataset=ylacombe/english_dialects&config=welsh_female&split=train&offset=0&length=5&&where=speaker_id=6136

The audio WAV file at https://datasets-server.huggingface.co/cached-assets/ylacombe/english_dialects/--/ed3d69abb765fd304ccdcc646ec6ca3c49740d15/--/welsh_female/train/62/audio/audio.wav doesn't correspond to the transcription:

```json
{
      "row_idx": 62,
      "row": {
        "line_id": "EN1321",
        "audio": [
          {
            "src": "https://datasets-server.huggingface.co/cached-assets/ylacombe/english_dialects/--/ed3d69abb765fd304ccdcc646ec6ca3c49740d15/--/welsh_female/train/62/audio/audio.wav",
            "type": "audio/wav"
          }
        ],
        "text": "Pillow lavas are lavas that contain characteristic pillow-shaped structures that are attributed to the extrusion of the lava under water",
        "speaker_id": 6136
      }
}
```

**Comment by albertvillanova** [comment]
The issue seems to be present as well on /rows: https://huggingface.co/datasets/ylacombe/english_dialects/viewer/welsh_female/train?p=1
- `line_id = EN1321`

**Comment by lhoestq** [comment]
Since it's also in /rows it means the issue is in the Parquet files Oo

**Comment by lhoestq** [comment]
Are you sure the issue doesn't come from your dataset itself @ylacombe ? The Parquet files used for /rows are the ones you pushed to hub (copied to the refs/convert/parquet branch)

**Comment by lhoestq** [comment]
Ah yes it works with `datasets` indeed ! This requires more investigation

**Comment by lhoestq** [comment]
Ok I found the issue: the datasets-server returns the URL of the audio file at row index 62 instead of 162

**Comment by albertvillanova** [comment]
Maybe related to:
- #1920

**Comment by albertvillanova** [comment]
I think that the issue was fixed by PR:
- #2172

Could you please confirm, @ylacombe?

**Comment by ylacombe** [comment]
Indeed, it seems fixed!
