### ISSUE TITLE
Self-hosting an instance of HF datasets on premises

### ISSUE THREAD

**Issue by surak** [huggingface/datasets-server#2160]
Hi, 

Maybe I didn't read correctly, but I was thinking if it's possible to host an instance of the same middleware you use in our research institution so we could host our own datasets in a HF way.

The idea is that I am writing from the biggest research center in Europe, and we produce A LOT of data, and we use a lot of datasets from other sources as well - be it medical and confidential, or anything up to simple stuff like imagenet or common crawl. We host it all.

So far, this has been done in a very haphazard and ad-hoc way - people download everything into a folder visible to the supercomputers.

I would like to change that and do it in an organized way, so I would like to host the whole thing - the web server and the datasets.

Does my question even make sense? I can explain better if not.

If you have parts of your infra which are not open, I totally understand. Just let me know and I will search for an alternative.

Thanks!

**Comment by severo** [comment]
Hi. The datasets-server is developed openly, but I'm not sure how well it would work if installed as another instance.

In particular, most parts are intricated with the Hub (https://huggingface.co):
- the datasets server has a 1-1 relation with the Hub's datasets repositories (every dataset has specific metadata stored in the datasets server)
- the Hub sends a webhook to the datasets server to ping it when a dataset has been updated
- the datasets server hosts the converted parquet files on the Hub (in the `refs/convert/parquet` branch)
- etc.

And the Hub itself is not open source

So: I think it would be hard to make it work with another "Hub"

---

But, maybe we can explore with the team, to find other ways to help you and provide that service. cc @jeffboudier

**Comment by severo** [comment]
> But, maybe we can explore with the team, to find other ways to help you and provide that service.

I was specifically thinking of https://huggingface.co/enterprise. Would it make sense for you to host the datasets on Hugging Face as private datasets? You could select the "region" if it's important to store your data in Europe, for example.

**Comment by surak** [comment]
No- the idea is to have it on the filesystem of the supercomputers, as the compute nodes have no internet access, and anything which is not local makes little sense on this case.

Plus, we are talking multi-petabyte for several things here. Those things might take weeks just to transfer from one research institution to another. Cloud is not an option.

Thanks for the effort, really. I will close this one, as it makes no business sense to you guys to open the hub and it makes no sense to me to replicate its functionality as well.
