### ISSUE TITLE
The "Recreate" admin tab does not work

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2195]
<img width="1099" alt="Capture d’écran 2023-12-11 à 14 26 29" src="https://github.com/huggingface/datasets-server/assets/1676121/db50d616-5f3c-40c0-8df6-417c46277bf5">

**Comment by AndreaFrancis** [comment]
It is related to my last change (removing finished_at). Maybe a deploy will fix it; I will do it.

**Comment by AndreaFrancis** [comment]
It is working now 
![image](https://github.com/huggingface/datasets-server/assets/5564745/f153b822-1a15-458e-bbe8-3823df0b8b8c)

**Comment by severo** [comment]
Thanks @AndreaFrancis!
