### ISSUE TITLE
/rows generates empty images

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2297]
See https://huggingface.co/datasets/HuggingFaceM4/WebSight/viewer/default/train?p=1

<img width="1386" alt="Capture d’écran 2024-01-15 à 16 12 40" src="https://github.com/huggingface/datasets-server/assets/1676121/a20f3628-5ddd-400c-a067-17d47a6caedb">

Note that /first-rows images are OK.

<img width="1025" alt="Capture d’écran 2024-01-15 à 16 13 14" src="https://github.com/huggingface/datasets-server/assets/1676121/c34c00d5-e195-43ae-990e-dad431f6a6d0">

Reported by @VictorSanh on Slack (internal): https://huggingface.slack.com/archives/C02V51Q3800/p1705330620412079

**Comment by severo** [comment]
No error is raised in the code:

![Uploading Capture d’écran 2024-01-15 à 17.31.52.png…]()

**Comment by lhoestq** [comment]
Hmm for some reason the image files are 0 bytes, let me investigate
