### ISSUE TITLE
[Croissant] The API supports a parameter to produce either an abridged JSON-LD or a full-length JSON-LD

### ISSUE THREAD

**Issue by marcenacp** [huggingface/datasets-server#2332]
**Issue**: Croissant JSON-LD are embedded in Hugging Face's HTML page. As JSON-LD can get lengthy, they are truncated ([see the code](https://github.com/huggingface/datasets-server/blob/1759d65fa668f35067175cfb3210666c1b7c3f47/services/api/src/api/routes/croissant.py#L99)).

**Proposed solution**: Add a parameter `?full=true/false` (with a default to false) to toggle between the abridged version or the full-length version of the JSON-LD. Hugging Face would use the abridged version to embed in their HTML page, while still allowing users to retrieve the full version to produce a valid Croissant file. Ideally the description of the abridged version would state that it's (or may be) abridged, and provide the URL of the full version. This is a temporary solution while waiting for <meta> tags to support URLs rather than in-lined JSON.

@lhoestq @severo What do you think? Also, what convention do you usually use for the URL parameters? Do you have examples of such routes? If I have your go, I could implement this. Thanks for your input!

**Comment by severo** [comment]
Good idea. Feel free to open a PR!

> what convention do you usually use for the URL parameters?

We have no other boolean parameter, I think. @lhoestq should we pass:
- `?full=true/false`
- or `?max_columns=1000`, and if not present: return the full response?

If we opt for the integer parameter, you could take example on https://github.com/huggingface/datasets-server/blob/1759d65fa668f35067175cfb3210666c1b7c3f47/services/rows/src/rows/routes/rows.py#L72

else, we should do the same, but for a boolean value. If so, I think checking for exact value `true` is OK, and coherent with what we do on the Hub (https://huggingface.co/spaces/enzostvs/hub-api-playground)

---

> Ideally the description of the abridged version would state that it's (or may be) abridged, and provide the URL of the full version

OK, good idea. As we return a croissant content that we "directly" embed in the HTML, it would be better if it's part of the croissant specification, or at least not incompatible with it
