### ISSUE TITLE
Detect tags and serve them in /is-valid

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2350]
First tags to detect:
- webdataset
- croissant

`/is-valid` response will change from

```json
{
    "preview": true,
    "viewer": true,
    "search": true
    "filter": true
}
```

to

```json
{

    "preview": true,
    "viewer": true,
    "search": true
    "filter": true,
    "tags": ["croissant"]
}
```

**Comment by severo** [comment]
For "croissant", the tag is detected if the `dataset-info` artefact exists for the dataset.

For "webdataset", the tag is detected if the `dataset-info` matches `["content"][dataset_info"]["default"]["builder_name"] == "webdataset`

**Comment by AndreaFrancis** [comment]
I think in the future we can change de idea/name of 'is-valid' for something more informative

**Comment by severo** [comment]
exactly, with every change, the name becomes less accurate

**Comment by lhoestq** [comment]
I was thinking that we could have a new job "loaders".
In v1 we return the list of  {"loader": string} that we can add to the is-valid tags.

And we can iterate for the code snippets for v2
For example with the info to build the code snippet like
```
{"loader": "webdataset", "url": "pipe:curl <hf url>"}
```
This way the front end can translate it to
```python
import webdadataset as wds

url = "pipe:curl <hf url>"
ds = wds.WebDataset(url).decode()
```

For croissant it would be
```
{"loader": "mlcroissant", "url": "<croissant url>"}
```
for
```python
import mlcroissant as mlc

url = "<croissant url>"
ds = mlc.Dataset(url)
```

**Comment by severo** [comment]
Done with #2386 (in /hub-cache, not /is-valid).

For the last comment: let's open another issue @lhoestq ?
