### ISSUE TITLE
Replace `DatasetModuleNotInstalledError` errors with `DatasetWithScriptNotSupportedError`

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2385]
We should never have a `DatasetModuleNotInstalledError` error, because we should return a `DatasetWithScriptNotSupportedError` error before

See https://github.com/huggingface/datasets-server/issues/1067#issuecomment-1924305954

**Comment by severo** [comment]
Impact:

```
db.cachedResponsesBlue.countDocuments({error_code: "DatasetModuleNotInstalledError"})
989
db.cachedResponsesBlue.countDocuments({error_code: "DatasetWithScriptNotSupportedError"})
23593
```

**Comment by RitchieP** [comment]
Hi, does this mean that Huggingface's Dataset Viewer will not be supporting custom datasets script in the near future?

**Comment by severo** [comment]
Indeed, we don't plan to support script-based datasets. Is it an issue for you? Feel free to give more details on your usecase.

**Comment by RitchieP** [comment]
I see, it's not a very big issue for me as of now. But I am slowly building a dataset that hopefully someday could scale up, and having Dataset Viewer would benefit other users to better understand the dataset.
