### ISSUE TITLE
Update Poetry to the latest version to align with that of Dependabot

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#2405]
What about aligning Poetry version with the one used by Dependabot (currently 1.7.1)?
- Advantage: we will be able to directly merge the security PRs proposed by Dependabot
- Disadvantage: we will have to align with Dependabot version each time they update their Poetry
  - Poetry installation instructions explain how to install multiple versions in parallel

If we agree on this, I would like to work on this issue.

**Comment by severo** [comment]
yes, ok
