### ISSUE TITLE
Update duckdb to 0.10.0

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2413]
It will be the first version that will ensure backward-compatibility of the .duckdb format

**Comment by severo** [comment]
https://github.com/huggingface/datasets-server/pull/2316#issuecomment-1930065020

> Having API workers that could read both duckdb 0.8 and 0.10 sounds like a bit of a pain actually.
> 
> Maybe it will be easier to add a new job to compute the new indexes, then after some time switch the API to use them once all the indexes are ready and then the old indexes ?

**Comment by severo** [comment]
released: https://duckdb.org/2024/02/13/announcing-duckdb-0100

**Comment by albertvillanova** [comment]
Happy to see the switch to a backward-compatible version (we could easily update in the future) and also to have the DuckDB file in a different place than the Parquet files.

**Comment by AndreaFrancis** [comment]
From https://github.com/huggingface/datasets-server/pull/2316#issuecomment-1930065020:
> Having API workers that could read both duckdb 0.8 and 0.10 sounds like a bit of a pain actually.
> 
> Maybe it will be easier to add a new job to compute the new indexes, then after some time switch the API to use them once all the indexes are ready and then the old indexes ?

Do you mean to have two parallel job runners? One for the previous version and a new one for 0.10? 
If it is only one for the new one 0.10, search/filter will be available only for the already processed datasets.

wdyt @lhoestq @severo ?

**Comment by severo** [comment]
I think it's two in parallel to make the transition. And we could take the opportunity to store the files elsewhere (not along with the parquet files)

**Comment by AndreaFrancis** [comment]
> I think it's two in parallel to make the transition. And we could take the opportunity to store the files elsewhere (not along with the parquet files)

Let me check if it is possible to have two different versions of the same package in poetry (not sure yet).

**Comment by lhoestq** [comment]
It's probably not possible directly :/

We might need a second python environment and run the indexing in a subprocess using the second python environment.

Or maybe it's possible to install the duckdb cli with the new version and run the indexing in a subprocess simply by calling the cli

**Comment by AndreaFrancis** [comment]
> And we could take the opportunity to store the files elsewhere (not along with the parquet files)

Also related to https://github.com/huggingface/datasets-server/issues/1694#issuecomment-1737010286
and see internal discussion on Slack: https://huggingface.slack.com/archives/C067U56EQBB/p1701174059111469
Also: https://huggingface.slack.com/archives/C0311GZ7R6K/p1686665484050679
Do you think pushing index files to a new revision is okay? (refs/converts/duckdb) @lhoestq @severo  @julien-c @gary149  
If so, we will need a new app token + user for uploading the duckdb index files or give the existing user https://huggingface.co/parquet-converter the permissions to refs/converts/duckdb.

**Comment by AndreaFrancis** [comment]
> I think it's two in parallel to make the transition. 

@huggingface/datasets-server Just as an open concern, currently "split-duckdb-index" has other steps that depends on it like config-duckdb-index-size, split-is-valid, dataset-duckdb-index-size, config-is-valid, dataset-is-valid, dataset-hub-cache. Not sure if we will handle also parallel responses for it or maybe just wait to the new job runner to compute all cache entries and then "refresh" all children steps (Which could be simpler since all processing steps are light).

@lhoestq  Also in regards to https://github.com/huggingface/datasets-server/pull/1296#issuecomment-1602596876, is it a good opportunity to add a version attribute to the new split-duckdb cache records? I think yes.

**Comment by severo** [comment]
> Also in regards to https://github.com/huggingface/datasets-server/pull/1296#issuecomment-1602596876, is it a good opportunity to add a version attribute to the new split-duckdb cache records? I think yes.

I think it's a good idea. We already have it indirectly through the job runner version, but not in the content itself (ie: not in the API response)

**Comment by lhoestq** [comment]
> @lhoestq Also in regards to https://github.com/huggingface/datasets-server/pull/1296#issuecomment-1602596876, is it a good opportunity to add a version attribute to the new split-duckdb cache records? I think yes.

good idea !

> Not sure if we will handle also parallel responses for it or maybe just wait to the new job runner to compute all cache entries and then "refresh" all children steps (Which could be simpler since all processing steps are light).

refreshing all the children steps should be fine indeed
