### ISSUE TITLE
"Errors to retry" only retried once a day

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2439]
It's strange: `JobManagerCrashedError` is listed in the errors to retry, but I witnessed a dataset where it was not retried (`failed_runs: 0`, no jobs).

See discussion opened here: https://huggingface.co/datasets/Samuel-Martineau/kryptik/discussions/1

<img width="1485" alt="Capture d’écran 2024-02-12 à 12 53 36" src="https://github.com/huggingface/datasets-server/assets/1676121/5df7efeb-593c-43e0-b920-7c4918805756">

**Comment by severo** [comment]
OK, it's a very small proportion of the cases: only the ones from today. They will be retried in the daily backfill. 

```
db.cachedResponsesBlue.countDocuments({error_code: "JobManagerCrashedError", "details.copied_from_artifact": {$exists: false}})
4800
db.cachedResponsesBlue.countDocuments({error_code: "JobManagerCrashedError", "details.copied_from_artifact": {$exists: false}, failed_runs: 0})
32
db.cachedResponsesBlue.find({error_code: "JobManagerCrashedError", "details.copied_from_artifact": {$exists: false}, failed_runs: 0}).sort({updated_at: 1}).limit(1)
...
  updated_at: 2024-02-11T23:15:54.489Z }
```

**Comment by severo** [comment]
The errors to retry are:

```
ERROR_CODES_TO_RETRY = {
    "ConnectionError",
    "CreateCommitError",
    "ExternalServerError",
    "JobManagerCrashedError",
    "LockedDatasetTimeoutError",
    "StreamingRowsError",
}
```

They are retried only in the daily backfill.

I think we should check in `finish_job()`, to retry them (create a new job) immediately if needed. Otherwise, it's unclear for the user.

**Comment by severo** [comment]
The original dataset is not public anymore. Here was my comment in the discussion @Samuel-Martineau.

> For some reason, we're not able to generate the Parquet files from your dataset, and the worker crashes.
> 
> I opened an issue on a related bug (https://github.com/huggingface/datasets-server/issues/2439): we should retry earlier in case of crash. But anyway, I did it manually on your dataset and it still crashes. Maybe @albertvillanova @lhoestq have more clues about why the worker is crashing, and what could be done to fix it?

**Comment by Samuel-Martineau** [comment]
Hi, thanks for your quick response. I deleted the dataset, as I only needed it to test a few things about Hugging Face. If you believe it would help if it were back online, I can do that tonight.

**Comment by severo** [comment]
No, not needed. Feel free to open a discussion if you encounter another issue with your datasets.

**Comment by severo** [comment]
Another example: https://huggingface.co/datasets/CohereForAI/aya_collection/discussions/7

**Comment by severo** [comment]
On the other hand, it helps in case of temporary failure of the Hub: if we retry immediately until reaching the maximum number of retries, we will always stay with an error.
With the current implementation, we wait one day between two retries. The conditions that allowed the failure might have changed, and we might end up with a success that time.

**Comment by severo** [comment]
A (lot too complex) alternative would be to allow the user to re-run the missing steps from the UI, as in GitHub's CI with failed jobs.

**Comment by severo** [comment]
Another alternative would be to create a new cron job, run every 10m or hour for example, that would only target these error codes and try to backfill the affected datasets. It would concern only a fraction of the datasets, and thus should only take a fraction of the 6h required for the daily backfill
