### ISSUE TITLE
Remove the parallel steps?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2473]
I think it would be simpler to delete the concept of "parallel" steps.

Currently, we have two pairs of parallel steps:

1. `config-split-names-from-streaming` and `config-split-names-from-info`
2. `split-first-rows-from-streaming` and `split-first-rows-from-parquet`

It generates some complications:
- we don't want to store them both, in particular, the first-rows that have the heaviest content in the database
- the responses can be incoherent (see https://github.com/huggingface/datasets-server/issues/2460)
- it implies specific handling in the code (see `parallel_step_names` in the code)

The parallel steps are currently used to try to get a quick response from streaming the dataset, when it's faster than converting to parquet. But we should always trust the parquet ones more than the streaming ones. Also: computing from parquet (once we have parquet files) is super fast, while it can take some time from streaming.

So, I propose:

- to remove the concept of parallel steps (and raise an error if a processing graph has parallel steps)
- to have a conditional in the unique implementation of `config-split-names` and `split-first-rows`: use parquet/info preferentially, else use streaming
- (note: we have to ensure we don't have concurrency issue, and we always end up with the parquet version when possible, not the streaming one)

What do you think @huggingface/datasets-server?

**Comment by severo** [comment]
For 

> (note: we have to ensure we don't have concurrency issue, and we always end up with the parquet version when possible, not the streaming one)

one way would be to keep the parallel steps, and add a third step, that copies the parquet version if possible, else the streaming one...

But it would end up with 3x the storage, which is not a good idea, I think.

**Comment by lhoestq** [comment]
I didn't know we were storing first-rows twice. IIRC only one was computed and the other would get "AlreadyComputedError"

Anyway no need to work on this imo. It sounds like an optimization that doesn't matter that much right now

> Also: computing from parquet (once we have parquet files) is super fast, while it can take some time from streaming.

The `split-first-rows-from-streaming` part is sometimes faster. We get the results faster for big datasets, instead of waiting for 5GB of data to be converted.

**Comment by severo** [comment]
> I didn't know we were storing first-rows twice. IIRC only one was computed and the other would get "AlreadyComputedError"

yes, we're only storing it once.

> The split-first-rows-from-streaming part is sometimes faster. We get the results faster for big datasets, instead of waiting for 5GB of data to be converted.

Sure, otherwise we would not have created it. What I meant is that we don't compute from parquet if streaming already exists, but doing so would not add too much computation cost as it's fast.

> Anyway no need to work on this imo. It sounds like an optimization that doesn't matter that much right now

hmmm, maybe, maybe not. It would simplify the logic, hence the maintenance. And it would fix https://github.com/huggingface/datasets-server/issues/2460 that cannot be fixed otherwise, I think (order + type of the columns).

---

For

> (note: we have to ensure we don't have concurrency issue, and we always end up with the parquet version when possible, not the streaming one)

another way is to handle this way in the job runner:
1. if "parquet" exists, use it to create the entry. Then store it unconditionally.
2. else: use "streaming" to create the entry. But before storing it, ensure it has not been updated successfully meanwhile (ie. store it + create children jobs only if we replace an error or missing entry with a successful one).

**Comment by AndreaFrancis** [comment]
I like Sylvain's idea:

> to have a conditional in the unique implementation of config-split-names and split-first-rows: use parquet/info preferentially, else use streaming

Having unique job runners that first will try one source and if error, will try the second one (parquet/streaming).
Migration could be kind of simpler because we have to remove all entries with "AlreadyComputedError" and then rename all -from-streaming/from-parquet to only split-names or first-rows (And for sure stop workers when deploying).

**Comment by severo** [comment]
> Having unique job runners that first will try one source and if error, will try the second one (parquet/streaming).

hmmm, you're right, it's even simpler than what I expected. The job runner "just" has to try computing from parquet, and if not available, do it from streaming. That's it
