### ISSUE TITLE
 `config-parquet-and-info` crashes with OOM at pq files validation, presumably when there are a lot of files

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets-server#2552]
[bigcode/the-stack-v2](https://huggingface.co/datasets/bigcode/the-stack-v2) keeps failing at config-parquet-and-info step and seems that the problem is that there are too many parquet files to validate (there are about 1k of them). 

It [starts](https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/config/parquet_and_info.py#L645) [ `retry_and_validate_get_parquet_file_and_size`](https://github.com/huggingface/datasets-server/blob/main/services/worker/src/worker/job_runners/config/parquet_and_info.py#L651): 

![image](https://github.com/huggingface/datasets-server/assets/16348744/a88733c6-145a-4bae-b6b3-8980e33b5d00)

and then fails with OOM in about a minute:

![image](https://github.com/huggingface/datasets-server/assets/16348744/bc8d7221-fa0a-4ff1-84c1-513b5e1ebc6e)

See also https://github.com/huggingface/datasets-server/pull/2544 which didn't help.

Note that [bigcode/the-stack-v2-dedup](https://huggingface.co/datasets/bigcode/the-stack-v2-dedup) which is about 2-4 times smaller works at this step.

cc @anton-l

**Comment by severo** [comment]
Could we refresh other datasets with the same issue (crash in config-parquet-and-info)?

Let me know if you want me to take care of it

**Comment by polinaeterna** [comment]
@severo hm i don't know if we can easily find datasets with this specific issue because it happens when there are a lot of parquet files to read the metadata from (for example, the-stack-v2 has 1k parquet files) and it doesn't raise any specific error but `missing heartbeats`. and we don't have that many datasets like this. for comparison - [the-stack-v2-dedup](https://huggingface.co/datasets/bigcode/the-stack-v2-dedup) is ~3x smaller but still there are many files - assume 300 - and it worked fine.

but if we have resources we can try to refresh all `missing heartbeats` and see maybe something will work, why not

**Comment by severo** [comment]
as of today:
<img width="310" alt="Capture d’écran 2024-03-12 à 15 33 06" src="https://github.com/huggingface/datasets-server/assets/1676121/9f18b269-2b52-4cc5-83f1-c017b4704817">

If it will fix 95% of them, I would be ok to refresh them. If it will fix 5% of them, I think it's not worth it. What do you think?

**Comment by AndreaFrancis** [comment]
Maybe do it incrementally, we currently have { _id: { kind: 'config-parquet-and-info' }, count: 442 } with JobManagerCrashedError (Launch first 50 will let us know if it helps or not)

**Comment by severo** [comment]
Yes, good idea. Do you want to take care of it?

**Comment by AndreaFrancis** [comment]
Yes, I can refresh them. I will let you know if the number of crashes decreases.

**Comment by AndreaFrancis** [comment]
Well, it reduced only 77 datasets. Now we have 365 with JobManagerCrashedError.
