### ISSUE TITLE
The API is broken when passing a cookie + 2FA enabled

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2572]
All the API calls from my main browser (such as https://datasets-server.huggingface.co/splits?dataset=mnist) fail with

```json
{"error":"Unexpected error."}
```

The underlying logs are:

```
INFO: 2024-03-11 22:38:50,327 - httpx - HTTP Request: GET https://huggingface.co/api/datasets/mnist/auth-check "HTTP/1.1 302 Found"
INFO:     10.0.95.34:60730 - "GET /splits?dataset=mnist HTTP/1.1" 500 Internal Server Error
```

Related to https://github.com/huggingface/datasets-server/issues/2377.

It only appears from my main browser, where I'm logged in on huggingface.co. Private browsing, curl, or another browser fixes the issue.

**Comment by severo** [comment]
I don't understand why we get 302 on https://huggingface.co/api/datasets/mnist/auth-check... I don't reproduce, and I can't find corresponding code in moon-landing.

**Comment by severo** [comment]
I don't reproduce either from a services/api pod:

```
>>> b = httpx.get("https://huggingface.co/api/datasets/mnist/auth-check", follow_redirects=False)
>>> b
<Response [200 OK]>
```

**Comment by severo** [comment]
OK, I don't reproduce from another browser, or from curl. So: the issue must be that I pass my cookie when trying to open https://datasets-server.huggingface.co/splits?dataset=mnist from a tab of my browser...

Reducing the priority, since it's not that important.

**Comment by severo** [comment]
I think the issue is that I have 2FA enabled, and in this case (2FA enabled + cookie passed), the request is redirected to a two-factor verification page.

I don't think we can handle this in datasets-server.

cc @coyotte508 for visibility, and maybe to confirm if this is the issue.

**Comment by severo** [comment]
Maybe it's better to remove the support for cookie authentication: https://github.com/huggingface/datasets-server/issues/1011

**Comment by coyotte508** [comment]
cc @Kakulukian for viz
