### ISSUE TITLE
Incoherencies with types for descriptive statistics?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2573]
https://datasets-server.huggingface.co/statistics?dataset=mstz/wine&config=wine&split=train

gives:

<img width="329" alt="Capture d’écran 2024-03-12 à 00 21 12" src="https://github.com/huggingface/datasets-server/assets/1676121/b196a35e-485a-4dfd-8437-b1a7006777de">

but normally, all the categorical columns should include the fields `no_label_count` and `no_label_proportion` (they are not optional in the type: 

https://github.com/huggingface/datasets-server/blob/84c5e3bdb01c931c2766441efb3d63708b707abd/services/worker/src/worker/job_runners/split/descriptive_statistics.py#L80-L86

<img width="367" alt="Capture d’écran 2024-03-12 à 00 21 35" src="https://github.com/huggingface/datasets-server/assets/1676121/107ce615-ab39-4500-83bd-57497ccaa2e6">

---

I don't remember, but I imagine that we didn't want to recompute the cache entries when we added these two fields, and that's why we still have old entries without these two fields.

I think we should put them as optional in the types, until we fix all the cache entries.

**Comment by severo** [comment]
cc @polinaeterna for viz

**Comment by severo** [comment]
btw, it's already correct in the code:

- openapi.json puts the two fields as optional, because we can get both cases when fetching an entry from the database
- the types in services/worker are not optional because the new entries have the two fields

**Comment by severo** [comment]
OK. Closing, as we don't want to recompute all the stats just for that, and there is no incoherencies in the types. I'll add a comment in the openapi spec, to be sure

**Comment by polinaeterna** [comment]
oops yes i remember that i recomputed some entries after adding `no_label_*` fields but not all that have ClassLabel feature and i don't remember why. in theory we can recompute I think, there are not too many datasets with ClassLabel
