### ISSUE TITLE
Cells are marked as truncated whereas they're not

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2586]
See https://datasets-server.huggingface.co/first-rows?dataset=HuggingFaceH4/deita-6k-v0-sft&config=default&split=train_sft

<details><summary>JSON response</summary>
<pre>
{
  "dataset": "HuggingFaceH4/deita-6k-v0-sft",
  "config": "default",
  "split": "train_sft",
  "features": [
    {
      "feature_idx": 0,
      "name": "prompt",
      "type": { "dtype": "string", "_type": "Value" }
    },
    {
      "feature_idx": 1,
      "name": "prompt_id",
      "type": { "dtype": "string", "_type": "Value" }
    },
    {
      "feature_idx": 2,
      "name": "messages",
      "type": [
        {
          "content": { "dtype": "string", "_type": "Value" },
          "role": { "dtype": "string", "_type": "Value" }
        }
      ]
    }
  ],
  "rows": [
    {
      "row_idx": 0,
      "row": {
        "prompt": "I want to learn store Procedure, Can you teach me from the basic .",
        "prompt_id": "100cfc5f4d14b9c640cac30ebb28d0f91f2dc7662e9a578a544923a48fd5a59f",
        "messages": [
          {
            "content": "I want to learn store Procedure, Can you teach me from the basic .",
            "role": "user"
          },
          ...
    },
    {
      "row_idx": 9,
      "row": {
        "prompt": "\"Act as business consultant. Prepare a content for thirty slides about ageism for business training.",
        "prompt_id": "994c40cee21a1e60e11fb326a41999f05079bd568681c6066efe83660e91fd83",
        "messages": "[{\"content\":\"Act as business consultant. Prepare a content for thirty slides about ageism for busine"
      },
      "truncated_cells": ["prompt", "messages"]
    }
  ],
  "truncated": true
}
</pre></details>

The cells `prompt` and `messages` are always listed in `truncated_cells`, whereas they are not always truncated. For example, they are not truncated in cell 0.

```json
   {
      "row_idx": 0,
      "row": {
        "prompt": "I want to learn store Procedure, Can you teach me from the basic .",
        "prompt_id": "100cfc5f4d14b9c640cac30ebb28d0f91f2dc7662e9a578a544923a48fd5a59f",
        "messages": [
          {
            "content": "I want to learn store Procedure, Can you teach me from the basic .",
            "role": "user"
          },
          ...
        ],
      "truncated_cells": ["prompt", "messages"]
    }
```

In cell 9, they are:

```json
    {
      "row_idx": 9,
      "row": {
        "prompt": "\"Act as business consultant. Prepare a content for thirty slides about ageism for business training.",
        "prompt_id": "994c40cee21a1e60e11fb326a41999f05079bd568681c6066efe83660e91fd83",
        "messages": "[{\"content\":\"Act as business consultant. Prepare a content for thirty slides about ageism for busine"
      },
      "truncated_cells": ["prompt", "messages"]
    }
```

**Comment by severo** [comment]
possibly introduced with https://github.com/huggingface/datasets-server/pull/2543

**Comment by severo** [comment]
It causes an issue on the Hub (`[object Object]`): https://github.com/huggingface/moon-landing/issues/9264

<img width="1036" alt="Capture d’écran 2024-03-14 à 11 43 54" src="https://github.com/huggingface/datasets-server/assets/1676121/4b4a95df-99a4-459c-ae3d-30d7d4369143">

**Comment by lhoestq** [comment]
Fixed at https://huggingface.co/datasets/HuggingFaceH4/deita-6k-v0-sft
![image](https://github.com/huggingface/datasets-server/assets/42851186/f8a68238-c723-4776-be7c-fef2eead8d57)

**Comment by severo** [comment]
awesome!
