### ISSUE TITLE
Add transformed columns (audio, image, string, lists) to duckdb file

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets-server#2648]
To support filtering for columns that are stored as bytes (audio; image - when it' implemented), we need to store the transformed values that are used for stats computation. For example, for audio we should store their duration as a separate numerical column. We can also store other columns that require any other transformation, so that we don't do this on the fly. Currently it's length for string and list columns. 

That would require recomputing of all the `duckdb.index` file so we should probably implement this after image statistics.

**Or** if recomputing all index files is not feasible, I imagine we can create a separate duckdb file for all transformed values. But this is an additional layer of complexity (additional job runner, additional file to download during filtering).

**Comment by severo** [comment]
> if recomputing all index files is not feasible
I think it's feasible

**Comment by polinaeterna** [comment]
done in https://github.com/huggingface/dataset-viewer/pull/2737
