### ISSUE TITLE
Provide statistics on a split column

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#376]
- continuous:
  - distribution / histogram
  - mean
  - median
  - standard deviation
  - range (min/max)
- discrete:
  - list of values (with frequency) if not too many 
  - number of unique values

**Comment by meg-huggingface** [comment]
Just to connect the dots, we cover some of this in the data measurement work as well.
https://huggingface.co/spaces/huggingface/data-measurements-tool
Blog post explaining more: https://huggingface.co/blog/data-measurements-tool

**Comment by severo** [comment]
Related issue on moon-landing (internal) to integrate the statistics to the dataset viewer: https://github.com/huggingface/moon-landing/issues/3260
