### ISSUE TITLE
Making repo private and public again makes dataset preview unavailable

### ISSUE THREAD

**Issue by osanseviero** [huggingface/datasets-server#380]
I get a Server error "Unauthorized"

Slack discussion https://huggingface.slack.com/archives/C0311GZ7R6K/p1655366487928519

**Comment by severo** [comment]
I'll try to create e2e tests for these use cases and fix them for good. I thought it had been fixed with the previous commits.

**Comment by severo** [comment]
In the cache database, `/splits` collection, there are no entries for `esc-bench/esc-diagnostic-dataset`, `esc-bench/esc-diagnostic-backup` or `polinaeterna/diagnostic`.

Note: all these datasets are gated.

Maybe the datasets server never received the webhooks for some reason.

Also: even if we fix the webhook, we might want to automatically try to refresh the cache in this case.

**Comment by severo** [comment]
Manually launched:

```
curl -X POST https://datasets-server.huggingface.co/webhook -H 'Content-Type: application/json' -d '{"event": "update", "repo": {"type": "dataset", "name": "esc-bench/esc-diagnostic-dataset"}}';
```

to refresh the cache, but it has created no job, and the cache has remained empty. It must be an issue in the webhook handler in the API service

**Comment by severo** [comment]
Recovering:
<img width="799" alt="Capture d’écran 2022-10-25 à 17 51 57" src="https://user-images.githubusercontent.com/1676121/197821866-8a327976-978a-4052-a9df-ae12bbd4846a.png">

**Comment by severo** [comment]
Done. Note that something seems to be broken on the spgispeech config: https://huggingface.co/datasets/esc-bench/esc-diagnostic-dataset/viewer/spgispeech/other


<img width="1540" alt="Capture d’écran 2022-10-25 à 19 42 00" src="https://user-images.githubusercontent.com/1676121/197844435-b306eef2-de54-4eb4-b376-66ed66af3e5d.png">
