### ISSUE TITLE
Enable the private datasets

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#39]
The code is already present to pass the token, but it's disabled in the code (hardcoded):

https://github.com/huggingface/datasets-preview-backend/blob/df04ffba9ca1a432ed65e220cf7722e518e0d4f8/src/datasets_preview_backend/cache.py#L119-L120

- [ ] enable private datasets and manage their cache adequately
- [ ] separate private caches from public caches: for authenticated requests, we need to check every time, or at least use a much lower TTL, because an access can be removed. Also: since a hub dataset can be turned private, how should we manage them?
- [ ] add doc. See https://github.com/huggingface/datasets-preview-backend/commit/f6576d5639bcb16fc71bf0e6796f3199124ebf49

**Comment by severo** [comment]
Requested on the forum: https://discuss.huggingface.co/t/the-dataset-preview-has-been-disabled-on-this-dataset/21339/5

**Comment by severo** [comment]
Also here: https://discuss.huggingface.co/t/does-the-rest-api-work-with-private-repo/28987 (to consume the API)

**Comment by beyondguo** [comment]
When to enable the dataset viewer on private datasets? This has been requested for more than a year! lol

**Comment by severo** [comment]
We prioritize other features, such as random access to the rows (#13) and providing statistics on the columns (#376). Enabling private datasets will be very useful, but it requires a lot of care to avoid any leak of private information and the internal structure of the project must be adapted.

**Comment by faustusdotbe** [comment]
Hi! Chiming in to show interest. I completely understand this is not a top priority, but being able to have the viewer in private datasets would be super cool (also as a last final "sanity check" before making the repo public for example).

**Comment by alexgshaw** [comment]
+1 to this feature

**Comment by DavidFarago** [comment]
+1 for this feature

**Comment by arikanev** [comment]
+1

**Comment by TheAnimeGuru** [comment]
+1 This would be very useful

**Comment by nealchandra** [comment]
I see this issue has been tagged as a P2 -- are you able to give us a rough estimate of what that might mean in terms of when it could land?

**Comment by severo** [comment]
No, we will update here when we have an ETA. Meanwhile, see https://github.com/huggingface/datasets-server/issues/39#issuecomment-1373434738

**Comment by Stillerman** [comment]
+1

**Comment by prassanna-ravishankar** [comment]
Is there a way we can explicitly  enable this for "private datasets"(at our own risk) ? At the moment my dataset has to be private, but I am concerned less about leakages etc. Would love to enable it

**Comment by severo** [comment]
> Is there a way we can explicitly enable this for "private datasets"(at our own risk) ?

No, it's not possible at the moment. It is not a replacement, but if it works for you, maybe you can set your dataset as [gated](https://huggingface.co/docs/hub/datasets-gated#gated-datasets): the dataset viewer works with them.

**Comment by severo** [comment]
> What is the strictest possible gating? Can you restrict it to effectively be a private dataset?

It's not the same as private, but if you opt to manually approve the requests to access the gated dataset (https://huggingface.co/docs/hub/datasets-gated#manual-approval), you would avoid giving public access to the data.

**Comment by enoriega** [comment]
+1 to enable dataset viewer on private datasets

**Comment by eduardm** [comment]
+1. As an enterprise user, I don't want to share the dataset publicly, but not having a preview is really frustrating and makes collaboration difficult. Currently, we are creating a tiny dataset (10 rows) and making that public just to have a preview and understand what is what.

**Comment by andreemic** [comment]
+1 for this!

The datasets filtering and sorting UI is very very barebones, so the viewer would help to navigate private datasets a lot

**Comment by severo** [comment]
Also, internal request: https://huggingface.slack.com/archives/C02EMARJ65P/p1702930353945389

**Comment by qionghuang6** [comment]
+1 for viewing private datasets

**Comment by julien-c** [comment]
please continue +1'ing this issue (can be on the OP) so we get a sense for how many people/teams need this! 🙏

**Comment by sutgeorge** [comment]
+1

**Comment by severo** [comment]
Done!

The private datasets are now supported in the datasets-server, enabling the dataset viewer + parquet conversion on the dataset pages.

https://github.com/huggingface/datasets-server/assets/1676121/1670245b-d384-4493-89e3-e712f6e2b102

Note that it's a paid feature, available as of today for [Pro users](https://huggingface.co/subscribe/pro) and [Enterprise orgs](https://huggingface.co/enterprise). Please give us feedback when you try this new feature!

**Comment by faustusdotbe** [comment]
Merci Sylvain !
