### ISSUE TITLE
Publish a parquet file for every dataset on the Hub

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#398]
To be able to apply specific processes as: stats, or random access, we need to first download the datasets on the disk.

Possibly in the parquet format.

One part will be implemented in the `datasets` library, but we also have challenges in the datasets-server project: infrastructure, workers

**Comment by severo** [comment]
### Proposal A

- download a dataset and prepare a parquet file. Supported by datasets since [2.5.0](https://github.com/huggingface/datasets/releases/tag/2.5.0), including sharding, and audio+image files
- commit the parquet file(s):
  - in a dedicated and protected directory, ie: `.hf/parquet/`, or `.hf/data/parquet/`, or `.hf/datasets-server/parquet/`. Note that the datasets library ignores the directories with a dot as the first character.
  - define the filename pattern. For now, it's something like: `csv-train-00000-of-00001.parquet` where `csv` is the loader used by datasets, `train` is the split, `00000-of-00001` is the shard number, and `.parquet` is the extension. We might prefer to use subdirectories for the config and split and avoid the loader, ie: `/default/train/00000-of-00001.parquet`
- and send them to the Hub. 
  - we will wait for a Hugging Face filesystem to be supported in datasets to do so more easily (https://huggingface.co/docs/datasets/filesystems)
  - a dedicated user (ie, `datasets-server-bot`) will be used in order to identify the commits and PRs on the Hub
  - if it's the first time, a pull request will be created, and the reference (`refs/pr/42`) will be stored in the cache database
  - then, the reference will be pulled from the cache database and used to push to the correct PR on the Hub
  - the pull request should remain in the Draft mode so that nobody merges it (even if it's [doable](https://huggingface.co/docs/hub/repositories-pull-requests-discussions#fetching-all-pull-requests-for-git-magicians) manually if the dataset maintainer wants to)
- in the cache database, store:
  - the PR details
  - the path and name of the parquet files, or the path to the parquet files with a placeholder for the shard number and the number of shards
  
### Drawbacks

- the PRs will be "polluted" by a permanent draft PR
- the URL to access the parquet file from the web is not easily forgeable, as one has to identify the PR number: `https://huggingface.co/datasets/severo/test-parquet/resolve/refs%2Fpr%2F<PR_NUMBER>/parquet/csv-train-00000-of-00001.parquet`. We surely will want to give the Hub users an option to download the parquet file/files, so: not having an easy way to identify it can be a problem. An alternative would be to send a query to the datasets server because it stores the details in its cache.
- if the datasets-server cache is erased or broken for some reason, ghost PR will haunt the Hub for decades

### Pros

- we use the existing features of the Hub (PRs)

**Comment by lhoestq** [comment]
Awesome ! :D

What about more meaningful directory names ? Like `.exported/parquet` maybe ?

Getting the parquet URLs can be made easier using `huggingface-hub` utilities in python btw.

In Dask the API would look like
```
import dask.dataframe as dd

dd.read_parquet("hf://<repo_name>/.exported/parquet", storage_options={"repo_type": "dataset"})
```

**Comment by severo** [comment]
> What about more meaningful directory names ? Like `.exported/parquet` maybe ?

much better, I like it

> Getting the parquet URLs can be made easier using huggingface-hub utilities in python btw.

yes, the only problem is `xxx` in `"revision": "refs/pr/xxx"`. You cannot guess what it is, it's not a well-known word, ie `/refs/exported/parquet`, you have to get it manually, or ask datasets-server

**Comment by severo** [comment]
Some more notes:
- let's start with the current filenames (`csv-train-00000-of-00001.parquet`), but create one subdirectory per config. It's how it's managed in the datasets cache btw.
- to make it easier to iterate on the shards, the user might use huggingface_hub to get the list of files. But I imagine it's a lot simpler if we create a datasets-server endpoint to get all the infos about the parquet file(s): /parquet?dataset=dataset&config=config&split&split, which returns a list of all the shards URL
- the git workflow will surely be: from main, add a parquet, then `push --force` to the PR: it makes it a lot simpler than merging or rebasing the PR, and it will also delete the previous parquet files on the server which helps saving storage

**Comment by lhoestq** [comment]
if push --force is not available (as it is the case in `download_and_prepare`) it's fine to just upload the new files and keep the old ones in the git history for now

**Comment by julien-c** [comment]
Counter proposal on Hub-side is here: https://github.com/huggingface/moon-landing/pull/4311#issuecomment-1293659237 

😎😎

**Comment by severo** [comment]
Is it OK if we store the parquet file(s) in `.convert/parquet/` for consistency with the git reference (`/refs/convert/parquet`)?

**Comment by lhoestq** [comment]
Since it's not a PR - I'm fine with having them at the root

**Comment by severo** [comment]
Hmmm, as it's a git reference, I imagine it should share the same history as the main branch. Should we delete all the files and put them in the root path? Or put them in a reserved path as I proposed above?

**Comment by severo** [comment]
### Proposal B

- download a dataset (from the main branch of the HF repo) and prepare a parquet file. Supported by datasets since [2.5.0](https://github.com/huggingface/datasets/releases/tag/2.5.0), including sharding, and audio+image files
- save the parquet files (the parquet file is divided into shards) in a reserved path, let's say `.hf/convert/parquet/`. This subdirectory is deleted if it existed already, then created.
- ❓ do we save them at the root, or in subdirectories to make it easier to find configs and splits?
- ❓ do we use the default filename pattern? For now, the structure is: `csv-train-00000-of-00001.parquet` where `csv` is the loader used by datasets, `train` is the split, `00000-of-00001` is the shard number, and `.parquet` is the extension
- commit the new files in git locally, using a dedicated org or user (ie, `datasets-server-bot` or `datasets-maintainers`)
- ❓ should we sign the commit? we add this feature later
- push the commit to the git reference `refs/convert/parquet` on the Hub
- ❓ how will we manage these git operations? datasets+hffs? huggingface_hub? other?
- a discussion is created (if it's the first time), or a comment is added to the discussion, with details on how to get the parquet file (git -> `refs/convert/parquet`, HTTP -> `https://huggingface.co/datasets/${DATASET}/resolve/refs%2Fconvert%2Fparquet/.hf/convert/parquet/csv-train-00000-of-00001.parquet`).
- in the cache database, store:
  - the discussion number (or discussion URL)
  - the worker version, and the dataset main git revision, in order to skip jobs if nothing has changed
  - ❓ should we list the path and name of the parquet files? the list can be obtained from the HF Hub API, but 1. I'm not sure the round-trip is needed, 2. on the other end, the source of truth is now the Hub

**Comment by julien-c** [comment]
> - should we sign the commit?
> - how will we manage these git operations?

i think you should use `huggingface_hub.create_commit`, will be more scalable then git for this... and commits will be signed by default (I think? not sure here actually...)

**Comment by severo** [comment]
Done with #651
