### ISSUE TITLE
Shuffle the rows?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#430]
see https://github.com/huggingface/moon-landing/issues/3375

**Comment by lhoestq** [comment]
I think it would be nice to have an endpoint to get random samples from the dataset instead

**Comment by severo** [comment]
P2 label should have prevented the stale bot from closing the issue. Fixed with #1635.

**Comment by lhoestq** [comment]
actually closing this one now that the viewer has pagination + search it's easy to explore more random samples of the dataset
