### ISSUE TITLE
Kubernetes pods crash for various reasons

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#526]
Until now, I've seen:
- `ContainerStatusUnknown`
- `Error`
- `OOMKilled`
- `OutOfcpu`
- `OutOfmemory`

It would be good to understand why every error occurs, and try to avoid it.

We delete them with:

```bash
k get pod | grep -e ContainerStatusUnknown -e Error -e OutOfmemory  -e OutOfcpu -e OOMKilled | cut -d ' ' -f 1 | xargs -I % kubectl delete pod/% --force
```

**Comment by AndreaFrancis** [comment]
Many pods for prod-datasets-server-worker-all are crashing with error 

-     ContainerStatusUnknown
-     Error
-     OOMKilled

Re-opening this issue to track reasons.
The only log I could see is:
```
Defaulted container "prod-datasets-server-worker" out of: prod-datasets-server-worker, prepare-assets (init), prepare-cache (init), prepare-parquet-metadata (init), prepare-duckdb-index (init)
unable to retrieve container logs for containerd://6b05b517783eaa1d2e1ca99752d90d13aff416f0dd5a82d0804892fd46c3b3d6 

```

**Comment by severo** [comment]
I don't see these errors anymore, since we have stopped overcommitting the RAM (ie. now, we directly assign the max RAM to the workers, so: the node doesn't run out of memory unexpectedly). Let's keep it open for some time, until we confirm the issue is fixed.

**Comment by severo** [comment]
Not occurring anymore
