### ISSUE TITLE
Dataset Viewer issue for nlphuji/winogavil

### ISSUE THREAD

**Issue by yonatanbitton** [huggingface/datasets-server#587]
### Link

https://huggingface.co/datasets/nlphuji/winogavil

### Description

The dataset viewer is not working for dataset nlphuji/winogavil.

Error details:

```
Error code:   UnexpectedError
Type is not JSON serializable: PngImageFile
```

**TLDR**: Is there an option to ignore a specific dataset field *only* in the Dataset Viewer, and to keep it as the part of the dataset otherwise? 

My dataset includes a field named "candidates" which is a list of strings, where each string is a filename reference. 
In the process script ([here](https://huggingface.co/datasets/nlphuji/winogavil/blob/main/winogavil.py#L116)) I transform each of the filenames to a png. 

This code:
```python
winogavil = load_dataset("nlphuji/winogavil", use_auth_token=auth_token)["test"]
print(winogavil[0]['candidates'])
print(winogavil[0]['candidates_images'])
```
returns the following:
```python
['eagle', 'teepee', 'factory', 'metal', 'ash']
[<PIL.PngImagePlugin.PngImageFile image mode=RGB size=2384x2384 at 0x7F6ABC6AA2D0>, <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1500x1500 at 0x7F6ABC6AA390>, <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1400x1400 at 0x7F6ABC6AAA50>, <PIL.PngImagePlugin.PngImageFile image mode=RGB size=2400x2400 at 0x7F6ABC6AAA10>, <PIL.PngImagePlugin.PngImageFile image mode=RGB size=900x900 at 0x7F6ABC6AA4D0>]
```

This is the intended use for my dataset, and the only gap is that it does not work in the Dataset Viewer.

Ideally, it will show each image name as string, and have an option to "click" it and to show image. 

- Do you have a support for a list of images in the Dataset Viewer?
- If not, is there an option just to eliminate the "candidate_images" field ONLY in the viewer, and keep it as a part of the dataset (with load_dataset)?

[This colab](https://colab.research.google.com/drive/19qcPovniLj2PiLlP75oFgsK-uhTr6SSi?usp=sharing) shows a usage example for my dataset with huggingface, if that helps. 

I managed to reach a solution by defining it as a list of strings rather than images:

```python
#"candidates_images": [img]
"candidates_images": [datasets.Value("string")]
```

It means that this field will hold the strings and the dataset user will need to read it to an image object. 

Now `['candidates_images'][0]` is
`'/root/.cache/huggingface/datasets/downloads/extracted/0d79b7f800bd172835f30786bdc7e6b20178375a9b927086b7f1ce0af27d63d4/winogavil_images/eagle.jpg'`
And its possible to read it with Pillow.Image.open

This solution is fine with me, but I am wondering if there is a better solution. 

Thanks!

**Comment by severo** [comment]
Thanks for reporting, it's a bug indeed.
Note that we already thought of the case, see

https://github.com/huggingface/datasets-server/blob/dbd54ee1c41a25ccb86fd8a9ac0ce704da18a63c/services/worker/src/worker/features.py#L102-L104

We should return a list of image URLs, and show them in the dataset viewer.

**Comment by yonatanbitton** [comment]
Thanks for the response. Is it going to be fixed? If so, i'll revert it to be a list of images instead of a list strings, whenever the change occurs.

**Comment by severo** [comment]
Yes, I'm working on it. I'll ping you when it's deployed so that you can revert.

**Comment by severo** [comment]
#592 fixes the error. The `/first-rows` now returns a list of image URLs:

https://datasets-server.huggingface.co/first-rows?dataset=severo/winogavil&config=TEST&split=test

<img width="1034" alt="Capture d’écran 2022-09-27 à 16 56 02" src="https://user-images.githubusercontent.com/1676121/192561555-52a8d1d4-bef2-4f62-8d19-1dd67d503321.png">

For the moment, the dataset viewer on the Hub does not support lists of images, thus shows the JSON content of the cell.

https://huggingface.co/datasets/severo/winogavil/viewer/TEST/test

<img width="743" alt="Capture d’écran 2022-09-27 à 16 55 39" src="https://user-images.githubusercontent.com/1676121/192561562-44091871-cefc-49a8-b14a-b5d2033c0d06.png">

I'll be working on updating the dataset viewer on the Hub.

@yonatanbitton you should already be able to switch back to the previous version of the dataset and see the contents of the dataset.

**Comment by yonatanbitton** [comment]
Thank you very much @severo. 

I've tried to revert back, but received another problem when I tried to filter:
`winogavil_specific_num_candidates = winogavil.filter(lambda example: example['num_candidates'] == NUM_CANDIDATES)
`
This line took too long and crushed several times. 
I thought it was because the dataset held images instead of image paths (which is heavier structure), and when I reverted back to list of image paths it was fixed. Therefore I now again hold a list of image paths and it's fine with me.  

I think we can close it. Thank you.

**Comment by severo** [comment]
Hi @yonatanbitton: we now support the lists of images in the dataset viewer, see https://huggingface.co/datasets/severo/winogavil for example (it's one commit behind your repository)

<img width="1142" alt="Capture d’écran 2022-10-10 à 10 47 44" src="https://user-images.githubusercontent.com/1676121/194829116-18abda76-1d3b-4e80-a763-20b0eed729bb.png">

Feel free to update your repository if you want to show the images in the viewer.

Thanks again for raising the issue.

**Comment by yonatanbitton** [comment]
Hi again. I am using the images list which is great. However, the problem I reported in the Sep 27 still occurs. I suspect that the data is contained in a non-lazy structure which make it take too much RAM (and eventually crush) when trying to work with it. 
For example, even trying to convert the dataset to dataframe takes too long and crushes. 
Is there an option to check it? 

I'm currently using this notebook: https://colab.research.google.com/drive/19qcPovniLj2PiLlP75oFgsK-uhTr6SSi#scrollTo=lLl0AXq9f5jB
You can reproduce the error by trying to filter 
`winogavil_specific_num_candidates = winogavil.filter(lambda example: example['num_candidates'] == 12)
`
Or by converting it to a dataframe.
Thanks!

**Comment by severo** [comment]
As https://github.com/huggingface/datasets-server/issues/587#issuecomment-1328171254 is not directly related to this issue anymore, maybe you could open a new issue in https://github.com/huggingface/datasets/ instead, or create a discussion in your repo https://huggingface.co/datasets/nlphuji/winogavil/discussions. cc @albertvillanova
