### ISSUE TITLE
Dataset Viewer issue for will33am/Caltech101

### ISSUE THREAD

**Issue by williamberrios** [huggingface/datasets-server#588]
### Link

https://huggingface.co/datasets/will33am/Caltech101

### Description

The dataset viewer is not working for dataset will33am/Caltech101.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Thanks for reporting, it's a bug on our side, the data are available:

https://datasets-server.huggingface.co/first-rows?dataset=will33am/Caltech101&config=will33am--Caltech101&split=train

<img width="662" alt="Capture d’écran 2022-09-26 à 10 40 43" src="https://user-images.githubusercontent.com/1676121/192232238-2eca35a7-1b8d-472f-93f2-30c32d4b1802.png">

but we fail to show it in the dataset viewer on the Hub:

https://huggingface.co/datasets/will33am/Caltech101/viewer/will33am--Caltech101/train

<img width="638" alt="Capture d’écran 2022-09-26 à 10 40 02" src="https://user-images.githubusercontent.com/1676121/192232049-329919c1-0d87-4544-a2b6-dea3c101df4f.png">

Note: possibly a good hotfix would be to set the feature type of the `image` column to [Image](https://huggingface.co/docs/datasets/image_dataset). The current feature type is:

<img width="246" alt="Capture d’écran 2022-09-26 à 10 42 10" src="https://user-images.githubusercontent.com/1676121/192232806-16cf3475-906e-433e-af66-c4df907c535b.png">

Cc @albertvillanova @mariosasko

**Comment by severo** [comment]
Note: possibly it is due to the `decode=True` parameter of the `Image` column. The current feature type is:

<img width="246" alt="Capture d’écran 2022-09-26 à 10 42 10" src="https://user-images.githubusercontent.com/1676121/192232806-16cf3475-906e-433e-af66-c4df907c535b.png">

Reproduction:

```python
>>> from datasets import load_dataset
>>> ds = load_dataset("will33am/Caltech101", streaming=True)
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 788/788 [00:00<00:00, 812kB/s]
Using custom data configuration will33am--Caltech101-f7ef236142ecf4a5
>>> ds["train"].features
{'id': Value(dtype='int64', id=None), 'image': Image(decode=True, id=None), 'label': Value(dtype='string', id=None)}
```

**Comment by severo** [comment]
I refreshed the cache for the dataset, and it works now as expected. I'm not sure what occurred.

https://huggingface.co/datasets/will33am/Caltech101/viewer/will33am--Caltech101/train

<img width="1233" alt="Capture d’écran 2022-09-26 à 10 57 21" src="https://user-images.githubusercontent.com/1676121/192235889-1c838a09-7165-4016-8b21-b260c4897895.png">
