### ISSUE TITLE
tensorflow-io-gcs-filesystem build issue on M1

### ISSUE THREAD

**Issue by dtaivpp** [huggingface/datasets-server#590]
Wondering if anyone is building and developing this on an M1/2 Machine. At the moment I am running into the following issue. `tensorflow-io-gcs-filesystem` is not currently available on macOS with the M1. Normally this wouldnt be a problem as you can install it using the following:

```bash
python setup.py -q bdist_wheel --project tensorflow_io_gcs_filesystem
python -m pip install --no-deps dist/<wheel-file-from-last-step>
```

Only issue poetry first removes all the dependencies it seems before attempting to install everything. Is there a workaround for this that you all have seen?

**Comment by severo** [comment]
Unfortunately, I don't have access to a M1/2 Mac, and the installation works without error on Ubuntu and Intel MacOS.
I'll try to find help to reproduce and fix the issue.

**Comment by dtaivpp** [comment]
That's it alright. Is there any way to specify for poetry to build from source or use a prebuilt local package? If so it can be done. Otherwise developing on m1/2 might just be off the table.

**Comment by severo** [comment]
The issue should have been fixed now (after merging https://github.com/huggingface/datasets-server/pull/593). Could you check @dtaivpp?

Also: I wrote some notes about installing on MacOS; I will start working on the docs in the next few days, and I will add them.

**Comment by dtaivpp** [comment]
Lol now I am getting some new errors. I will drop my install notes and see if they match what you have. Now it wants me to install a rust compiler.  🤦‍♂️

**Comment by severo** [comment]
Oh yes, rust is required to install [transformers](https://github.com/huggingface/transformers/), which requires [tokenizers](https://github.com/huggingface/tokenizers/), which uses rust.

I added install notes for MacOS today here: https://github.com/huggingface/datasets-server/blob/main/DEVELOPER_GUIDE.md#mac-os, I hope it helps.
