### ISSUE TITLE
Support package imports in datasets scripts

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets-server#599]
It would be neat if the viewer would work with datasets scripts that have arbitrary package imports (basically, being able to parse the output of `datasets.utils.py_utils.get_imports(dataset_script)` and prepare the env) instead of being constrained to some predefined list of the supported packages. Are there any plans to support that?

**Comment by severo** [comment]
Related: #259

**Comment by severo** [comment]
Already discussed here: https://github.com/huggingface/datasets-server/issues/73#issuecomment-1027766764

> - I wonder if you already thought about letting the maintainers of a dataset define in a requirements.txt file (or pyproject.toml or another file versioned in the dataset repository) the list of dependencies required to run the dataset python script?
> - Hi ! Yes we've already discussed that and this is a good idea indeed :) It wasn't asked a lot though, that's why we haven't implemented it yet
> - Meanwhile, maybe we could try to detect the imports in the datasets scripts, and generate a list of dependencies automatically, right?
> - There is already some code doing that in `datasets.load`

From an internal discussion on Slack: https://huggingface.slack.com/archives/C02V51Q3800/p1643793746471429

**Comment by severo** [comment]
Some thoughts:
- it would reduce the number of dependencies in the Docker image and thus reduce its size and build time
- it would make it easier to support new dependencies (do it in the dataset script, no need to modify the code of datasets-server)

But:
- some dependencies require software installed on the system, for example, `rust`(for tokenizers), `libicu`, `llvm`, `ffmpeg` or `libsoundfile`: they cannot be installed on the fly and must be preinstalled in the docker image. See https://github.com/huggingface/datasets-server/blob/373ef57f4fcaeb0fb7c8ede25ff0a36b8605901f/services/worker/Dockerfile#L17-L33
- it means installing every dependency at runtime, which can be an overhead for the most common dependencies, in comparison with having the dependencies pre-installed.

**Comment by severo** [comment]
Finally, I imagine this feature should be implemented first in the `datasets` library, then supported here, based on the `datasets` implementation.

**Comment by lhoestq** [comment]
I don't think we'll support this in `datasets` - it's bad practice to modify the user's environment at runtime and it can lead to unexpected behaviors/frustration/env breaking

**Comment by severo** [comment]
OK, thanks.

Should we close this issue @lhoestq? Or how do you think we could handle it in the datasets-server?

**Comment by lhoestq** [comment]
I guess we can try and see if it fixes a bunch of datasets without breaking the worker envs ^^

**Comment by mariosasko** [comment]
> some dependencies require software installed on the system, for example, rust(for tokenizers), libicu, llvm, ffmpeg or libsoundfile: they cannot be installed on the fly and must be preinstalled in the docker image. See

We can have special installation routines for such dependencies.

> it means installing every dependency at runtime, which can be an overhead for the most common dependencies, in comparison with having the dependencies pre-installed.

I think we can still have a good portion of dependencies pre-installed.

I just find it cumbersome having to open an issue for each missing dependency and then waiting for it to be added, so if we can automate something, we should IMO.

**Comment by albertvillanova** [comment]
People from BigBIO (https://huggingface.co/bigscience-biomedical) just asked if there could be used an external dependency called `bioc` (and some others): currently the preview does not work for those datasets
- it is widely used in many of their biomedical datasets
- but IMO it is not a dependency we would like to add for all datasets on the Hub

It would be great if users can define a per-repo `requirements.txt` file:
- this could be used by the preview to create the env (or extend the already existing one)
- I agree this should not be done within `datasets.load_dataset`: not a good idea modify the env at run-time

This `requirements.txt` file is telling users: if you would like to load this dataset, then first run `pip install -r requirements.txt`

CC: @galtay

**Comment by severo** [comment]
> EDIT: my suggestion above was based on the assumption that there was a container/image per repo; but @severo just told me that it is the same machine for all datasets... 😅

Sure: for now, it's simpler to add `bioc` to the pre-installed dependencies (the only drawback would be an increase in the size of the image and the CI duration).

But I think it would be nice to have per-dataset dependencies, to avoid creating a PR for every new dependency.

**Comment by galtay** [comment]
thanks for posting this @albertvillanova ! at the moment, this is how the bioc requirement appears in our github repo https://github.com/bigscience-workshop/biomedical/blob/main/setup.cfg#L10

I am currently working on creating a list of things that are preventing some previews for the 123 dataset loaders we recently migrated to the hub (https://huggingface.co/bigscience-biomedical) but really loving the results so far.

**Comment by mariosasko** [comment]
One more situation where this feature would help: https://github.com/huggingface/datasets/pull/5289#issuecomment-1326796321

**Comment by severo** [comment]
Might help if we implement the feature: https://github.com/simonw/til/blob/main/python/call-pip-programatically.md

**Comment by severo** [comment]
I'm still not convinced we should let the script/user add dependencies. Opening again, to allow discussion, but not setting a priority.

**Comment by mariosasko** [comment]
Also requested on Slack here: https://huggingface.slack.com/archives/C01229B19EX/p1690571927151009

**Comment by severo** [comment]
Closing as we won't support script based datasets anyway
