### ISSUE TITLE
[feat req] Alphabetical ordering for splits in dataset viewer

### ISSUE THREAD

**Issue by sanchit-gandhi** [huggingface/datasets-server#614]
### Link

https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0

### Description

Currently, the datasets splits for the viewer are displayed in a seemingly random order, see example for [Common Voice 11](https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0):
<img width="1505" alt="Screenshot 2022-10-21 at 14 04 39" src="https://user-images.githubusercontent.com/93869735/197192381-46ca4041-db69-423e-be55-abf96e70167a.png">

It would be easier to traverse the list of possible splits if they were arranged alphabetically!

**Comment by severo** [comment]
WDYT @huggingface/datasets? We respect the order given by https://github.com/huggingface/datasets/blob/main/src/datasets/inspect.py#L382: is the order of the splits important or not? We generally expect `train` to be the first split, which would not occur with `["train", "test", "eval"]` for example if they were ordered alphabetically.

**Comment by lhoestq** [comment]
The order doesn't matter - you can sort it if you want

**Comment by severo** [comment]
I wonder if we want to manage this on the datasets-server side or on the Hub. And I'm not sure what the strategy should be. For long lists, it seems a good idea to sort alphabetically. For `["train", "test", "eval"]`, I'm not sure if `["eval", "test", "train"]` is better, as an ML process starts with training, etc. and it's surely why the splits in the dataset script were written in this order.

**Comment by polinaeterna** [comment]
maybe sort only configs? it can also be done directly in the script.

**Comment by severo** [comment]
maybe @julien-c or @gary149 want to chime in

**Comment by severo** [comment]
> maybe sort only configs?

yes, it's a good idea @polinaeterna. The splits are generally only 5-6 max, while there are a lot of datasets with a high number of configurations. Alphabetically sorting seems more useful for lists with a large number of items.

**Comment by severo** [comment]
Done with #623 
<img width="1141" alt="Capture d’écran 2022-10-25 à 21 20 52" src="https://user-images.githubusercontent.com/1676121/197863064-521880dd-81d5-4e44-b391-31780cc81d6d.png">

I manually refreshed the cache for https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0/viewer/ab/train, but other datasets will remain with the old order until the cache is invalidated. I don't think it's worth refreshing all the cache just for this.

**Comment by sanchit-gandhi** [comment]
Brilliant, thank you all! 🤗
