### ISSUE TITLE
Handle non-decoded image features

### ISSUE THREAD

**Issue by NimaBoscarino** [huggingface/datasets-server#628]
### Link

https://huggingface.co/datasets/society-ethics/LILA

### Description

The dataset viewer expects images to be PIL images, but since the HF Datasets library allows non-decoded images (with `decode=False`) this is not always the case. At the moment, if an image feature is not decoded, the viewer fails with the following error in the UI:

```
Error code:   RowsPostProcessingError
```

In the backend, the error is:
![image](https://user-images.githubusercontent.com/6765188/199774586-c3fcc202-5c93-48d0-b010-29ca7485c6b6.png)

**Comment by severo** [comment]
If the image has not been decoded (decode=False), we should:
- try to decode it, then apply the normal processing
- if the decoding raises an error, return a new type of error in the dataset viewer, so that the dataset maintainer is able to understand what is not working, and fix the dataset.

Possibly, the same applies to the Audio type.

WDYT @huggingface/datasets?

**Comment by severo** [comment]
Simpler fix: if if the image has not been decoded (decode=False), return the raw content of the cell:
```json
{
  'bytes': None,
  'path': '/root/.cache/huggingface/datasets/downloads/extracted/b0a21163f78769a2cf11f58dfc767fb458fc7cea5c05dccc0144a2c0f0bc1292/train/bean_rust/bean_rust_train.29.jpg'
}
```

The API client must be able to detect that this is the expected content... Looking at how to adapt the API to support this, and for the Audio type too.

**Comment by mariosasko** [comment]
@severo This is the exact format in which the rows are returned when `decode=False` :).

**Comment by severo** [comment]
Yes, I know (copied from the docs). The only issue here is that we would have to change the REST API, to have two formats for the images: decoded and not decoded.

Another option is simply not to support "decoded=False" for images and audios, like it is currently. We might let as is, or raise a specific NotImplemented exception to help debug.

**Comment by lhoestq** [comment]
On this specific case where someone want to check URLs that return 404 before getting the images it makes more sense to have a string URL column anyway, so I would say low prio
