### ISSUE TITLE
Index the (text) datasets contents to enable full-text search

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#629]
See an example by @ola13 on the ROOTS corpus: https://huggingface.co/spaces/bigscience-data/roots-search.

Implementation details are here: https://huggingface.co/spaces/bigscience-data/scisearch/resolve/main/roots_search_tool_specs.pdf

Internal discussion: https://huggingface.slack.com/archives/C0311GZ7R6K/p1667586339997379

**Comment by AndreaFrancis** [comment]
I would love to work in this feature! 
Also I saw the hub already implemented it on https://github.com/huggingface/moon-landing/pull/4971 using `meilisearch`, I will continue with the research and put my finding here.

**Comment by ola13** [comment]
More of a research-oriented solution but check out this. as well: https://arxiv.org/abs/2302.14534 :)

**Comment by AndreaFrancis** [comment]
The API phase can start now that the first phase of FTS has been implemented on https://github.com/huggingface/datasets-server/pull/1296. 
Note that duckdb index files (Initially for those small datasets with parquet files under 100Mb) are being generated and stored in revision "refs/convert/parquet" in the file "index.duckdb". 
So, my proposal is:

1. We need a preparation for FTS (This includes downloading the index file) so, there could be a `POST /fts-prepare` triggered by the hub that will do a couple of actions in datasets-server side:
		- Store an entry in a new mongo collection `"temporal_file"` with 
			- dataset
			- config
			- split
			- location (path of the downloaded file)
			- created_at
			- last_used_at (last date that API used the file to query fts)
		- Download the index file	
2. When requesting a search `GET /fts?q=<query>`
	       - Look for the record in "temporal_file" collection and get the downloaded index location 
		- If exists: connect to db -> with retry mechanism in case another process is connected to the same locked file
		- Return results with pagination
		- Update last_used_at file in "temporal_file" collection
3. To have a k8s Job that runs every X minutes
		- Delete all files whose last_used_at field is more than Y minutes
		- Delete related records in "temporal_file" collection
	

WDYT @huggingface/datasets-server

**Comment by severo** [comment]
I think we can do even simpler:
- on GET /fts?q=<query>, if no local file, download it
- use the path to locate the file (dataset/config/split)
- have a k8s job that deletes the old files (based on the last access date)

**Comment by lhoestq** [comment]
Nice ! 

> -> with retry mechanism in case another process is connected to the same locked file

If you open the db as read-only there shouldn't be any lock no ?

**Comment by AndreaFrancis** [comment]
Closing as this was implemented in two phases:
- Index creation https://github.com/huggingface/datasets-server/pull/1296
- /search endpoint https://github.com/huggingface/datasets-server/pull/1516
