### ISSUE TITLE
Show which files in the datasets are scanned as unsafe

### ISSUE THREAD

**Issue by xiaohk** [huggingface/datasets-server#648]
Hello, HF datasets show that at least one files in [our datasets](https://huggingface.co/datasets/poloclub/diffusiondb) are scanned as unsafe. There are more than 16,000 files in the repo, so it's quite difficult to find which file is scanned as unsafe. It would be great if the warning message tells which file is scanned as unsafe.

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/15007159/203851476-8fbf49ce-988c-4362-98cf-e0ef34d8e4f0.png">

**Comment by julien-c** [comment]
cc @McPatate @krampstudio

**Comment by krampstudio** [comment]
@xiaohk We've made somechanges to the [hub](https://huggingface.co). From now on, we've added links to the suspicious files. It should help you next time.

![image](https://user-images.githubusercontent.com/468620/205005130-ceb94ac2-83ff-4382-a790-c9131bbeefcb.png)
