### ISSUE TITLE
Add a new endpoint: /features

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#655]
The features are already provided under /first-rows, but some clients, like Autotrain (cc @SBrandeis), are interested in having access to the features, without the first rows.

**Comment by SBrandeis** [comment]
low priority though, as we already have the information with `/rows` where we need that ingo

**Comment by severo** [comment]
`/first-rows`

**Comment by SBrandeis** [comment]
Would it make sense to expose a "simplified" version of the `/first-rows` endpoint, that is easier to consume (especially from JS frontends)?

I understand the advantages of being transparent with the actual objects from `datasets`, but parsing the features can be challenging, especially when dealing with nested features (see https://github.com/huggingface/moon-landing/tree/main/server/lib/datasets).

We could imagine a new endpoint that does all the heavy lifting and outputs data in an easy-to-use format, wdyt? It would also be a way to centralize the processing logic for all dataset-viewer likes in the company.

cc @beurkinger & @lhoestq

**Comment by severo** [comment]
As you mention, /first-rows returns rows and features, where features are an exact dump of the Features returned by the datasets library.

Previously, when /first-rows was called /rows, we were returning instead "columns", with a column type among:
```
"JSON", "BOOL", "INT", "FLOAT", "STRING", "IMAGE_URL", "RELATIVE_IMAGE_URL", "AUDIO_RELATIVE_SOURCES"
```

See https://github.com/huggingface/datasets-server/blob/b36e416cae5a1fb4a34c91d5723032c5f13a5bb3/libs/libutils/src/libutils/types.py#L4 or https://github.com/huggingface/moon-landing/pull/3650/files#diff-64a67deff17881efb7c2974c3d4cb47d9558c70a4d1e24ec7ed6f0c712d1f29aL9 for reference.

I decided to remove this intermediate layer and expose the original `datasets` features. But if needed we can add this kind of simplification of the types if needed.

**Comment by severo** [comment]
Another option would be to offer Python and JavaScript code to parse the responses. Not sure what is the best.

**Comment by beurkinger** [comment]
@severo @SBrandeis 

Not directly related to this PR I think (I'm actually curious to know about the "only the first row" stuff), but something that would be VERY nice to have is to have the `_type` of each cell direclty accessible, so we don't have to do stuff like 
```
features.find((f) => f.name === key)?.type._type === 'ClassLabel'
```
when parsing. It would also makes Cells typing/checking sooooo much easier.

Also in some dataset the value of the ClassLabel seems incorrect ? Like in https://huggingface.co/datasets/glue the label is `-1`, which of course corresponds to nothing in the labels array. Am I missing something ?

> Another option would be to offer Python and JavaScript code to parse the responses. Not sure what is the best.

I'm not sure the user should be needed a library to parse a three row tables containing 15 cells :)

**Comment by severo** [comment]
> I'm actually curious to know about the "only the first row" stuff

The idea of /first-rows is to be able to show a dataset viewer for all the datasets of the Hub. Many of the datasets are big, and downloading and storing them to serve the rows isn't easy. As a first step, we have thus decided to take advantage of the "streaming" feature of datasets, which allowed us to get the first rows of every dataset without the need to download them entirely. We store the 100 first rows of every dataset in a MongoDB database, and serve them with a REST API.

You can find a bit more details in the docs: https://huggingface.co/docs/datasets-server/first_rows

In the (near) future, we will extend the capacities of the datasets server:
- we will download every dataset, convert it to the parquet format, and publish the parquet version on the Hub (in a special branch of the repo)
- we will serve random rows of every dataset, using the parquet version as the source of truth.

Note that we will still publish /first-rows, because it will be computed much quicker after every update of a dataset, so that the dataset viewer on the Hub will be available sooner.

> Also in some dataset the value of the ClassLabel seems incorrect ? Like in https://huggingface.co/datasets/glue the label is -1, which of course corresponds to nothing in the labels array. Am I missing something ?

It's a test split, where the correct label is not given. That's why the value is -1 in that case.

> It would also makes Cells typing/checking sooooo much easier.

I understand the need to parse the values more easily from a client point of view. The code in https://github.com/huggingface/moon-landing/tree/main/server/lib/datasets is clearly complicated (it might be the basis for a client library if needed) and being able to use the REST API with few lines of code is important.
Possibly it would mean converting the "datasets features" to simpler types, on the backend side. Ideally, the same format would apply to /first-rows and to /rows (the future random access from the parquet files).

Let's iterate a bit on this. I'll also bring the subject to the datasets team.

**Comment by beurkinger** [comment]
@severo Thanks a lot for the detailed answer, sorry it took me some time to get around reading it :)

In the end I was able to do what I wanted on the autoTrain side, without writing too much code. On the long term, having type hints at the cell level would really help keep things clean though (at least in the context of this app).

```
Possibly it would mean converting the "datasets features" to simpler types on the backend side. Ideally, the same format would apply to /first-rows and /rows (the future random access from the parquet files).
```
This could help !

**Comment by severo** [comment]
I don't think it's required. We have /info and the parquet files which provide the info
