### ISSUE TITLE
Support HDF5 datasets

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#657]
Can we add [h5py](https://github.com/h5py/h5py) as a dependency to the viewer workers ? It's a pretty common dependency for vision datasets since it allows to read hdf5 files which is common in this field (used by 180k+ repos on github)

related to https://huggingface.co/datasets/sayakpaul/nyu_depth_v2/discussions/5#638a1d4dc7f3cc0d220ea643

cc @severo

**Comment by severo** [comment]
It's already installed:

https://github.com/huggingface/datasets-server/blob/main/workers/datasets_based/poetry.lock#L673

**Comment by lhoestq** [comment]
❤️
