### ISSUE TITLE
Dataset Viewer issue for chengan/tedlium_small

### ISSUE THREAD

**Issue by basanthsk** [huggingface/datasets-server#661]
### Link

https://huggingface.co/datasets/chengan/tedlium_small

### Description

The dataset viewer is not working for dataset chengan/tedlium_small.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Hi, thanks for reporting. I think it's fixed now.

<img width="1572" alt="Capture d’écran 2022-12-12 à 11 52 52" src="https://user-images.githubusercontent.com/1676121/207027508-1717cd5d-9bb8-4493-9e1a-5fdf83cb118d.png">
