### ISSUE TITLE
Dataset Viewer issue for xfact/nq-dpr

### ISSUE THREAD

**Issue by euiyulsong** [huggingface/datasets-server#673]
### Link

https://huggingface.co/datasets/xfact/nq-dpr

### Description

The dataset viewer is not working for dataset xfact/nq-dpr.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
It's working now. It just took some time to prepare.

<img width="1564" alt="Capture d’écran 2023-01-05 à 09 46 12" src="https://user-images.githubusercontent.com/1676121/210738576-ff6b295a-810d-4147-8fc1-008bc3969db0.png">
