### ISSUE TITLE
Dataset Viewer issue for allenai/soda

### ISSUE THREAD

**Issue by skywalker023** [huggingface/datasets-server#674]
### Link

https://huggingface.co/datasets/allenai/soda

### Description

The dataset viewer is not working for dataset allenai/soda.

Error details:

```
Error code:   ResponseNotReady

```

Please help! 🙏🏻

**Comment by severo** [comment]
Fixed! Thanks for pinging us.



<img width="804" alt="Capture d’écran 2023-01-05 à 10 40 05" src="https://user-images.githubusercontent.com/1676121/210749089-2198db86-5e99-42ff-8ccb-58d1870f2850.png">

**Comment by skywalker023** [comment]
Thanks so much!!
