### ISSUE TITLE
Dataset Viewer issue for ivelin/rico_sca_refexp_synthetic_saved

### ISSUE THREAD

**Issue by ivelin** [huggingface/datasets-server#685]
### Link

https://huggingface.co/datasets/ivelin/rico_sca_refexp_synthetic_saved

### Description

The dataset viewer is not working for dataset ivelin/rico_sca_refexp_synthetic_saved.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Yes, the jobs queue behind the dataset viewer is currently long and might take some hours to recover. Sorry about this; we are working on reducing this kind of issue in the future.

**Comment by ivelin** [comment]
Thank you for the prompt response. Much appreciated.
Good to know it's not a bug on my end. Pulling the dataset with the python API works fine, so it's not a critical issue. 
Preview visualization is nice for sharing with others but not time critical. Thank you!

**Comment by severo** [comment]
It has finally been processed:

<img width="1554" alt="Capture d’écran 2023-01-20 à 09 56 04" src="https://user-images.githubusercontent.com/1676121/213655345-ee2638a5-7130-4b4d-b212-841737000839.png">

https://huggingface.co/datasets/ivelin/rico_sca_refexp_synthetic_saved/viewer/ivelin--rico_sca_refexp_synthetic_saved/train

**Comment by ivelin** [comment]
Awesome! Thank you.
