### ISSUE TITLE
Dataset Viewer issue for bigbio/pubmed_qa

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#701]
### Link

https://huggingface.co/datasets/bigbio/pubmed_qa

### Description

this config fails to return the split names: pubmed_qa_labeled_fold6_bigbio_qa

but we get an error even though the other configs work

**Comment by severo** [comment]
somewhat related to #208

**Comment by severo** [comment]
We could fix this conceptually by "splitting" the "splits" processing step into:
- "configs", and expose the configs with `/configs` endpoint,
- then launch N "splits" jobs (one by config), and expose `/splits-in-config` endpoint
The thing is that, if we implement this, we don't know how to "fan-in" to get the response of /splits for all the configs, ie: wait for all the `/splits-in-config` jobs to have finished, then create the `/splits` response by concatening them all.
We could simply compute the response dynamically on every call, but the response time would be worse (in that case we could add another "cache" layer in front of the API server - we already had it in nginx, and we removed it later to make everything simpler)

**Comment by lhoestq** [comment]
`/splits?dataset=...` should keep working since there is a default config, but one should be able to specify another config, maybe with `/splits?dataset=...&config_name=...`

**Comment by severo** [comment]
> /splits?dataset=... should keep working since there is a default config

By the way, currently `/splits` gives the list of all the splits of all the configs, eg https://datasets-server.huggingface.co/splits?dataset=duorc gives:

```json
{
  "splits": [
    {
      "dataset": "duorc",
      "config": "SelfRC",
      "split": "train",
      "num_bytes": 239852925,
      "num_examples": 60721
    },
    {
      "dataset": "duorc",
      "config": "SelfRC",
      "split": "validation",
      "num_bytes": 51662575,
      "num_examples": 12961
    },
    {
      "dataset": "duorc",
      "config": "SelfRC",
      "split": "test",
      "num_bytes": 49142766,
      "num_examples": 12559
    },
    {
      "dataset": "duorc",
      "config": "ParaphraseRC",
      "split": "train",
      "num_bytes": 496683105,
      "num_examples": 69524
    },
    {
      "dataset": "duorc",
      "config": "ParaphraseRC",
      "split": "validation",
      "num_bytes": 106510545,
      "num_examples": 15591
    },
    {
      "dataset": "duorc",
      "config": "ParaphraseRC",
      "split": "test",
      "num_bytes": 115215816,
      "num_examples": 15857
    }
  ]
}
```

But I think we can also break things. At least:
- implement /configs and /splits-in-config (or another better name)
- compute /splits dynamically
- use /configs and /splits-in-config in the Hub to get a quicker response

**Comment by severo** [comment]
BTW: the issue is the same for `/parquet-and-dataset-info`: we compute it for all the configs at once, and if one config fails, the response is an error. We could change to a finer level of granularity (the config).

**Comment by lhoestq** [comment]
I see !

> implement /configs and /splits-in-config (or another better name)

Small pref for `/splits?dataset=...&config=...` and we can do the same for `/parquet-and-dataset-info`, but as you want

**Comment by severo** [comment]
sure, much better:
- `/splits?dataset=...&config=...` returns the cached response
- `/splits?dataset=...` dynamically creates the response

**Comment by severo** [comment]
I'll propose a PR, and let you review, as a way to show how to add or modify a processing step.

**Comment by severo** [comment]
Handled by #734
