### ISSUE TITLE
Dataset Viewer issue for matchbench/semi-text-w

### ISSUE THREAD

**Issue by ScHh0625** [huggingface/datasets-server#704]

**Comment by severo** [comment]
Part of the splits are available, and some are still being computed and should be up soon. We're working to reduce the time to prepare the data for the dataset viewed.

<img width="1561" alt="Capture d’écran 2023-01-26 à 15 07 20" src="https://user-images.githubusercontent.com/1676121/214856305-4d32d753-d81f-421d-bf0f-d3cc3bf22b57.png">
