### ISSUE TITLE
Update poetry lock file format to 2.0

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#710]
Since `poetry` 1.3.0 (9 Dec 2022), a new lock file format is used (version 2.0). See release notes: https://github.com/python-poetry/poetry/releases/tag/1.3.0

We should update our poetry lock files to the new format.

**Comment by severo** [comment]
We should ensure we all use poetry 1.3.0 thus, possibly here: https://github.com/huggingface/datasets-server/blob/main/workers/datasets_based/pyproject.toml#L59 (for each project).

Also, use it in the CI and the dockerfiles (using 1.2.2 for now).

**Comment by albertvillanova** [comment]
I have followed your instructions in the DEVELOPER_GUIDE:
```shell
curl -sSL https://install.python-poetry.org | python3 -
```
getting the latest Poetry version 1.3.2.

**Comment by severo** [comment]
> I mean, following those instructions, the "[workers/datasets_based/pyproject.toml#L59](https://github.com/huggingface/datasets-server/blob/main/workers/datasets_based/pyproject.toml#L59)" you mentioned is not used to establish the installed Poetry version...

Sure, I was thinking of a parameter in `pyproject.toml` that would raise an exception if you try to run poetry lock with an old version of poetry. But this parameter does not seem to exist. As [`engines`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) in npm, where you can tell which is the minimal version of npm to manage the package.
