### ISSUE TITLE
Dataset Viewer issue for rfernand/basic_sentence_transforms

### ISSUE THREAD

**Issue by rfernand2** [huggingface/datasets-server#718]
### Link

https://huggingface.co/datasets/rfernand/basic_sentence_transforms

### Description

The dataset viewer is not working for dataset rfernand/basic_sentence_transforms.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by rfernand2** [comment]
It is working now.  Did it just need a long time to prepare/cache the data somehow?  The data is not that large.

**Comment by severo** [comment]
> Did it just need a long time to prepare/cache the data somehow

Yes. Usually, it should be very quick for small datasets, but we still have issues sometimes when the processing queue gets filled with other datasets. We are working on solutions to reduce this kind of incident.

**Comment by rfernand2** [comment]
The error message hints at that but would be helpful to change it to something for explicit like "Dataset Viewer server is busier than usual; please try again later".   With the current message, I thought it might still be an issue on my side.

Thanks,

- Roland

**Comment by severo** [comment]
Closing, fixed by https://github.com/huggingface/datasets-server/pull/754.
