### ISSUE TITLE
Modify /splits worker

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#734]
The /splits endpoint is now redundant with the /config-names and the /split-names endpoints and can be computed from them.
One benefit is getting a list of configs and splits, even if some configs are erroneous. See #208 and #701.

We want to keep the /splits endpoint (used by the Hub, for example) but compute it from the other responses. Various options:
1. on every request to /splits, get all the /config-names and /split-names responses for the dataset from the database, and forge the response
2. same as 1., but putting a cache layer
3. precompute the /splits response as soon as possible, and put it in the database. 1. it would still require a worker (not a problem), 2. it should be launched after every update of a /config-names or /split-names for the dataset. Possibly the best option.

Pending questions:
- what should be the format if a /split-names response is an error, while the /config-names response is OK. The current /splits worker would generate an error response, which defeats #208 and #701. Ideally, we want to have a list of configs, with the list of splits, or an error if we cannot get them. But we have to keep backwards compatibility, or change it in the Hub and the other known clients.
- how to manage the transition? Even if the format change, I think that the old format would still be a valid result, and we would replace them at our own pace with the new format.

**Comment by severo** [comment]
For the format of /splits, we could add a field with the error (or missing) values.

For now we have:

- success:

```json
{
  "splits": [
    {"dataset":"emotion","config":"split","split":"train"},
    {"dataset":"emotion","config":"split","split":"validation"},
    {"dataset":"emotion","config":"split","split":"test"},
    {"dataset":"emotion","config":"unsplit","split":"train"}
  ]
}
```

- error:

```json
{
  "error": {
    "message": "blablabla"
  }
}
```

When some of the splits are working, and some are not, we could have:

```json
{
  "splits": [
    {"dataset":"emotion","config":"split","split":"train"},
    {"dataset":"emotion","config":"split","split":"validation"},
    {"dataset":"emotion","config":"split","split":"test"},
  ],
  "errors": [
    {"dataset":"emotion","config":"unsplit","error": {"message": "Not ready yet"}},
  ]
}
```

**Comment by severo** [comment]
Once implemented, test with https://huggingface.co/datasets/bigbio/pubmed_qa (this config fails to return the split names: pubmed_qa_labeled_fold6_bigbio_qa, but we get an error even though the other configs work), see #701.

**Comment by severo** [comment]
See proposal at https://github.com/huggingface/datasets-server/issues/755#issuecomment-1428236340

**Comment by AndreaFrancis** [comment]
Both new workers have been already implemented and added to the endpoint list of processing steps
https://github.com/huggingface/datasets-server/blob/a2b67d629c0e7ba85851c7e7cea05af76d4e52c6/services/api/src/api/config.py#L113
Note that previous /splits workers remains as primary source
                "dataset": ["/splits", "dataset-split-names-from-streaming", "dataset-split-names-from-dataset-info"],
@severo suggested to put /splits as the final source and wait until all the datasets have been proceeded for  "dataset-split-names-from-streaming", "dataset-split-names-from-dataset-info" caches

**Comment by severo** [comment]
> @severo suggested to put /splits as the final source and wait until all the datasets have been proceeded for "dataset-split-names-from-streaming", "dataset-split-names-from-dataset-info" caches

Or: launch jobs to fill all the missing cache entries.

**Comment by AndreaFrancis** [comment]
Closing this issue since /splits job runner does not exist and API response was replaced with "dataset-split-names", "dataset-split-names-from-streaming" and "dataset-split-names-from-dataset-info" new job runners.
See https://github.com/huggingface/datasets-server/pull/1025
