### ISSUE TITLE
Fill /split-names and /first-rows from /parquet-and-dataset-info if needed

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#755]
/split-names and /first-rows are created using streaming. They might fail for this reason while /parquet-and-dataset-info works for the same dataset.

In this case, we should fill /split-names (from /dataset-info) and /first-rows (from /parquet).

Note that we would generate a concurrence between two execution paths for the same result: we need to manage this by avoiding launching one of them if we already have the result, and avoiding updating the result if it has already been computed (in the case of concurrent jobs)

**Comment by severo** [comment]
We prepared the switch by deprecating the `FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE` parameter: it's now hard-coded, and that part of the code will be deleted once this issue is fixed:

https://github.com/huggingface/datasets-server/blob/7188c0a4b84b10b88e39ff9f3ad88ae04843402e/workers/datasets_based/src/datasets_based/workers/first_rows.py#L539L561

See #769/#771 and #773

**Comment by AndreaFrancis** [comment]
From https://github.com/huggingface/datasets-server/pull/797#issuecomment-1425445279 comment
**First:** I will first allow processing steps to support cache-kind  different value than endpoint, that way I will be able to create the new worker for split-names-db.  
**Second:** Create new worker for split-names-db, but I have a question here:
> Note that we would generate a concurrence between two execution paths for the same result: we need to manage this by avoiding launching one of them if we already have the result, and avoiding updating the result if it has already been computed (in the case of concurrent jobs)

Don't we already have that logic in should_skip_job worker method? Or is other kind of consideration to have in mind?

**Third:** Create new worker for first-rows ( Maybe /first-rows-parquet)
Does this sounds like a plan?

**Comment by severo** [comment]
> Don't we already have that logic in should_skip_job worker method

yes

> Or is other kind of consideration to have in mind?

yes: imagine the result from split-names-db is already there, and is a success, and that later split-names-streaming finished and is an error: we don't want to store that error. So we have to put a control at the moment where we store the value in the cache to manage the concurrent access.

**Comment by severo** [comment]
I have a proposal.

The same endpoint could have multiple associated processing steps, along two dimensions:

- multiple [cache kinds](https://github.com/huggingface/datasets-server/blob/fb3399aa3a96abe0f46b1c6a9ee8ac9f3358f394/libs/libcommon/src/libcommon/processing_graph.py#L49),
- multiple [input types](https://github.com/huggingface/datasets-server/blob/fb3399aa3a96abe0f46b1c6a9ee8ac9f3358f394/libs/libcommon/src/libcommon/processing_graph.py#L36) (dataset/config/split)

In this issue, we are interested in having two processing steps with different cache kinds for the same endpoint. The idea would be that, when the endpoint is requested, we look if the cache contains the response, with a loop on the associated processing steps, respecting the order we want (for example `["/split-names-db", "/split-names-streaming"]`). So, if `/split-names-db` exists, we return it (be it a success or an error). If not, if `/split-names-streaming` exists, we return it (be it a success or an error). If not, we return an error. One advantage of this solution is that we will not have concurrent access to the cache db, the disadvantage is that we would store the data twice.

The second point is related to https://github.com/huggingface/datasets-server/issues/734. The /splits endpoint would be associated to the cache kinds `/split-names-db` and `split-names-streaming` for the input type `config`, and to a new endpoint to be created, `/dataset-split-names`, for the input type `dataset`. So, if the /splits endpoint is requested with the parameter `dataset`, we reach `/dataset-split-names`, and if it is requested with the parameters `dataset` and `config`, we reach `/split-names-db` and `split-names-streaming` in that order.

WDYT?

**Comment by severo** [comment]
I think that if -db has an error, there is no hope that -streaming is working, bit why not

For the issue with double storage, I think we should not worry. It's better to have a simple logic. And I don't think the storage overhead will be an issue.

**Comment by severo** [comment]
Work in progress

**Comment by AndreaFrancis** [comment]
**Required/implemented tasks for this issue:**
- [ ] Allow api service to respond by input params given a list of processing steps

**/split-names will be changed to /splits?dataset=....&config=....**
- [ ] Implement config level split-names-from-streaming job runner
- [ ] Implement config level split-names-from-dataset-info job runner
- [ ] Change /splits endpoint to response by config using the previous processing steps

**For /first-rows:**
- [ ] Implement config level first-rows-from-parquet job runner
- [ ] Implement config level first-rows-from-streaming job runner (It already exist as /first-rows, maybe a renaming is needed)
- [ ] Change /first-rows endpoint to response by config using the previous processing steps

**Comment by AndreaFrancis** [comment]
First rows have been implemented with job runners split-first-rows-from-streaming and split-first-rows-parquet
Splits have been implemented with job runners split-names-from-streaming and split-names-from-dataset-info

**Comment by severo** [comment]
Do you think we already can delete /splits?
