### ISSUE TITLE
Handle the case where the DatasetInfo is too big

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#762]
In the /parquet-and-dataset-info processing step, if DatasetInfo is over 16MB, we will not be able to store it in MongoDB (https://pymongo.readthedocs.io/en/stable/api/pymongo/errors.html#pymongo.errors.DocumentTooLarge). We have to handle this case, and return a clear error to the user.

See https://huggingface.slack.com/archives/C04L6P8KNQ5/p1675332303097889 (internal). It's a similar issue to https://github.com/huggingface/datasets-server/issues/731 (should be raised for that dataset, btw)

**Comment by AndreaFrancis** [comment]
I think we could have validation size at worker level when getting the content https://github.com/huggingface/datasets-server/blob/main/workers/datasets_based/src/datasets_based/worker.py#L282 and if response size exceeds a MAX_CONTENT_SIZE then raise an exception. This would help us handle size issue not only for dataset-info but for all other workers types.

**Comment by severo** [comment]
Yes, it's a good idea.

I'm wondering what the best way is:
1. adding a MAX_CONTENT_SIZE that could be lower than 16MB and raising if any response is above this size
2. catching the pymongo.errors.DocumentTooLarge exception (i.e. hard-coding MAX_CONTENT_SIZE to 16MB) and raising a new exception with a clear message

Any thoughts?

**Comment by AndreaFrancis** [comment]
I think having max content validation in worker let us decoupled from the database engine, lets say in the future we support another type, we wont depend on mongodb.
Also having the validation at worker level would fix https://github.com/huggingface/datasets-server/issues/770

**Comment by severo** [comment]
OK, let's go with MAX_CONTENT_SIZE then

**Comment by severo** [comment]
Done with #780
