### ISSUE TITLE
Remove `FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE` from code

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#769]
It's not used anymore.

**Comment by JatinKumar001** [comment]
Hey, you are saying to remove FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE from the code then what's the value for "fallback_max_dataset_size" variable?

**Comment by severo** [comment]
It must be deleted too, as well as max_size_fallback

**Comment by JatinKumar001** [comment]
Hey, I remove all the occurrence of FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE and its related variables and open a pull request.

https://github.com/huggingface/datasets-server/pull/771

**Comment by severo** [comment]
done with #771
