### ISSUE TITLE
Dataset Viewer issue for mozilla-foundation/common_voice_11_0

### ISSUE THREAD

**Issue by gassis** [huggingface/datasets-server#776]
### Link

https://huggingface.co/datasets/mozilla-foundation/common_voice_11_0

### Description

The dataset viewer for Portuguese Language is not working for dataset mozilla-foundation/common_voice_11_0.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Thanks for the patience. The jobs queue was under pressure, the dataset viewer is now working.
<img width="804" alt="Capture d’écran 2023-02-08 à 16 58 17" src="https://user-images.githubusercontent.com/1676121/217582473-9545a638-56d4-4b06-9201-9563c2d27345.png">

**Comment by gassis** [comment]
Thank you very much !! It's working perfectly.
