### ISSUE TITLE
Dataset Viewer issue for allenai/scirepeval

### ISSUE THREAD

**Issue by amanpreet692** [huggingface/datasets-server#785]
### Link

https://huggingface.co/datasets/allenai/scirepeval

### Description

The dataset viewer is not working for dataset allenai/scirepeval.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Thanks for your patience. The jobs queue was under pressure; the dataset viewer is now working.

<img width="1517" alt="Capture d’écran 2023-02-08 à 16 58 47" src="https://user-images.githubusercontent.com/1676121/217582608-a86c52e3-1df3-4d78-8552-4f48ae900adb.png">
