### ISSUE TITLE
Handle the 16MB limit in MongoDB with a dedicated error

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#795]
### Description

As per comment on https://github.com/huggingface/datasets-server/pull/780#issuecomment-1422238212 
We should handle the db limitation per document with a dedicated error

**Comment by severo** [comment]
Let's keep it open

**Comment by severo** [comment]
I imagine it's part of https://github.com/huggingface/datasets-server/issues/1443. Let's keep it closed.
