### ISSUE TITLE
Change db migrations from jobs to init containers

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#819]
From comment https://github.com/huggingface/datasets-server/pull/810#discussion_r1105871837

> there are so many past jobs that we don't need anymore that we could delete them periodically. Manually or with a cron job. Otherwise, the migration jobs take forever, and the helm update timeouts and fails

@severo sugesstion: 
> Migrate from jobs to init containers to ensure the migration has time to finish without making Helm upgrade timeout

**Comment by severo** [comment]
A possible implementation is described in https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations
