### ISSUE TITLE
Add `worker_version` to queued `Job`

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#830]
This can be useful when e.g. killing a zombie job because right now we assume that the current worker version is the one the worker was using when the job started.

Then we can properly kill zombie jobs that come from an older worker version.

See https://github.com/huggingface/datasets-server/pull/827#discussion_r1114260946

**Comment by severo** [comment]
should we keep it open, @lhoestq?

**Comment by lhoestq** [comment]
I think it's not high priority for now
