### ISSUE TITLE
Dataset Viewer issue for artem9k/ai-text-detection-pile

### ISSUE THREAD

**Issue by artem9k** [huggingface/datasets-server#841]
### Link

https://huggingface.co/datasets/artem9k/ai-text-detection-pile

### Description

The dataset viewer is not working for dataset artem9k/ai-text-detection-pile. I am trying to load a jsonl file

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
It has finally been fixed. Sorry for the inconvenience.

<img width="1591" alt="Capture d’écran 2023-02-28 à 09 29 23" src="https://user-images.githubusercontent.com/1676121/221796671-72ff20b2-f7e0-4224-89f3-f679a03f052e.png">
