### ISSUE TITLE
Dataset Viewer issue for bridgeconn/snow-mountain

### ISSUE THREAD

**Issue by anjalyjayakrishnan** [huggingface/datasets-server#842]
### Link

https://huggingface.co/datasets/bridgeconn/snow-mountain

### Description

The dataset viewer is not working for dataset bridgeconn/snow-mountain.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
It has finally been fixed. Sorry for the inconvenience.

<img width="1541" alt="Capture d’écran 2023-02-28 à 09 28 09" src="https://user-images.githubusercontent.com/1676121/221796495-1ee1fca2-4c27-4456-a28a-212547cd6623.png">
