### ISSUE TITLE
Support all the characters in dataset, config and split

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#853]
For example, a space is an allowed character in a config, while it's not supported in datasets-server.

https://discuss.huggingface.co/t/problem-with-dataset-preview-with-audio-files/31475/3?u=severo

cc @polinaeterna

**Comment by severo** [comment]
low priority, but let's keep it

**Comment by albertvillanova** [comment]
Still not fixed.

**Comment by polinaeterna** [comment]
should we actually allow characters like spaces? maybe it's better to add validation for whitespace symbols and directly in `datasets` and raise

**Comment by severo** [comment]
I created an issue on datasets: https://github.com/huggingface/datasets/issues/5989. Closing here.
