### ISSUE TITLE
Dataset Viewer issue for openai/summarize_from_feedback

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets-server#855]
### Link

https://huggingface.co/datasets/openai/summarize_from_feedback

### Description

The dataset viewer is not working for dataset openai/summarize_from_feedback.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Thanks for filling a bug. The datasets server infrastructure is under maintenance, we expect it to be back in the next minutes.

**Comment by lewtun** [comment]
Thanks!

**Comment by lewtun** [comment]
It's back, so closing this issue
