### ISSUE TITLE
Dataset Viewer issue for bigscience/P3

### ISSUE THREAD

**Issue by FangxuLiu** [huggingface/datasets-server#856]
### Link

https://huggingface.co/datasets/bigscience/P3

### Description

The dataset viewer is not working for dataset bigscience/P3.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Our infrastructure is under maintenance; it should come back to normality soon. I'll be commenting here.

**Comment by severo** [comment]
Thanks for reporting. It sometimes appears, and it's due to a timeout between the Hub backend and the datasets server. We'll be looking at this. Closing in favor of #877
