### ISSUE TITLE
Support timestamp and date feature types

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#86]
- [ ] add a date type
- [ ] detect dates, ie `allenai/c4` -> `timestamp` , `curiosity_dialogs`

**Comment by severo** [comment]
see also (internal): https://huggingface.slack.com/archives/C0311GZ7R6K/p1680784227964169

**Comment by lhoestq** [comment]
just got
```
bson.errors.InvalidDocument: cannot encode object: datetime.date(2016, 5, 20), of type: <class 'datetime.date'>
```
when running the first rows job for https://huggingface.co/datasets/ClimatePolicyRadar/global-stocktake-documents

It seems the column `date: date32[day]` can't be stored in mongo as is

**Comment by lhoestq** [comment]
I think we store dates using a nice formatting, maybe like "YYYY-MM-DD" for date32 and "YYYY-MM-DDTHH:MM:SSZ" for date64 ?

**Comment by severo** [comment]
Another report: https://huggingface.co/datasets/poloclub/diffusiondb/discussions/2#6374ff55b93cbdf65675f563 (old!)

**Comment by lhoestq** [comment]
Another report: https://huggingface.co/datasets/aborruso/pnrr/discussions/1

**Comment by lhoestq** [comment]
another one: https://huggingface.co/datasets/hyperdemocracy/us-congress-bills/discussions/1#64fd5e06b3eee10ba54990d3

**Comment by severo** [comment]
It should not generate an error since https://github.com/huggingface/datasets-server/pull/1938.

But beyond not raising an exception, we want to fully support the type, in order to get dates histogram for example.

**Comment by lhoestq** [comment]
Now getting this during `upsert_response_params` when `CachedResponseDocument.upsert_one` is called

```
bson.errors.InvalidDocument: cannot encode object: datetime.date(2023, 6, 13), of type: <class 'datetime.date'>
```
