### ISSUE TITLE
Turn /dataset-info into a config-level job

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#864]
We should:
- compute the values for every config independently: `config--dataset-info`
- compute the dataset-level response `dataset--dataset-info` each time a `config--dataset-info` is computed (allowing partial responses: some config responses can be missing or erroneous)
- return the appropriate response on /dataset-info, depending on the inputs (see https://github.com/huggingface/datasets-server/pull/834)

See #735.

**Comment by AndreaFrancis** [comment]
For the new worker /split-names-from-dataset-info, we will probable need to change the source, currently it is /dataset-info [config] but after this is implemented, it will have to be config--dataset-info.
