### ISSUE TITLE
Dataset Viewer issue for docred

### ISSUE THREAD

**Issue by ArchchanaKugathasan** [huggingface/datasets-server#872]
### Link

https://huggingface.co/datasets/docred

### Description

The dataset viewer is not working for dataset docred.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Thanks for reporting. It sometimes appears, and it's due to a timeout between the Hub backend and the datasets server. We'll be looking at this. Closing in favor of #877
