### ISSUE TITLE
Dataset Viewer issue for Matthijs/cmu-arctic-xvectors

### ISSUE THREAD

**Issue by p1sa** [huggingface/datasets-server#876]
### Link

https://huggingface.co/datasets/Matthijs/cmu-arctic-xvectors

### Description

The dataset viewer is not working for dataset Matthijs/cmu-arctic-xvectors.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Thanks for reporting. It sometimes appears, and it's due to a timeout between the Hub backend and the datasets server. We'll be looking at this. Closing in favor of #877
