### ISSUE TITLE
Unsafe warning issue for poloclub/diffusiondb

### ISSUE THREAD

**Issue by xiaohk** [huggingface/datasets-server#882]
### Link

https://huggingface.co/datasets/poloclub/diffusiondb

### Description

Hello 👋, we have seen the below warning on [our dataset](https://huggingface.co/datasets/poloclub/diffusiondb) on hugging face. The flagged file is a [zip file](https://huggingface.co/datasets/poloclub/diffusiondb/blob/main/images/part-000989.zip).

```
Virus: Multios.Backdoor.Msfvenom_Payload-9951536-0
```

![image](https://user-images.githubusercontent.com/15007159/222321545-57a90142-4e33-4693-93c8-e9e2f0339f31.png)

This zip file only contains 1000 images and a json file. I don't think there is any security concern among these files. I tried to (1) re-load and re-export all images using PIL and (2) re-zip and re-upload this particular file in [this commit](https://huggingface.co/datasets/poloclub/diffusiondb/commit/527749109c86eda3c82027143e45964e75cbf772). However, the same error comes back again 😭.

Do you have any suggestions on how to fix it please? Thank you!

**Comment by severo** [comment]
Assigning to @McPatate, who provides support for the vulnerabilities scanner.

**Comment by McPatate** [comment]
Pinged the ClamAV team about this, indeed when I unzip and run the scanner nothing appears to be dangerous.

I'll let you know if the zip is a false positive or actually unsafe.

**Comment by McPatate** [comment]
Got a reply from the ClamAV team, they're investigating and think it's probably a false positive. Until it's updated, for now I'll leave it as is.

Sorry for the inconvenience, false positives do happen with AVs from time to time.

**Comment by xiaohk** [comment]
Thank you so much, @severo and @McPatate! ❤️

**Comment by xiaohk** [comment]
Hello @McPatate, is there any update from the ClamAV team on this issue?

**Comment by xiaohk** [comment]
Comment to prevent stale label 😄

**Comment by McPatate** [comment]
Ah sorry, forgot to reply @xiaohk, haven't had any news from the ClamAV team.

We don't re-scan files once they've been scanned atm, I have to add that to the repo scanner since the virus db changes over time. I'll let you know if I see something new. Thanks for keeping us updated!

**Comment by severo** [comment]
Still no news @McPatate ?

**Comment by xiaohk** [comment]
> There are some improvements I'd like to work on to make the scanner more scalable and add the periodic re-scanning of files. Until then I can manually re-trigger your scan if you want, lmk.

Sounds good! Thank you so much! 🙏

**Comment by xiaohk** [comment]
The warning has disappeared! Thank you @McPatate and @severo! ❤️ ❤️

**Comment by xiaohk** [comment]
Hello @McPatate, it seems the same warning has come back (to the same file...)

https://huggingface.co/datasets/poloclub/diffusiondb

<img width="440" alt="Monosnap poloclub:diffusiondb · Datasets at Hugging Face 2023-10-18 15-36-09" src="https://github.com/huggingface/datasets-server/assets/15007159/17ccb898-afb2-41ac-81fb-82e5bdfc1838">
