### ISSUE TITLE
Store /valid and /is-valid in the cache

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#891]
Pre-computing /is-valid (for each dataset) and /valid (for all the datasets) and storing the responses in that cache would help reduce the latency of these endpoints and the compute load on the API service. They are the only two endpoints that are calculated on the fly.

Another benefit: it would remove the particular field `required_by_dataset_viewer` in https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/processing_graph.py because the same property could be defined as dependencies between processing steps:
- /is-valid would depend on /splits and /first-rows
- /valid would depend on /is-valid

Note that we would have to add a value to [InputType](https://github.com/huggingface/datasets-server/blob/0539fbd1950bfbe89605ddd40db1aaebfc757438/libs/libcommon/src/libcommon/processing_graph.py#L10) for /valid. None? Optional?

Thanks, @AndreaFrancis, for the discussion that allowed rethinking this part.

---

- [x] create `dataset-is-valid` https://github.com/huggingface/datasets-server/pull/1032
- [ ] create `valid`
  - [ ] add `none` in InputType, and make the `dataset` parameter optional where it makes sense (it is currently mandatory nearly everywhere in the code)
  - [ ] add the `valid` step
- [ ] deploy and fill the cache. Done for `is-valid`
- [ ] switch the /valid and /is-valid endpoints. PR for `is-valid`: https://github.com/huggingface/datasets-server/pull/1160

**Comment by severo** [comment]
We have to work on this to reduce the latency

**Comment by severo** [comment]
I'll work on adding the step `dataset-is-valid which will only depend on `split-first-rows-from-streaming` and `split-first-rows-from-parquet` (if we have at least one of them working, it means that we have the list of configs and splits).

**Comment by severo** [comment]
- [ ] create `dataset-is-valid` https://github.com/huggingface/datasets-server/pull/1032
- [ ] create `valid` https://github.com/huggingface/datasets-server/pull/1032
- [ ] deploy and fill the cache
- [ ] switch the /valid and /is-valid endpoints

**Comment by severo** [comment]
For `valid`: maybe include the list of feature types, to enable filtering by feature type?

See https://github.com/huggingface/datasets-server/issues/561 and https://github.com/huggingface/datasets-server/pull/833#issuecomment-1517689866. cc @lhoestq

**Comment by lhoestq** [comment]
Oh that could be great !

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
keep open. I'll take care of it.

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
Closing this issue, as it's done for /is-valid, and we will switch /valid to Server-sent events. Sending the full list is not scalable, and we are struggling with this now.
