### ISSUE TITLE
Dataset Viewer issue for hendrycks_test

### ISSUE THREAD

**Issue by shiyujiaaaa** [huggingface/datasets-server#892]
### Link

https://huggingface.co/datasets/hendrycks_test

### Description

The dataset viewer is not working for dataset hendrycks_test.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Yes, we've had a backend issue. It's working again. Sorry for the inconvenience.

**Comment by severo** [comment]
To be improved with #877.
