### ISSUE TITLE
Dataset Viewer issue for hendrycks/ethics

### ISSUE THREAD

**Issue by xksteven** [huggingface/datasets-server#899]
### Link

https://huggingface.co/datasets/hendrycks/ethics

### Description

The dataset viewer is not working for dataset hendrycks/ethics.

Error details:

```
Error code:   ResponseNotReady

```

How do I debug this?

**Comment by severo** [comment]
Hi! Thanks for opening the issue. The response will eventually be computed by our backend and returned. It might take some hours, since we're currently experiencing some issues. Please retry later. Sorry for the inconvenience.

**Comment by AndreaFrancis** [comment]
Sorry for the inconvenience, the service is up again and the issue is fixed.
