### ISSUE TITLE
Dataset Viewer issue for mc4

### ISSUE THREAD

**Issue by yonikremer** [huggingface/datasets-server#902]
### Link

https://huggingface.co/datasets/mc4

### Description

The dataset viewer is not working for dataset mc4.

When I tried to look into subsets of the mc4 dataset I got the following error:

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
The dataset viewer sometimes takes a moment to refresh. It's fixed now, sorry for the inconvenience.

<img width="1033" alt="Capture d’écran 2023-03-08 à 10 33 40" src="https://user-images.githubusercontent.com/1676121/223676280-2025aa3d-d0c7-4aff-9e3b-3d381bc0e5fb.png">
