### ISSUE TITLE
Dataset Viewer issue for Yusuf5/OpenCaselist

### ISSUE THREAD

**Issue by Hellisotherpeople** [huggingface/datasets-server#907]
### Link

https://huggingface.co/datasets/Yusuf5/OpenCaselist

### Description

The dataset viewer is not working for dataset Yusuf5/OpenCaselist.

Error details:

```
Error code:   ResponseNotReady

```
NOTE: This is a 40GB CSV file, of several million debate documents. It's a follow up to DebateSum 

https://huggingface.co/datasets/Hellisotherpeople/DebateSum

**Comment by severo** [comment]
Yes, the dataset viewer can take some time to be ready, depending on the dataset. It's working now.

<img width="1021" alt="Capture d’écran 2023-03-08 à 10 36 07" src="https://user-images.githubusercontent.com/1676121/223676838-c1cf28fe-f65c-462d-84bc-30f55358d40f.png">
