### ISSUE TITLE
`/parquet-and-dataset-info` is processing datasets bigger than 5GB

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#908]
e.g. right now it's processing https://huggingface.co/datasets/madrylab/imagenet-star/tree/main

![image](https://user-images.githubusercontent.com/42851186/223496629-750acc52-0f05-4fcf-b466-9cf89083a674.png)

Though I checked and `PARQUET_AND_DATASET_INFO_MAX_DATASET_SIZE` is defined by 
```
parquetAndDatasetInfo:
  maxDatasetSize: "5_000_000_000"
```

**Comment by AndreaFrancis** [comment]
Same behavior with https://huggingface.co/datasets/CYHSM/asp/tree/main dataset.

**Comment by severo** [comment]
we have to look at it

**Comment by severo** [comment]
to be done

**Comment by severo** [comment]
We have false positives, but it's not a big issue, I think. See https://huggingface.co/datasets/Muennighoff/multi_eurlex for example.
