### ISSUE TITLE
Use pydantic, or msgspec, for validation+serialization+OpenAPI spec generation

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#913]
See https://docs.pydantic.dev (https://docs.pydantic.dev/usage/settings/ for the config)

Alternative: https://jcristharif.com/msgspec/

Usages:
- validate query parameters in API endpoints
- validate data fetched from the database (we do it manually, in case some data are malformed)
- serialize the API responses to JSON (we use orjson)
- generate JSON schema (ie OpenAPI spec) from code
- use constraints in validation (>0, etc)

**Comment by severo** [comment]
It could also replace `jsonschema`

**Comment by severo** [comment]
anyone has an opinion on this? @huggingface/datasets-server

**Comment by polinaeterna** [comment]
I remember @anton-l had some arguments against using `pydantic` but I don't remember what they are exactly :D
