### ISSUE TITLE
Dataset Viewer issue for gsdf/EasyNegative

### ISSUE THREAD

**Issue by Usonw** [huggingface/datasets-server#922]
### Link

https://huggingface.co/datasets/gsdf/EasyNegative

### Description

The dataset viewer is not working for dataset gsdf/EasyNegative.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by severo** [comment]
Thanks for reporting. It sometimes appears, and it's due to a timeout between the Hub backend and the datasets server. We'll be looking at this. Closing in favor of https://github.com/huggingface/datasets-server/issues/877
