### ISSUE TITLE
Dataset Viewer issue for domro11/lectures

### ISSUE THREAD

**Issue by domro11** [huggingface/datasets-server#946]
### Link

https://huggingface.co/datasets/domro11/lectures

### Description

The dataset viewer is not working for dataset domro11/lectures.

Error details:

```
Error code:   ResponseNotReady

```
Furthermore not able to incorporate dataset wtih streamlit app as ask for a need to differentiate between train and test

**Comment by severo** [comment]
Thanks for reporting. The dataset viewer can take some time to refresh after a dataset update. The dataset viewer new shows a result.

<img width="1024" alt="Capture d’écran 2023-03-17 à 09 37 20" src="https://user-images.githubusercontent.com/1676121/225854460-e12c24b5-dc1c-4449-b3d3-18849e9dd468.png">

It's an error, though. @albertvillanova @lhoestq do you have recommendations for such a dataset (a list of one-line text files)?

**Comment by albertvillanova** [comment]
Let me have a look...
