### ISSUE TITLE
More than half of the received webhooks are ignored!

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#950]
An exception is raised (400 is returned) and thus the update jobs are not created, leading to many outdated dataset viewers on the Hub.

**Comment by severo** [comment]
It has started yesterday.

<img width="398" alt="Capture d’écran 2023-03-17 à 11 03 08" src="https://user-images.githubusercontent.com/1676121/225874016-f6b943bc-0dd9-4f5f-adee-85bff4056e10.png">

**Comment by albertvillanova** [comment]
Just right now I had this issue again for: https://huggingface.co/datasets/cmu_hinglish_dog

**Comment by severo** [comment]
I fixed the issue by increasing the timeout value for requests to the Hub (200ms -> 1.5s) - #952.

We have not experienced new errors in the last 8 minutes. Closing.
