### ISSUE TITLE
Dataset Viewer issue for orkg/SciQA

### ISSUE THREAD

**Issue by YaserJaradeh** [huggingface/datasets-server#953]
### Link

https://huggingface.co/datasets/orkg/SciQA

### Description

Hi,
I'm trying to upload my dataset to the hub, and it seems everything is working when using the data via the python package, however, the dataset viewer is not working for dataset orkg/SciQA.

Error details:
```
Error code:   ResponseNotFound

```

**Comment by severo** [comment]
Yes, we had an issue that prevented updating the dataset viewer (#950). It's fixed now. Thanks for reporting!

https://huggingface.co/datasets/orkg/SciQA

**Comment by YaserJaradeh** [comment]
Thanks for the fast reply
