### ISSUE TITLE
Dataset Viewer issue for vhug/xorder_dish_dataset

### ISSUE THREAD

**Issue by v-prgmr** [huggingface/datasets-server#956]
### Link

https://huggingface.co/datasets/vhug/xorder_dish_dataset

### Description

The dataset viewer is not working for dataset vhug/xorder_dish_dataset.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by albertvillanova** [comment]
@severo you mean: https://huggingface.co/datasets/vhug/xorder_dish_dataset

And the dataset has been deleted.

**Comment by severo** [comment]
Yes, sorry, I edited the message

**Comment by severo** [comment]
Closing
