### ISSUE TITLE
Dataset Viewer issue for Crapp/sadQuotes

### ISSUE THREAD

**Issue by crapptrapp** [huggingface/datasets-server#957]
### Link

https://huggingface.co/datasets/Crapp/sadQuotes

### Description

The dataset viewer is not working for dataset Crapp/sadQuotes.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Fixed, thanks for reporting!

<img width="1032" alt="Capture d’écran 2023-03-20 à 10 40 21" src="https://user-images.githubusercontent.com/1676121/226301825-81f73067-41a1-44bf-82d0-a52f621a1e12.png">
