### ISSUE TITLE
Dataset Viewer issue for shainaraza/clinical_bias

### ISSUE THREAD

**Issue by shainaraza** [huggingface/datasets-server#959]
### Link

https://huggingface.co/datasets/shainaraza/clinical_bias

### Description

The dataset viewer is not working for dataset shainaraza/clinical_bias.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
I cannot access https://huggingface.co/datasets/shainaraza/clinical_bias anymore. Did you turn it private or delete it?

**Comment by albertvillanova** [comment]
The dataset is private and the dataset viewer does not support private datasets.

**Comment by albertvillanova** [comment]
The dataset is public now and the viewer works as expected.

![Screenshot from 2023-04-19 09-55-11](https://user-images.githubusercontent.com/8515462/233007595-e582ac02-c16e-4071-a532-6da0641a10cc.png)

I'm closing this issue.
