### ISSUE TITLE
Dataset Viewer issue for j-krzywdziak/test

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#966]
### Link

https://huggingface.co/datasets/j-krzywdziak/test

### Description

Hi, recently I am having a problem with dataset viewer. I cannot get the preview of audio files in my dataset. I am getting this error :
ERROR: type should be audio, got [ { "src": "https://datasets-server.huggingface.co/assets/j-krzywdziak/test/--/Test Dataset/test/2/audio/audio.mp3", "type": "audio/mpeg" }, { "src": "https://datasets-server.huggingface.co/assets/j-krzywdziak/test/--/Test Dataset/test/2/audio/audio.wav", "type": "audio/wav" } ]
Audio files are zipped and are in wav format. Anyone have any idea?

https://discuss.huggingface.co/t/audio-files-view-error/31624

<img width="1021" alt="Capture d’écran 2023-03-20 à 18 51 25" src="https://user-images.githubusercontent.com/1676121/226425185-e765d2ac-e61b-46ee-8d75-e0a9b78ae4b0.png">

**Comment by albertvillanova** [comment]
I can have a look at this.

**Comment by polinaeterna** [comment]
related to https://github.com/huggingface/datasets-server/issues/853

**Comment by severo** [comment]
Still not fixed. Reopen
