### ISSUE TITLE
Dataset Viewer issue for RUCAIBox/Open-Dialogue

### ISSUE THREAD

**Issue by Open-ChatGPT** [huggingface/datasets-server#968]
### Link

https://huggingface.co/datasets/RUCAIBox/Open-Dialogue

### Description

The dataset viewer is not working for dataset RUCAIBox/Open-Dialogue.

Error details:

```11可能会近两年
Error code:   ResponseNotFound

```

**Comment by albertvillanova** [comment]
I'm investigating this.

**Comment by albertvillanova** [comment]
Hi @NB112211, 

I think this is not a specific issue with the dataset viewer but with the dataset itself: it requires a loading script.

I have created a discussion in the Community tab of the dataset: https://huggingface.co/datasets/RUCAIBox/Open-Dialogue/discussions/2
Let's continue the discussion there.

I'm closing this issue.
