### ISSUE TITLE
Parquet files should be deleted if a dataset goes above the limit

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#980]
In step /parquet-and-dataset-info, we fail fast if the dataset is too big. But we miss a corner case: if the dataset was under the limit, but is later updated and ends with a size above the limit. In that case, it already contains parquet files in the `refs/convert/parquet` branch. When the dataset is updated (webhook received, jobs launched), an error is stored in the cache. Still, the parquet files on the Hub remain unchanged, corresponding to the last working version, which means they might now be unsynchronized with the `main` branch.

**Comment by severo** [comment]
Note that I created the issue based on https://huggingface.co/datasets/alexandrainst/da-wit

As of today (2023/03/23), it contains parquet files in the `refs/convert/parquet` branch: https://huggingface.co/datasets/alexandrainst/da-wit/tree/refs%2Fconvert%2Fparquet/alexandrainst--danish-wit
<img width="1006" alt="Capture d’écran 2023-03-23 à 15 15 32" src="https://user-images.githubusercontent.com/1676121/227238551-e46d7d29-36fb-408f-a433-37e4427723d8.png">

Last updated 4 months ago.

But the response to https://datasets-server.huggingface.co/parquet-and-dataset-info?dataset=alexandrainst/danish-wit is

```
{"error":"The dataset is too big to be converted to Parquet. The size of the dataset (8384818740.5 B, as given per the datasets library) exceeds the maximum supported size (5000000000 B). Please report the issue."}
```

It might be that we computed the parquet files with a higher max supported size and changed that value later... The main branch has not changed, so the parquet files must remain valid.

**Comment by severo** [comment]
Let's keep open. It should be part of a bigger issue, on how to clean dangling assets/parquet files/cache entries, etc.

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
We must keep it open. It's somewhat related to #1122 and #1284 (cleaning dangling resources)

**Comment by severo** [comment]
@lhoestq  what do you think of this issue? Maybe we are missing a step which is removing the existing parquet files, if we are not able to create parquet files anymore for the current revision. Cases I see:
- the dataset is now too big, and the parquet files will be stored under partial/ instead of the root (I think the old files will be deleted, right?)
- the dataset is now too big, and is not streamable: the parquet files should be deleted

**Comment by lhoestq** [comment]
> the dataset is now too big, and the parquet files will be stored under partial/ instead of the root (I think the old files will be deleted, right?)

yup correct, the old files are deleted

> the dataset is now too big, and is not streamable: the parquet files should be deleted

yes that's an issue indeed but is not super common

**Comment by severo** [comment]
OK. Do we close it? Or leave open forever with low priority?

**Comment by lhoestq** [comment]
open + low prio sounds good

**Comment by severo** [comment]
replaced by #2384
