### ISSUE TITLE
Appropiate HTTPStatus code in worker Custom Exception classes

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#998]
Context @severo's comment https://github.com/huggingface/datasets-server/pull/995#discussion_r1151161546
For now we support only error 500 INTERNAL_SERVER_ERROR and 501 NOT_IMPLEMENTED error as part of custom Exception classes in worker project.
But this could be misunderstood since we manage those error in purpose and they are not a result of another request or dependent module.
We should evaluate each case and change to an appropiate HTTPStatus code.

**Comment by severo** [comment]
keep open

**Comment by severo** [comment]
who wants to take this issue @huggingface/datasets-server ?

**Comment by severo** [comment]
closing in favor of #1662
