### ISSUE TITLE
Use the huggingface_hub webhook server?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#999]
See https://github.com/huggingface/huggingface_hub/pull/1410

The/webhook endpoint could live in its pod with the huggingface_hub webhook server. Is it useful for our project? Feel free to comment.

**Comment by severo** [comment]
cc @Wauplin

**Comment by Wauplin** [comment]
Idk what your use case would be but happy to chat if you want to discuss it :)

**Comment by Wauplin** [comment]
Just remembered about this issue. Webhooks server is now available in huggingface_hub>=0.14 🤗
